// The ten archetypes: one record each. Everything the rooms show comes from here.
// Atlas scores run from -1 to 1 on each dimension. They are an interpretive sketch, not a measurement.

export const DIMS = [
  { id: 'act', lo: 'Inward', hi: 'Outward', note: 'receives the world, or acts on it' },
  { id: 'order', lo: 'Change', hi: 'Order', note: 'unsettles things, or holds them in place' },
  { id: 'mind', lo: 'Body', hi: 'Mind', note: 'meets reality through the body, or through thought' },
  { id: 'with', lo: 'Alone', hi: 'Together', note: 'goes alone, or works through other people' },
  { id: 'time', lo: 'Present', hi: 'Future', note: 'lives in the moment, or for what comes next' },
]

export const ARCHETYPES = [
  {
    id: 'scientist', no: 'I', name: 'Scientist', verb: 'understand', color: '#1f4fd8', fg: '#f7f5f0',
    question: 'How does it work?',
    instrument: 'The experiment',
    gift: 'Knowledge that can be checked by anyone, and outlives the person who found it.',
    shadow: 'Mistaking the map for the territory; treating whatever cannot be measured as unreal.',
    exemplars: ['Marie Curie', 'Charles Darwin', 'Rosalind Franklin'],
    quote: ['The first principle is that you must not fool yourself, and you are the easiest person to fool.', 'Richard Feynman, Caltech commencement, 1974'],
    play: 'Click to add an observation. The line is refitted to all of them.',
    glyph: 'M12 42a30 30 0 1 0 60 0a30 30 0 1 0 -60 0M63 63L88 88',
    at: { act: -0.15, order: 0.55, mind: 0.85, with: 0.1, time: 0.3 },
  },
  {
    id: 'engineer', no: 'II', name: 'Engineer', verb: 'build', color: '#f26a1b', fg: '#0c0c0c',
    question: 'How can we make it work?',
    instrument: 'The plan',
    gift: 'Things that work, for people who will never know your name.',
    shadow: 'Building because it can be built; the machine that outgrows its purpose.',
    exemplars: ['Imhotep', 'Filippo Brunelleschi', 'Isambard Kingdom Brunel'],
    quote: ['Give me a place to stand, and I will move the earth.', 'Attributed to Archimedes'],
    play: 'Move along the bridge to carry the load across it.',
    glyph: 'M8 80L50 18L92 80ZM29 49L50 80L71 49Z',
    at: { act: 0.65, order: 0.55, mind: 0.25, with: 0.35, time: 0.8 },
  },
  {
    id: 'warrior', no: 'III', name: 'Warrior', verb: 'overcome', color: '#a8161f', fg: '#f7f5f0',
    question: 'What stands in the way?',
    instrument: 'Discipline',
    gift: 'Courage: the will to hold a line, and to keep going when it costs something.',
    shadow: 'Needing an enemy to feel alive; strength that forgets what it was for.',
    exemplars: ['Achilles', 'Joan of Arc', 'Miyamoto Musashi'],
    quote: ['To subdue the enemy without fighting is the supreme excellence.', 'Sun Tzu, The Art of War (trans. Giles)'],
    play: 'Cut through the current. It closes again behind you.',
    glyph: 'M18 88L50 10L82 88M50 10V96M34 66H66',
    at: { act: 0.9, order: 0.05, mind: -0.75, with: 0.35, time: -0.4 },
  },
  {
    id: 'artist', no: 'IV', name: 'Artist', verb: 'create', color: '#e0157a', fg: '#f7f5f0',
    question: 'What could it be?',
    instrument: 'The medium',
    gift: 'New forms for feelings that had none; a way of seeing that stays after you look away.',
    shadow: 'Self-absorption; beauty used as an excuse for anything.',
    exemplars: ['Katsushika Hokusai', 'Johann Sebastian Bach', 'Frida Kahlo'],
    quote: ['Art does not reproduce the visible; rather, it makes visible.', 'Paul Klee, Creative Confession, 1920'],
    play: 'Draw. Every mark is answered five more times.',
    glyph: 'M50 50a5 5 0 0 1 10 0a10 10 0 0 1-20 0a15 15 0 0 1 30 0a20 20 0 0 1-40 0a25 25 0 0 1 50 0',
    at: { act: 0.45, order: -0.5, mind: 0, with: -0.45, time: 0.1 },
  },
  {
    id: 'philosopher', no: 'V', name: 'Philosopher', verb: 'question', color: '#26285e', fg: '#f7f5f0',
    question: 'What is it, really?',
    instrument: 'The question',
    gift: 'Clarity about what we actually mean, and about what we only thought we knew.',
    shadow: 'Doubting everything and deciding nothing; cleverness instead of wisdom.',
    exemplars: ['Socrates', 'Zhuangzi', 'Simone de Beauvoir'],
    quote: ['The unexamined life is not worth living.', 'Socrates, in Plato’s Apology'],
    play: 'Click near any thought to ask another question of it.',
    glyph: 'M31 33a19 19 0 1 1 27 17c-6 4-8 8-8 15M50 80v6',
    at: { act: -0.6, order: -0.35, mind: 0.95, with: -0.35, time: 0 },
  },
  {
    id: 'explorer', no: 'VI', name: 'Explorer', verb: 'discover', color: '#0e7a52', fg: '#f7f5f0',
    question: 'What lies beyond?',
    instrument: 'The map',
    gift: 'A wider world: the edge of the known pushed a little further out.',
    shadow: 'Never arriving anywhere; conquest calling itself discovery.',
    exemplars: ['Ibn Battuta', 'Zheng He', 'Ernest Shackleton'],
    quote: ['We shall not cease from exploration, and the end of all our exploring will be to arrive where we started and know the place for the first time.', 'T. S. Eliot, Little Gidding, 1942'],
    play: 'Move through the fog. What you uncover stays uncovered.',
    glyph: 'M50 6L58 42L94 50L58 58L50 94L42 58L6 50L42 42Z',
    at: { act: 0.6, order: -0.8, mind: -0.3, with: -0.3, time: 0.55 },
  },
  {
    id: 'monk', no: 'VII', name: 'Monk', verb: 'transcend', color: '#e3a21a', fg: '#0c0c0c',
    question: 'What remains when I let go?',
    instrument: 'Attention',
    gift: 'A peace that does not depend on circumstances.',
    shadow: 'Escape dressed as transcendence; calm that has stopped caring.',
    exemplars: ['Siddhartha Gautama', 'Milarepa', 'Thomas Merton'],
    quote: ['Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.', 'Zen saying'],
    play: 'Hold still. The circle only forms when you stop moving.',
    glyph: 'M74.4 20.9A38 38 0 1 0 87.2 42.1',
    at: { act: -0.95, order: 0.45, mind: 0.4, with: -0.75, time: -0.85 },
  },
  {
    id: 'sovereign', no: 'VIII', name: 'Sovereign', verb: 'shape', color: '#5a2a8a', fg: '#f7f5f0',
    question: 'How should it be ordered?',
    instrument: 'The law',
    gift: 'An order inside which other people can flourish.',
    shadow: 'Tyranny; order kept for its own sake, and for the one who keeps it.',
    exemplars: ['Ashoka', 'Elizabeth I', 'Marcus Aurelius'],
    quote: ['No more talk about what a good man should be. Be one.', 'Marcus Aurelius, Meditations X.16 (translations vary)'],
    play: 'Bring your hand into the crowd and it falls into ranks around you.',
    glyph: 'M14 78V30L34 52L50 20L66 52L86 30V78Z',
    at: { act: 0.8, order: 0.95, mind: 0.3, with: 0.95, time: 0.7 },
  },
  {
    id: 'hedonist', no: 'IX', name: 'Hedonist', verb: 'experience', color: '#f47c6c', fg: '#0c0c0c',
    question: 'What does it feel like?',
    instrument: 'The senses',
    gift: 'Presence: the world savoured rather than used.',
    shadow: 'The treadmill of more; pleasure that has become a need.',
    exemplars: ['Epicurus', 'Omar Khayyam', 'Dionysus'],
    quote: ['By pleasure we mean the absence of pain in the body and of trouble in the soul.', 'Epicurus, Letter to Menoeceus (paraphrased); gentler than his reputation'],
    play: 'Move slowly. Every touch blooms, and fades.',
    glyph: 'M41 50a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M37 22a13 13 0 1 0 26 0a13 13 0 1 0 -26 0M37 78a13 13 0 1 0 26 0a13 13 0 1 0 -26 0M9 50a13 13 0 1 0 26 0a13 13 0 1 0 -26 0M65 50a13 13 0 1 0 26 0a13 13 0 1 0 -26 0',
    at: { act: -0.35, order: -0.2, mind: -0.95, with: 0.35, time: -1 },
  },
  {
    id: 'trickster', no: 'X', name: 'Trickster', verb: 'disrupt', color: '#c2d82b', fg: '#0c0c0c',
    question: 'What if it’s the other way round?',
    instrument: 'The joke',
    gift: 'Renewal: the rules made visible by being broken, and the stuck thing set moving again.',
    shadow: 'Cynicism; disruption with nothing to follow it.',
    exemplars: ['Hermes', 'Anansi', 'Coyote', 'Loki'],
    quote: ['The trickster is the boundary-crosser, and a culture without one stops changing.', 'After Lewis Hyde, Trickster Makes This World, 1998 (paraphrased)'],
    play: 'Touch the order. It comes undone, then slowly forgets that it did.',
    glyph: 'M8 28L32 76L50 38L68 76L92 28',
    at: { act: 0.35, order: -1, mind: 0.25, with: 0.2, time: -0.4 },
  },
]

export const byId = Object.fromEntries(ARCHETYPES.map((a) => [a.id, a]))

// Kinships. Allies work together; opposites pull in contrary directions; unions are the rare people who were both.
export const LINKS = {
  allies: [
    ['scientist', 'engineer', 'One finds out how it works, the other makes it work.'],
    ['scientist', 'explorer', 'The expedition and the observation have always travelled together.'],
    ['philosopher', 'scientist', 'Science began as natural philosophy.'],
    ['engineer', 'sovereign', 'Roads, aqueducts and walls: the works of rule.'],
    ['warrior', 'sovereign', 'The sword and the crown.'],
    ['artist', 'hedonist', 'Both trust the senses.'],
    ['artist', 'trickster', 'Both break forms to make new ones.'],
    ['philosopher', 'monk', 'Both turn away from appearances to ask what lies beneath.'],
    ['explorer', 'warrior', 'Both go toward what others avoid.'],
  ],
  opposites: [
    ['monk', 'hedonist', 'Let go of the world, or taste all of it.'],
    ['sovereign', 'trickster', 'Make the order, or make fun of it.'],
    ['engineer', 'philosopher', 'Build it, or ask whether it should be built.'],
    ['scientist', 'artist', 'Find out what is, or make what is not. C. P. Snow’s “two cultures”, 1959.'],
    ['explorer', 'sovereign', 'The frontier and the capital.'],
  ],
  unions: [
    ['warrior', 'monk', 'The warrior-monk: Shaolin, and the samurai who sat zazen.'],
    ['philosopher', 'sovereign', 'Plato’s philosopher-king, and Marcus Aurelius, who nearly was one.'],
    ['scientist', 'artist', 'Leonardo, who drew to understand.'],
    ['engineer', 'trickster', 'The hacker: building by breaking.'],
    ['explorer', 'monk', 'The pilgrim, who travels in order to arrive inward.'],
  ],
}

// One World, Ten Encounters: three things, and how each of the ten meets them.
// Each thing is a silhouette in a 600 × 400 box, with a high point and a centre for the drawings to use.
export const THINGS = [
  {
    id: 'mountain', name: 'A mountain',
    path: 'M0 400L120 250L190 300L300 90L380 220L430 180L600 400Z', peak: [300, 90], centre: [300, 290],
    lines: {
      scientist: 'Measures its height, dates its rock, and asks how it rose.',
      engineer: 'Sees where the tunnel should go.',
      warrior: 'Climbs it. A mountain is an opponent that never tires.',
      artist: 'Paints it again and again, as Hokusai made Thirty-six Views of Mount Fuji.',
      philosopher: 'Asks whether it is the same mountain from both sides.',
      explorer: 'Wants to know what is on the other side.',
      monk: 'Sits at its foot until it is no longer separate.',
      sovereign: 'Draws the border along its ridge.',
      hedonist: 'Takes the cable car up, for the view and the lunch.',
      trickster: 'Moves the summit marker ten metres, to see who notices.',
    },
  },
  {
    id: 'sea', name: 'The sea',
    path: 'M0 210Q75 180 150 210T300 210T450 210T600 210L600 400L0 400Z', peak: [450, 210], centre: [300, 300],
    lines: {
      scientist: 'Samples its salt and charts its currents.',
      engineer: 'Builds the harbour, the ship and the lighthouse.',
      warrior: 'Rows against the storm.',
      artist: 'Spends a lifetime on the colour of one wave.',
      philosopher: 'Asks, after Heraclitus, whether anyone steps into the same water twice.',
      explorer: 'Sails toward the edge of the chart.',
      monk: 'Listens to it until there is only listening.',
      sovereign: 'Claims twelve nautical miles of it.',
      hedonist: 'Swims in it at midnight.',
      trickster: 'Sends out a message in a bottle that says: do not open this.',
    },
  },
  {
    id: 'stranger', name: 'A stranger',
    path: 'M245 150a55 55 0 1 0 110 0a55 55 0 1 0-110 0ZM160 400C160 290 225 245 300 245C375 245 440 290 440 400Z', peak: [300, 95], centre: [300, 300],
    lines: {
      scientist: 'Wonders what made them who they are.',
      engineer: 'Asks what they need, and how it could be made.',
      warrior: 'Decides quickly: friend, or threat.',
      artist: 'Draws their face from memory that night.',
      philosopher: 'Wonders whether they see the same red.',
      explorer: 'Asks where they come from, and whether you could go there.',
      monk: 'Sees no stranger at all.',
      sovereign: 'Asks their name, and whether they mean to stay.',
      hedonist: 'Invites them to dinner.',
      trickster: 'Pretends to recognise them, to see what happens.',
    },
  },
]

// Seven questions for Your Constellation. Each answer gives its archetype two points.
export const QUIZ = [
  { q: 'A locked door stands in your way.', a: [['Work out how the lock works.', 'scientist'], ['Break it down.', 'warrior'], ['Ask why it was locked.', 'philosopher'], ['Find another way in.', 'explorer'], ['Knock, and ask if there is a party.', 'hedonist']] },
  { q: 'You have a free year, and money enough.', a: [['Build something that will outlast it.', 'engineer'], ['Go where no map is any good.', 'explorer'], ['Make the work only you could make.', 'artist'], ['Eat, drink, love, stay up late.', 'hedonist']] },
  { q: 'Your community is in disarray.', a: [['Draw up rules, and see them kept.', 'sovereign'], ['Make people laugh at what they fear.', 'trickster'], ['Fix the thing that is actually broken.', 'engineer'], ['Stand in front of whatever threatens it.', 'warrior']] },
  { q: 'Someone tells you, with total confidence, how the world works.', a: [['Ask for the evidence.', 'scientist'], ['Ask what they mean by “the world”.', 'philosopher'], ['Agree, then say the opposite with the same face.', 'trickster'], ['Let it pass. It doesn’t touch what matters.', 'monk']] },
  { q: 'A perfect evening is…', a: [['A long dinner, and nowhere to be.', 'hedonist'], ['Silence, and a candle.', 'monk'], ['Working late on something that is almost working.', 'engineer'], ['A conversation that goes on until three.', 'philosopher']] },
  { q: 'Faced with chaos, you…', a: [['Impose an order on it.', 'sovereign'], ['Find the pattern in it.', 'scientist'], ['Make something beautiful out of it.', 'artist'], ['Join in.', 'trickster']] },
  { q: 'What would you want said of you?', a: [['That they never gave up.', 'warrior'], ['That they saw what no one had seen.', 'explorer'], ['That they were at peace.', 'monk'], ['That they left things better ordered.', 'sovereign'], ['That they made something beautiful.', 'artist']] },
]
