// The twenty-four archetypes, in six orders of four: one record each. Everything the rooms show comes from here.
// Atlas scores run from -1 to 1 on each dimension. They are an interpretive sketch, not a measurement.

export const DIMS = [
  { id: 'act', lo: 'Inward', hi: 'Outward', note: 'receives the world, or acts on it' },
  { id: 'order', lo: 'Change', hi: 'Order', note: 'unsettles things, or holds them in place' },
  { id: 'mind', lo: 'Body', hi: 'Mind', note: 'meets reality through the body, or through thought' },
  { id: 'with', lo: 'Alone', hi: 'Together', note: 'goes alone, or works through other people' },
  { id: 'time', lo: 'Present', hi: 'Future', note: 'lives in the moment, or for what comes next' },
]

// Six orders of four. Each order is defined by what its ways attend to.
export const ORDERS = [
  { id: 'knowing', no: 'I', name: 'Knowing', object: 'the true', line: 'Ways that ask what is the case, and how anyone could know it.', ids: ['scientist', 'philosopher', 'theologian', 'detective'] },
  { id: 'making', no: 'II', name: 'Making', object: 'the made', line: 'Ways that add something to the world that was not there before.', ids: ['engineer', 'artist', 'musician', 'storyteller'] },
  { id: 'self', no: 'III', name: 'Disciplines', object: 'the self', line: 'Ways that work on the one who lives: its will, its silence, its body, its surface.', ids: ['warrior', 'monk', 'biohacker', 'looksmaxxer'] },
  { id: 'city', no: 'IV', name: 'The City', object: 'the shared order', line: 'Ways that deal with the rules people live under: to make them, refuse them, trade within them, mock them.', ids: ['sovereign', 'rebel', 'entrepreneur', 'trickster'] },
  { id: 'beholding', no: 'V', name: 'Beholding', object: 'the given world', line: 'Ways that receive the world as it is: go to it, taste it, watch it, keep it.', ids: ['explorer', 'hedonist', 'cinephile', 'archivist'] },
  { id: 'tending', no: 'VI', name: 'Tending', object: 'the other', line: 'Ways that care for another living being: its body, its mind, its heart, its growth.', ids: ['healer', 'teacher', 'lover', 'gardener'] },
]

export const ARCHETYPES = [
  {
    id: 'scientist', no: 'I', order: 'knowing', name: 'Scientist', verb: 'understand', color: '#1f4fd8', fg: '#f7f5f0',
    question: 'How does it work?',
    instrument: 'The experiment',
    gift: 'Knowledge that can be checked by anyone, and outlives the person who found it.',
    shadow: 'Mistaking the map for the territory; treating whatever cannot be measured as unreal.',
    exemplars: ['Marie Curie', 'Charles Darwin', 'Rosalind Franklin'],
    quote: ['The first principle is that you must not fool yourself, and you are the easiest person to fool.', 'Richard Feynman, Caltech commencement, 1974'],
    play: 'Click to add an observation. The line is refitted to all of them.',
    glyph: 'M12 42a30 30 0 1 0 60 0a30 30 0 1 0 -60 0M63 63L88 88',
    at: { act: -0.15, order: 0.55, mind: 0.85, with: 0.1, time: 0.3 },
  },
  {
    id: 'philosopher', no: 'II', order: 'knowing', name: 'Philosopher', verb: 'question', color: '#26285e', fg: '#f7f5f0',
    question: 'What is it, really?',
    instrument: 'The question',
    gift: 'Clarity about what we actually mean, and about what we only thought we knew.',
    shadow: 'Doubting everything and deciding nothing; cleverness instead of wisdom.',
    exemplars: ['Socrates', 'Zhuangzi', 'Simone de Beauvoir'],
    quote: ['The unexamined life is not worth living.', 'Socrates, in Plato’s Apology'],
    play: 'Click near any thought to ask another question of it.',
    glyph: 'M31 33a19 19 0 1 1 27 17c-6 4-8 8-8 15M50 80v6',
    at: { act: -0.6, order: -0.35, mind: 0.95, with: -0.35, time: 0 },
  },
  {
    id: 'theologian', no: 'III', order: 'knowing', name: 'Theologian', verb: 'revere', color: '#5c1a33', fg: '#f1d9a8',
    question: 'What is ultimate, and what does it ask of us?',
    instrument: 'Scripture and reason',
    gift: 'A language for what matters most, and a conversation about it kept going for centuries.',
    shadow: 'Certainty that permits cruelty; the map of heaven used to rule the earth.',
    exemplars: ['Augustine of Hippo', 'Al-Ghazali', 'Maimonides'],
    quote: ['Faith seeking understanding.', 'Anselm of Canterbury, Proslogion, c. 1078'],
    play: 'Rest the cursor on the window: light fills what patience reaches. Click to light a candle.',
    glyph: 'M14 50a36 36 0 1 0 72 0a36 36 0 1 0 -72 0M50 14V86M14 50H86M25 25L75 75M75 25L25 75M38 50a12 12 0 1 0 24 0a12 12 0 1 0 -24 0',
    at: { act: -0.75, order: 0.7, mind: 0.8, with: 0.5, time: 0.6 },
  },
  {
    id: 'detective', no: 'IV', order: 'knowing', name: 'Detective', verb: 'solve', color: '#20434f', fg: '#ebe4d0',
    question: 'What really happened?',
    instrument: 'The clue',
    gift: 'A hidden truth restored; justice that begins with attention.',
    shadow: 'Suspicion of everyone; a theory that bends the evidence to fit.',
    exemplars: ['Eugène François Vidocq', 'Kate Warne', 'Sherlock Holmes'],
    quote: ['When you have eliminated the impossible, whatever remains, however improbable, must be the truth.', 'Arthur Conan Doyle, The Sign of the Four, 1890'],
    play: 'Click two clues to tie them with string. Link the scene to the suspect.',
    glyph: 'M34 36a16 16 0 1 0 32 0a16 16 0 1 0 -32 0M42 50L34 88H66L58 50',
    at: { act: 0.35, order: 0.3, mind: 0.85, with: -0.4, time: -0.3 },
  },
  {
    id: 'engineer', no: 'V', order: 'making', name: 'Engineer', verb: 'build', color: '#f26a1b', fg: '#0c0c0c',
    question: 'How can we make it work?',
    instrument: 'The plan',
    gift: 'Things that work, for people who will never know your name.',
    shadow: 'Building because it can be built; the machine that outgrows its purpose.',
    exemplars: ['Imhotep', 'Filippo Brunelleschi', 'Isambard Kingdom Brunel'],
    quote: ['Give me a place to stand, and I will move the earth.', 'Attributed to Archimedes'],
    play: 'Move along the bridge to carry the load across it.',
    glyph: 'M8 80L50 18L92 80ZM29 49L50 80L71 49Z',
    at: { act: 0.65, order: 0.55, mind: 0.25, with: 0.35, time: 0.8 },
  },
  {
    id: 'artist', no: 'VI', order: 'making', name: 'Artist', verb: 'create', color: '#e0157a', fg: '#f7f5f0',
    question: 'What could it be?',
    instrument: 'The medium',
    gift: 'New forms for feelings that had none; a way of seeing that stays after you look away.',
    shadow: 'Self-absorption; beauty used as an excuse for anything.',
    exemplars: ['Katsushika Hokusai', 'Johann Sebastian Bach', 'Frida Kahlo'],
    quote: ['Art does not reproduce the visible; rather, it makes visible.', 'Paul Klee, Creative Confession, 1920'],
    play: 'Draw. Every mark is answered five more times.',
    glyph: 'M50 50a5 5 0 0 1 10 0a10 10 0 0 1-20 0a15 15 0 0 1 30 0a20 20 0 0 1-40 0a25 25 0 0 1 50 0',
    at: { act: 0.45, order: -0.5, mind: 0, with: -0.45, time: 0.1 },
  },
  {
    id: 'musician', no: 'VII', order: 'making', name: 'Musician', verb: 'tune', color: '#00a0b4', fg: '#0c0c0c',
    question: 'What does it sound like, and what comes next?',
    instrument: 'The ear',
    gift: 'Time made audible; a way of feeling together without speaking.',
    shadow: 'Perfectionism; a life practised instead of lived.',
    exemplars: ['Hildegard of Bingen', 'Ravi Shankar', 'Nina Simone'],
    quote: ['Without music, life would be a mistake.', 'Friedrich Nietzsche, Twilight of the Idols, 1889'],
    play: 'Sweep across the strings. Click once to let them sound.',
    glyph: 'M26 76a11 8 0 1 0 22 0a11 8 0 1 0-22 0M48 76V18Q64 24 74 40',
    at: { act: 0.15, order: -0.15, mind: -0.3, with: 0.6, time: -0.6 },
  },
  {
    id: 'storyteller', no: 'VIII', order: 'making', name: 'Storyteller', verb: 'tell', color: '#b5532c', fg: '#f6eadb',
    question: 'What happened, and what did it mean?',
    instrument: 'The plot',
    gift: 'Meaning that travels: experience shaped so that someone else can carry it.',
    shadow: 'The tidy story that is not true; a life bent to fit its narrative.',
    exemplars: ['Scheherazade', 'Homer', 'Chinua Achebe'],
    quote: ['We tell ourselves stories in order to live.', 'Joan Didion, The White Album, 1979'],
    play: 'Click to add a beat; the higher, the more tension. The shape names its parts.',
    glyph: 'M8 28Q30 18 50 30Q70 18 92 28V80Q70 70 50 82Q30 70 8 80ZM50 30V82',
    at: { act: 0.05, order: -0.55, mind: 0.6, with: 0.85, time: -0.1 },
  },
  {
    id: 'warrior', no: 'IX', order: 'self', name: 'Warrior', verb: 'overcome', color: '#a8161f', fg: '#f7f5f0',
    question: 'What stands in the way?',
    instrument: 'Discipline',
    gift: 'Courage: the will to hold a line, and to keep going when it costs something.',
    shadow: 'Needing an enemy to feel alive; strength that forgets what it was for.',
    exemplars: ['Achilles', 'Joan of Arc', 'Miyamoto Musashi'],
    quote: ['To subdue the enemy without fighting is the supreme excellence.', 'Sun Tzu, The Art of War (trans. Giles)'],
    play: 'Cut through the current. It closes again behind you.',
    glyph: 'M18 88L50 10L82 88M50 10V96M34 66H66',
    at: { act: 0.9, order: 0.05, mind: -0.75, with: 0.35, time: -0.4 },
  },
  {
    id: 'monk', no: 'X', order: 'self', name: 'Monk', verb: 'transcend', color: '#e3a21a', fg: '#0c0c0c',
    question: 'What remains when I let go?',
    instrument: 'Attention',
    gift: 'A peace that does not depend on circumstances.',
    shadow: 'Escape dressed as transcendence; calm that has stopped caring.',
    exemplars: ['Siddhartha Gautama', 'Milarepa', 'Thomas Merton'],
    quote: ['Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.', 'Zen saying'],
    play: 'Hold still. The circle only forms when you stop moving.',
    glyph: 'M74.4 20.9A38 38 0 1 0 87.2 42.1',
    at: { act: -0.95, order: 0.45, mind: 0.4, with: -0.75, time: -0.85 },
  },
  {
    id: 'biohacker', no: 'XI', order: 'self', name: 'Biohacker', verb: 'optimise', color: '#c9f0e4', fg: '#0c0c0c', ink: '#3e7f6c',
    question: 'What can be measured, and improved?',
    instrument: 'The protocol',
    gift: 'Taking the body seriously: attention, data, and the patience to change one thing at a time.',
    shadow: 'Optimising the numbers instead of the life; the self as a machine to be tuned forever.',
    exemplars: ['Santorio Santorio', 'Luigi Cornaro', 'Benjamin Franklin'],
    quote: ['All things are poison, and nothing is without poison; the dose alone makes a thing not a poison.', 'Paracelsus, 1538'],
    play: 'Move along the dose; click to run a trial. Too little does nothing. Too much does harm.',
    glyph: 'M4 54H28L36 28L50 80L60 42L67 54H96',
    at: { act: 0.4, order: 0.88, mind: -0.6, with: -0.5, time: 0.85 },
  },
  {
    id: 'looksmaxxer', no: 'XII', order: 'self', name: 'Looksmaxxer', verb: 'polish', color: '#f2c4ce', fg: '#0c0c0c', ink: '#b5576b',
    question: 'How do I appear?',
    instrument: 'The mirror',
    gift: 'Self-respect made visible; a discipline that shows.',
    shadow: 'A mirror that never approves; comparison without end.',
    exemplars: ['Beau Brummell', 'Oscar Wilde', 'Narcissus'],
    quote: ['One should either be a work of art, or wear a work of art.', 'Oscar Wilde, Phrases and Philosophies for the Use of the Young, 1894'],
    play: 'Drag the features. The mirror scores the symmetry, whether you asked it to or not.',
    glyph: 'M24 50a26 36 0 1 0 52 0a26 36 0 1 0-52 0M50 6V94',
    at: { act: 0.15, order: 0.4, mind: -0.85, with: 0.4, time: 0.5 },
  },
  {
    id: 'sovereign', no: 'XIII', order: 'city', name: 'Sovereign', verb: 'shape', color: '#5a2a8a', fg: '#f7f5f0',
    question: 'How should it be ordered?',
    instrument: 'The law',
    gift: 'An order inside which other people can flourish.',
    shadow: 'Tyranny; order kept for its own sake, and for the one who keeps it.',
    exemplars: ['Ashoka', 'Elizabeth I', 'Marcus Aurelius'],
    quote: ['No more talk about what a good man should be. Be one.', 'Marcus Aurelius, Meditations X.16 (translations vary)'],
    play: 'Bring your hand into the crowd and it falls into ranks around you.',
    glyph: 'M14 78V30L34 52L50 20L66 52L86 30V78Z',
    at: { act: 0.8, order: 0.95, mind: 0.3, with: 0.95, time: 0.7 },
  },
  {
    id: 'rebel', no: 'XIV', order: 'city', name: 'Rebel', verb: 'refuse', color: '#0c0c0c', fg: '#ff3b30',
    question: 'Why must it be this way?',
    instrument: 'The refusal',
    gift: 'Freedoms that did not exist until someone would not accept their absence.',
    shadow: 'Rebellion as identity; the revolution that becomes the next tyranny.',
    exemplars: ['Spartacus', 'Harriet Tubman', 'Václav Havel'],
    quote: ['What is a rebel? A man who says no.', 'Albert Camus, The Rebel, 1951'],
    play: 'The lattice keeps its order. Push against it; enough pressure in one place, and it gives.',
    glyph: 'M12 32H88M12 68H88M50 92V8M36 22L50 8L64 22',
    at: { act: 0.8, order: -0.85, mind: 0.15, with: 0.35, time: 0.75 },
  },
  {
    id: 'entrepreneur', no: 'XV', order: 'city', name: 'Entrepreneur', verb: 'seize', color: '#6cc644', fg: '#0c0c0c',
    question: 'Who would pay for this?',
    instrument: 'The bet',
    gift: 'Things that did not exist, brought into being and kept alive by people choosing them.',
    shadow: 'Growth as an end in itself; every hour and every friend a resource.',
    exemplars: ['Josiah Wedgwood', 'Madam C. J. Walker', 'Jacob Fugger'],
    quote: ['This process of Creative Destruction is the essential fact about capitalism.', 'Joseph Schumpeter, Capitalism, Socialism and Democracy, 1942'],
    play: 'Seize opportunities before they fade. Some of them are traps.',
    glyph: 'M10 84L38 56L54 68L88 30M66 30H88V52',
    at: { act: 0.85, order: -0.5, mind: 0.2, with: 0.6, time: 0.95 },
  },
  {
    id: 'trickster', no: 'XVI', order: 'city', name: 'Trickster', verb: 'disrupt', color: '#c2d82b', fg: '#0c0c0c',
    question: 'What if it’s the other way round?',
    instrument: 'The joke',
    gift: 'Renewal: the rules made visible by being broken, and the stuck thing set moving again.',
    shadow: 'Cynicism; disruption with nothing to follow it.',
    exemplars: ['Hermes', 'Anansi', 'Coyote', 'Loki'],
    quote: ['The trickster is the boundary-crosser, and a culture without one stops changing.', 'After Lewis Hyde, Trickster Makes This World, 1998 (paraphrased)'],
    play: 'Touch the order. It comes undone, then slowly forgets that it did.',
    glyph: 'M8 28L32 76L50 38L68 76L92 28',
    at: { act: 0.35, order: -1, mind: 0.25, with: 0.2, time: -0.4 },
  },
  {
    id: 'explorer', no: 'XVII', order: 'beholding', name: 'Explorer', verb: 'discover', color: '#0e7a52', fg: '#f7f5f0',
    question: 'What lies beyond?',
    instrument: 'The map',
    gift: 'A wider world: the edge of the known pushed a little further out.',
    shadow: 'Never arriving anywhere; conquest calling itself discovery.',
    exemplars: ['Ibn Battuta', 'Zheng He', 'Ernest Shackleton'],
    quote: ['We shall not cease from exploration, and the end of all our exploring will be to arrive where we started and know the place for the first time.', 'T. S. Eliot, Little Gidding, 1942'],
    play: 'Move through the fog. What you uncover stays uncovered.',
    glyph: 'M50 6L58 42L94 50L58 58L50 94L42 58L6 50L42 42Z',
    at: { act: 0.6, order: -0.8, mind: -0.3, with: -0.3, time: 0.55 },
  },
  {
    id: 'hedonist', no: 'XVIII', order: 'beholding', name: 'Hedonist', verb: 'experience', color: '#f47c6c', fg: '#0c0c0c',
    question: 'What does it feel like?',
    instrument: 'The senses',
    gift: 'Presence: the world savoured rather than used.',
    shadow: 'The treadmill of more; pleasure that has become a need.',
    exemplars: ['Epicurus', 'Omar Khayyam', 'Dionysus'],
    quote: ['By pleasure we mean the absence of pain in the body and of trouble in the soul.', 'Epicurus, Letter to Menoeceus (paraphrased); gentler than his reputation'],
    play: 'Move slowly. Every touch blooms, and fades.',
    glyph: 'M41 50a9 9 0 1 0 18 0a9 9 0 1 0 -18 0M37 22a13 13 0 1 0 26 0a13 13 0 1 0 -26 0M37 78a13 13 0 1 0 26 0a13 13 0 1 0 -26 0M9 50a13 13 0 1 0 26 0a13 13 0 1 0 -26 0M65 50a13 13 0 1 0 26 0a13 13 0 1 0 -26 0',
    at: { act: -0.35, order: -0.2, mind: -0.95, with: 0.35, time: -1 },
  },
  {
    id: 'cinephile', no: 'XIX', order: 'beholding', name: 'Cinephile', verb: 'frame', color: '#232323', fg: '#efe6d2',
    question: 'What does the frame leave out?',
    instrument: 'The frame',
    gift: 'A trained eye: knowing that every image is a choice, and seeing the choice.',
    shadow: 'Life lived as a spectator; the screen preferred to the street.',
    exemplars: ['André Bazin', 'Pauline Kael', 'François Truffaut'],
    quote: ['Photography is truth. The cinema is truth twenty-four times per second.', 'Jean-Luc Godard, Le Petit Soldat, 1960'],
    play: 'Move the frame. Click to cut a shot into the strip.',
    glyph: 'M12 24H88V76H12ZM12 34H88M12 66H88M24 24V34M40 24V34M56 24V34M72 24V34M24 66V76M40 66V76M56 66V76M72 66V76M44 42L60 50L44 58Z',
    at: { act: -0.5, order: 0.1, mind: 0.5, with: 0, time: -0.2 },
  },
  {
    id: 'archivist', no: 'XX', order: 'beholding', name: 'Archivist', verb: 'remember', color: '#d9c7a3', fg: '#0c0c0c', ink: '#8a7448',
    question: 'What must not be lost?',
    instrument: 'The catalogue',
    gift: 'Memory that outlives the people who had it; a past that can still be questioned.',
    shadow: 'Hoarding: keeping everything, and so finding nothing.',
    exemplars: ['Ban Zhao', 'The librarians of Alexandria', 'Paul Otlet'],
    quote: ['Who controls the past controls the future: who controls the present controls the past.', 'George Orwell, Nineteen Eighty-Four, 1949'],
    play: 'Hover over a fading memory to keep it. Whatever you do not keep is lost.',
    glyph: 'M14 14H86V86H14ZM14 38H86M14 62H86M42 25H58M42 49H58M42 73H58',
    at: { act: -0.3, order: 0.95, mind: 0.6, with: -0.3, time: -0.9 },
  },
  {
    id: 'healer', no: 'XXI', order: 'tending', name: 'Healer', verb: 'heal', color: '#8fb8de', fg: '#0c0c0c', ink: '#2e6a9e',
    question: 'Where does it hurt, and why?',
    instrument: 'Diagnosis and care',
    gift: 'Suffering reduced; the long human work of keeping one another alive.',
    shadow: 'Treating the disease and not the person; the healer who needs others to be ill.',
    exemplars: ['Hippocrates', 'Ibn Sina', 'Florence Nightingale'],
    quote: ['Cure sometimes, treat often, comfort always.', 'A physicians’ maxim, of uncertain origin'],
    play: 'Hold the cursor still on the body to listen for what hurts. Click to treat it.',
    glyph: 'M38 14H62V38H86V62H62V86H38V62H14V38H38Z',
    at: { act: 0.35, order: 0.35, mind: -0.6, with: 0.9, time: 0.05 },
  },
  {
    id: 'teacher', no: 'XXII', order: 'tending', name: 'Teacher', verb: 'teach', color: '#7a4b2a', fg: '#f3e9d2',
    question: 'How will they come to understand it?',
    instrument: 'The lesson',
    gift: 'Knowledge that outlives its holder by passing into someone else.',
    shadow: 'Teaching obedience instead of thought; the student kept dependent.',
    exemplars: ['Confucius', 'Maria Montessori', 'Anne Sullivan'],
    quote: ['The mind is not a vessel that needs filling, but wood that needs igniting.', 'Plutarch, On Listening to Lectures, c. 100'],
    play: 'Each dot is a student. Click to explain, and watch understanding spread from neighbour to neighbour.',
    glyph: 'M50 12C62 26 62 36 50 46C38 36 38 26 50 12ZM40 52H60L56 88H44Z',
    at: { act: 0.2, order: 0.6, mind: 0.45, with: 0.75, time: 0.6 },
  },
  {
    id: 'lover', no: 'XXIII', order: 'tending', name: 'Lover', verb: 'love', color: '#9b1d64', fg: '#fde4ee',
    question: 'Who are you, really?',
    instrument: 'Attention to one other',
    gift: 'Being known; a self widened by another.',
    shadow: 'Possession mistaken for love; losing oneself in another.',
    exemplars: ['Sappho', 'Rumi', 'Héloïse d’Argenteuil'],
    quote: ['Love is the extremely difficult realisation that something other than oneself is real.', 'Iris Murdoch, “The Sublime and the Good”, 1959'],
    play: 'Two points, drawn to each other. Move one and the other answers, never quite in step. Click to change who leads.',
    glyph: 'M12 50a24 24 0 1 0 48 0a24 24 0 1 0 -48 0M40 50a24 24 0 1 0 48 0a24 24 0 1 0 -48 0',
    at: { act: -0.15, order: -0.35, mind: -0.15, with: 0.95, time: -0.45 },
  },
  {
    id: 'gardener', no: 'XXIV', order: 'tending', name: 'Gardener', verb: 'tend', color: '#55772b', fg: '#f2ead3',
    question: 'What does it need to grow?',
    instrument: 'The season',
    gift: 'Patience with living things; a world left more alive than it was found.',
    shadow: 'Control dressed up as care; everything not planted, pulled up.',
    exemplars: ['Gertrude Jekyll', 'Masanobu Fukuoka', 'Gregor Mendel'],
    quote: ['We must cultivate our garden.', 'Voltaire, Candide, 1759'],
    play: 'Click the soil to plant; hover to water. Untended, they wilt.',
    glyph: 'M50 92V42M50 62Q30 58 20 36Q44 34 50 58M50 50Q66 44 78 22Q56 20 50 46M24 92H76',
    at: { act: -0.1, order: 0.25, mind: -0.5, with: -0.2, time: 0.25 },
  },
]

export const byId = Object.fromEntries(ARCHETYPES.map((a) => [a.id, a]))

// The archetype's colour as ink on paper: the palest carry a deeper ink so they can still be read.
export const ink = (a) => a.ink || a.color

// The archetype's colour as a mark on the dark rooms: near-black colours show their foreground instead.
export const mark = (a) => {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(a.color.slice(i, i + 2), 16))
  return r + g + b < 120 ? a.fg : a.color
}

// Kinships. Allies work together; opposites pull in contrary directions; unions are the rare people who were both.
export const LINKS = {
  allies: [
    ['scientist', 'engineer', 'One finds out how it works, the other makes it work.'],
    ['scientist', 'explorer', 'The expedition and the observation have always travelled together.'],
    ['philosopher', 'scientist', 'Science began as natural philosophy.'],
    ['engineer', 'sovereign', 'Roads, aqueducts and walls: the works of rule.'],
    ['warrior', 'sovereign', 'The sword and the crown.'],
    ['artist', 'hedonist', 'Both trust the senses.'],
    ['artist', 'trickster', 'Both break forms to make new ones.'],
    ['philosopher', 'monk', 'Both turn away from appearances to ask what lies beneath.'],
    ['explorer', 'warrior', 'Both go toward what others avoid.'],
    ['cinephile', 'storyteller', 'Both know that meaning lives in the cut.'],
    ['musician', 'artist', 'Both make forms out of time and feeling.'],
    ['entrepreneur', 'engineer', 'One builds the thing; the other finds who needs it.'],
    ['biohacker', 'scientist', 'The experiment, run on oneself.'],
    ['theologian', 'philosopher', 'Faith seeking understanding, and understanding questioning faith.'],
    ['gardener', 'monk', 'Both work at the speed of living things.'],
    ['detective', 'scientist', 'Both follow the evidence to a conclusion.'],
    ['archivist', 'storyteller', 'One keeps what happened; the other makes it mean something.'],
    ['looksmaxxer', 'hedonist', 'Both take the body as it is seen and felt.'],
    ['healer', 'gardener', 'Both tend living things that recover in their own time.'],
    ['teacher', 'philosopher', 'Socrates taught by asking; every good teacher is partly a philosopher.'],
    ['lover', 'artist', 'Love has always needed poems, and poems have always needed love.'],
    ['rebel', 'artist', 'The avant-garde: art as refusal.'],
    ['teacher', 'storyteller', 'The oldest lessons were stories.'],
  ],
  opposites: [
    ['monk', 'hedonist', 'Let go of the world, or taste all of it.'],
    ['sovereign', 'trickster', 'Make the order, or make fun of it.'],
    ['engineer', 'philosopher', 'Build it, or ask whether it should be built.'],
    ['scientist', 'artist', 'Find out what is, or make what is not. C. P. Snow’s “two cultures”, 1959.'],
    ['explorer', 'sovereign', 'The frontier and the capital.'],
    ['biohacker', 'hedonist', 'Optimise the body, or enjoy it.'],
    ['gardener', 'entrepreneur', 'Wait for the season, or move before the market does.'],
    ['looksmaxxer', 'monk', 'Perfect the surface, or let it go.'],
    ['detective', 'trickster', 'Solve the riddle, or set one.'],
    ['archivist', 'explorer', 'Keep what is known, or leave it behind.'],
    ['rebel', 'sovereign', 'Make the order, or refuse it.'],
    ['healer', 'warrior', 'Close the wound, or open it.'],
    ['lover', 'monk', 'Bind yourself to one, or loosen every tie.'],
  ],
  unions: [
    ['warrior', 'monk', 'The warrior-monk: Shaolin, and the samurai who sat zazen.'],
    ['philosopher', 'sovereign', 'Plato’s philosopher-king, and Marcus Aurelius, who nearly was one.'],
    ['scientist', 'artist', 'Leonardo, who drew to understand.'],
    ['engineer', 'trickster', 'The hacker: building by breaking.'],
    ['explorer', 'monk', 'The pilgrim, who travels in order to arrive inward.'],
    ['theologian', 'scientist', 'Georges Lemaître, a Catholic priest who proposed the expanding universe in 1927.'],
    ['gardener', 'scientist', 'Gregor Mendel, friar and gardener, who found the laws of inheritance in his pea plants.'],
    ['musician', 'scientist', 'Pythagoras, who by tradition heard number in the intervals of a string.'],
    ['storyteller', 'warrior', 'The epic: a war remembered because someone sang it.'],
    ['cinephile', 'entrepreneur', 'The studio founders, who turned watching into an industry.'],
    ['healer', 'philosopher', 'Ibn Sina, who wrote the Canon of Medicine and a philosophical encyclopedia called The Book of Healing.'],
    ['lover', 'theologian', 'The mystics, Rumi, Teresa of Ávila and Hafez among them, who spoke of God in the language of love.'],
    ['rebel', 'teacher', 'Paulo Freire, for whom teaching the poor to read was an act of liberation.'],
  ],
}

// One World, Twenty-Four Encounters: three things, and how each of the twenty-four meets them.
// Each thing is a silhouette in a 600 × 400 box, with a high point and a centre for the drawings to use.
export const THINGS = [
  {
    id: 'mountain', name: 'A mountain',
    path: 'M0 400L120 250L190 300L300 90L380 220L430 180L600 400Z', peak: [300, 90], centre: [300, 290],
    lines: {
      scientist: 'Measures its height, dates its rock, and asks how it rose.',
      engineer: 'Sees where the tunnel should go.',
      warrior: 'Climbs it. A mountain is an opponent that never tires.',
      artist: 'Paints it again and again, as Hokusai made Thirty-six Views of Mount Fuji.',
      philosopher: 'Asks whether it is the same mountain from both sides.',
      explorer: 'Wants to know what is on the other side.',
      monk: 'Sits at its foot until it is no longer separate.',
      sovereign: 'Draws the border along its ridge.',
      hedonist: 'Takes the cable car up, for the view and the lunch.',
      trickster: 'Moves the summit marker ten metres, to see who notices.',
      cinephile: 'Waits two hours for the light, and shoots it in widescreen.',
      musician: 'Hears the wind in the pass as a fifth.',
      entrepreneur: 'Sells tickets to the summit.',
      biohacker: 'Trains at altitude for the red blood cells.',
      looksmaxxer: 'Takes the summit photo from its best angle.',
      theologian: 'Remembers that the law was given on one.',
      gardener: 'Plants terraces on its slopes.',
      storyteller: 'Gives it a giant who sleeps inside.',
      detective: 'Asks who was last seen on the ridge.',
      archivist: 'Keeps every survey since the first.',
      healer: 'Gathers the herbs that grow above the tree line.',
      teacher: 'Takes the class up it, and asks why the rock is folded.',
      lover: 'Climbs it to watch someone else see the view.',
      rebel: 'Hides in it, as rebels always have.',
    },
  },
  {
    id: 'sea', name: 'The sea',
    path: 'M0 210Q75 180 150 210T300 210T450 210T600 210L600 400L0 400Z', peak: [450, 210], centre: [300, 300],
    lines: {
      scientist: 'Samples its salt and charts its currents.',
      engineer: 'Builds the harbour, the ship and the lighthouse.',
      warrior: 'Rows against the storm.',
      artist: 'Spends a lifetime on the colour of one wave.',
      philosopher: 'Asks, after Heraclitus, whether anyone steps into the same water twice.',
      explorer: 'Sails toward the edge of the chart.',
      monk: 'Listens to it until there is only listening.',
      sovereign: 'Claims twelve nautical miles of it.',
      hedonist: 'Swims in it at midnight.',
      trickster: 'Sends out a message in a bottle that says: do not open this.',
      cinephile: 'Frames the horizon exactly a third of the way up.',
      musician: 'Counts the waves in threes.',
      entrepreneur: 'Opens a shipping line.',
      biohacker: 'Swims in it at four degrees, for the cold exposure.',
      looksmaxxer: 'Checks the light on the water against the light on the face.',
      theologian: 'Reads in it the flood, and the parting.',
      gardener: 'Gathers seaweed for the beds.',
      storyteller: 'Says something is waiting on the other side.',
      detective: 'Reads the tide tables to break an alibi.',
      archivist: 'Catalogues every shipwreck by date.',
      healer: 'Remembers that salt water cleans a wound.',
      teacher: 'Explains the tides with an orange and a torch.',
      lover: 'Writes a name in the sand and lets the tide take it.',
      rebel: 'Crosses it at night, without papers.',
    },
  },
  {
    id: 'stranger', name: 'A stranger',
    path: 'M245 150a55 55 0 1 0 110 0a55 55 0 1 0-110 0ZM160 400C160 290 225 245 300 245C375 245 440 290 440 400Z', peak: [300, 95], centre: [300, 300],
    lines: {
      scientist: 'Wonders what made them who they are.',
      engineer: 'Asks what they need, and how it could be made.',
      warrior: 'Decides quickly: friend, or threat.',
      artist: 'Draws their face from memory that night.',
      philosopher: 'Wonders whether they see the same red.',
      explorer: 'Asks where they come from, and whether you could go there.',
      monk: 'Sees no stranger at all.',
      sovereign: 'Asks their name, and whether they mean to stay.',
      hedonist: 'Invites them to dinner.',
      trickster: 'Pretends to recognise them, to see what happens.',
      cinephile: 'Wonders what film they think they are in.',
      musician: 'Notices the rhythm of how they walk.',
      entrepreneur: 'Wonders whether they are a customer or a co-founder.',
      biohacker: 'Notices their posture, and how they slept.',
      looksmaxxer: 'Notices their jaw, and then their own.',
      theologian: 'Remembers the command to welcome the stranger.',
      gardener: 'Gives them cuttings to take home.',
      storyteller: 'Asks where they are from, and listens for the story.',
      detective: 'Notices the pale band where a watch used to be.',
      archivist: 'Writes down their name, so it will be kept.',
      healer: 'Asks first whether they are hurt.',
      teacher: 'Wonders what they know that no one has asked them.',
      lover: 'Wonders, for a second, whether this is the one.',
      rebel: 'Asks whose side they are on.',
    },
  },
]

// Eight questions for Your Constellation. Each answer gives its archetype two points.
export const QUIZ = [
  { q: 'A locked door stands in your way.', a: [['Work out how the lock works.', 'scientist'], ['Break it down.', 'warrior'], ['Ask why it was locked.', 'philosopher'], ['Find another way in.', 'explorer'], ['Knock, and ask if there is a party.', 'hedonist'], ['Look for clues about who locked it.', 'detective'], ['Refuse to accept that it stays locked.', 'rebel']] },
  { q: 'You have a free year, and money enough.', a: [['Build something that will outlast it.', 'engineer'], ['Go where no map is any good.', 'explorer'], ['Make the work only you could make.', 'artist'], ['Eat, drink, love, stay up late.', 'hedonist'], ['Start a company.', 'entrepreneur'], ['Make a film.', 'cinephile'], ['Volunteer where people need care.', 'healer']] },
  { q: 'Your community is in disarray.', a: [['Draw up rules, and see them kept.', 'sovereign'], ['Make people laugh at what they fear.', 'trickster'], ['Fix the thing that is actually broken.', 'engineer'], ['Stand in front of whatever threatens it.', 'warrior'], ['Tell a story that makes sense of it.', 'storyteller'], ['Plant a garden together.', 'gardener'], ['Look after the ones who are hurt.', 'healer'], ['Organise people to change what caused it.', 'rebel']] },
  { q: 'Someone tells you, with total confidence, how the world works.', a: [['Ask for the evidence.', 'scientist'], ['Ask what they mean by “the world”.', 'philosopher'], ['Agree, then say the opposite with the same face.', 'trickster'], ['Let it pass. It doesn’t touch what matters.', 'monk'], ['Ask what they believe, and why.', 'theologian'], ['Ask how the story ends.', 'storyteller'], ['Ask how they would explain it to a child.', 'teacher']] },
  { q: 'A perfect evening is…', a: [['A long dinner, and nowhere to be.', 'hedonist'], ['Silence, and a candle.', 'monk'], ['Working late on something that is almost working.', 'engineer'], ['A conversation that goes on until three.', 'philosopher'], ['A film in a dark room.', 'cinephile'], ['Playing music with friends.', 'musician'], ['One person, and a conversation that does not end.', 'lover']] },
  { q: 'Faced with chaos, you…', a: [['Impose an order on it.', 'sovereign'], ['Find the pattern in it.', 'scientist'], ['Make something beautiful out of it.', 'artist'], ['Join in.', 'trickster'], ['Write it all down and file it.', 'archivist'], ['Find the variable, and fix it.', 'biohacker'], ['Explain it to someone until it makes sense.', 'teacher']] },
  { q: 'What would you want said of you?', a: [['That they never gave up.', 'warrior'], ['That they saw what no one had seen.', 'explorer'], ['That they were at peace.', 'monk'], ['That they left things better ordered.', 'sovereign'], ['That they made something beautiful.', 'artist'], ['That they looked the part, and earned it.', 'looksmaxxer'], ['That they found out the truth.', 'detective'], ['That they loved well.', 'lover']] },
  { q: 'Your morning…', a: [['A cold shower, supplements, a sleep score.', 'biohacker'], ['Skincare, posture, a good mirror.', 'looksmaxxer'], ['Prayer, before anything else.', 'theologian'], ['Watering the plants.', 'gardener'], ['Scales, slowly, then faster.', 'musician'], ['Inbox zero and a pitch deck.', 'entrepreneur'], ['An old letter, reread.', 'archivist']] },
]
