// The dossier behind each plate: a short essay, its figure in myth, a lineage of dated moments,
// what it does, the words it uses, the signs of it in a person, and where to begin reading.
// Lineage entries are [year, as written, what happened]; negative years are BC. Dates marked c. are approximate.
export const DOSSIERS = {
  scientist: {
    figure: 'Prometheus, who stole fire from the gods: the light of knowing, and its price.',
    essay: 'The scientist trusts nothing that cannot be checked, least of all their own conviction. The method is humble and ruthless at once: guess, test, discard, and keep only what survives. What remains is never certainty, only the best explanation so far, held open to the next observation. Its great discovery is that the world is lawful, and that its laws are rarely what anyone expected.',
    lineage: [
      [-585, 'c. 585 BC', 'Thales of Miletus is said to predict a solar eclipse.'],
      [1543, '1543', 'Copernicus publishes On the Revolutions of the Heavenly Spheres.'],
      [1687, '1687', 'Newton’s Principia sets out the laws of motion and gravitation.'],
      [1859, '1859', 'Darwin publishes On the Origin of Species.'],
      [1905, '1905', 'Einstein’s miracle year: relativity, light quanta, Brownian motion.'],
    ],
    practice: ['Keeps a notebook, dated.', 'Repeats the experiment.', 'Publishes the method with the result.', 'Looks for the error in their own work first.'],
    lexicon: [['Hypothesis', 'A guess that could be shown wrong.'], ['Falsifiable', 'Popper’s test (1934): a claim that some observation could refute.'], ['Control', 'The case in which nothing was changed.'], ['Peer review', 'Judgement by those able to check the work.']],
    signs: ['You ask “how do you know?” more often than “what do you think?”', 'You enjoy being proved wrong, eventually.', 'Something in your personal life has a spreadsheet.'],
    works: [['The Structure of Scientific Revolutions', 'Thomas Kuhn, 1962'], ['The Logic of Scientific Discovery', 'Karl Popper, 1934'], ['Surely You’re Joking, Mr. Feynman!', 'Richard Feynman, 1985']],
  },
  engineer: {
    figure: 'Daedalus, who built the labyrinth, and the wings his son flew too high on.',
    essay: 'The engineer does not ask whether something is true, but whether it will hold. Every bridge is an argument with gravity that has to be won every day for a century. Engineering is the art of the good enough: margins of safety, tolerances, trade-offs, the honest arithmetic of what can fail. Its peculiar beauty is that, when it works, it disappears.',
    lineage: [
      [-2650, 'c. 2650 BC', 'Imhotep designs the step pyramid of Djoser at Saqqara.'],
      [1436, '1436', 'Brunelleschi’s dome over Florence cathedral is completed, without centring.'],
      [1769, '1769', 'James Watt patents the separate condenser for the steam engine.'],
      [1883, '1883', 'The Brooklyn Bridge opens, the longest suspension span of its day.'],
      [1969, '1969', 'Apollo 11 lands on the Moon and returns.'],
    ],
    practice: ['Calculates the load before drawing the beam.', 'Builds a prototype in order to break it.', 'Adds a factor of safety.', 'Writes down why each decision was made.'],
    lexicon: [['Tolerance', 'How far a part may differ from its drawing.'], ['Factor of safety', 'Strength held in reserve beyond the expected load.'], ['Failure mode', 'The particular way a thing breaks.'], ['Iteration', 'Build, test, change; again.']],
    signs: ['You take things apart before reading the instructions.', 'You answer “it depends on the requirements”.', 'Broken things in your home get fixed, and sometimes improved.'],
    works: [['To Engineer Is Human', 'Henry Petroski, 1985'], ['The Design of Everyday Things', 'Don Norman, 1988'], ['The Soul of a New Machine', 'Tracy Kidder, 1981']],
  },
  warrior: {
    figure: 'Achilles before Troy, and Arjuna on the field of Kurukshetra, who hesitated.',
    essay: 'The warrior meets reality as resistance. What matters is not the obstacle but the response: to stand, to train, to endure what cannot be avoided. Every warrior tradition is finally a tradition of self-command, because the first opponent is fear. At its best the warrior protects those who cannot; at its worst it needs an enemy in order to exist.',
    lineage: [
      [-480, '480 BC', 'Three hundred Spartans hold the pass at Thermopylae.'],
      [-450, 'c. 5th century BC', 'The Art of War, attributed to Sun Tzu, is compiled.'],
      [1645, 'c. 1645', 'Miyamoto Musashi writes The Book of Five Rings in a cave.'],
      [1832, '1832', 'Clausewitz’s On War is published, after his death.'],
    ],
    practice: ['Trains when there is nothing to train for.', 'Keeps the body ready and the word kept.', 'Studies the opponent.', 'Rests on purpose.'],
    lexicon: [['Discipline', 'Doing it when you do not want to.'], ['Courage', 'Acting in the presence of fear, not in its absence.'], ['Honour', 'A code that binds even when no one is watching.'], ['Strategy', 'The plan of the whole; tactics are the moves.']],
    signs: ['You choose the harder way to prove that you can.', 'You like a clear opponent.', 'People call you when something has to be faced.'],
    works: [['The Book of Five Rings', 'Miyamoto Musashi, c. 1645'], ['The Iliad', 'Homer, c. 750 BC'], ['All Quiet on the Western Front', 'Erich Maria Remarque, 1929']],
  },
  artist: {
    figure: 'Pygmalion, whose statue was made so well that it came alive.',
    essay: 'The artist does not describe reality; they add to it. A painting, a poem or a dance is a new thing in the world that makes the old things look different. The artist’s discipline is attention, and their risk is exposure: to make something is to show what you see, and to be seen seeing it.',
    lineage: [
      [-34000, 'c. 34,000 BC', 'Horses, lions and rhinoceroses are painted in the Chauvet cave.'],
      [1503, '1503', 'Leonardo begins the portrait now called the Mona Lisa.'],
      [1872, '1872', 'Monet paints Impression, Sunrise, and gives a movement its name.'],
      [1917, '1917', 'Duchamp submits a urinal, signed R. Mutt, as Fountain.'],
    ],
    practice: ['Works every day, inspired or not.', 'Keeps a sketchbook.', 'Copies the masters, and then stops.', 'Finishes things.'],
    lexicon: [['Composition', 'Where everything is, and why.'], ['Medium', 'What the work is made of.'], ['Gesture', 'A mark that keeps the movement of the hand.'], ['Negative space', 'The shape of what was left empty.']],
    signs: ['You notice the colour before the name.', 'You cannot walk past a beautiful thing.', 'Your notebooks hold more drawings than words.'],
    works: [['Ways of Seeing', 'John Berger, 1972'], ['Letters to a Young Poet', 'Rainer Maria Rilke, 1929'], ['The Story of Art', 'E. H. Gombrich, 1950']],
  },
  philosopher: {
    figure: 'Socrates, the gadfly of Athens, who said the unexamined life is not worth living.',
    essay: 'The philosopher stops at the words everyone else uses without thinking: justice, time, self, true. To question is not to doubt for its own sake but to refuse the comfort of the unexamined. Philosophy rarely ends a question; it changes it into a better one, and that change has given birth to the sciences, one after another.',
    lineage: [
      [-399, '399 BC', 'Socrates is tried and sentenced to death in Athens.'],
      [-375, 'c. 375 BC', 'Plato writes the Republic, with its cave.'],
      [1641, '1641', 'Descartes’ Meditations: I think, therefore I am.'],
      [1781, '1781', 'Kant’s Critique of Pure Reason asks what we can know at all.'],
      [1953, '1953', 'Wittgenstein’s Philosophical Investigations is published.'],
    ],
    practice: ['Defines the terms before arguing.', 'Looks for the counterexample.', 'States the opposing view better than its holder can.', 'Argues with the dead, in writing.'],
    lexicon: [['Premise', 'What the argument starts from.'], ['Ontology', 'The study of what exists.'], ['Epistemology', 'The study of how we know.'], ['Aporia', 'The puzzlement where an argument runs out.']],
    signs: ['You answer a question with a question.', 'You have argued, seriously, about what counts as a sandwich.', 'You often say: it depends what you mean by…'],
    works: [['Apology', 'Plato, c. 399 BC'], ['Meditations on First Philosophy', 'René Descartes, 1641'], ['The Problems of Philosophy', 'Bertrand Russell, 1912']],
  },
  explorer: {
    figure: 'Odysseus, ten years finding the way home, and Gilgamesh at the edge of the world.',
    essay: 'For the explorer, the edge of the map is an invitation. They meet reality by going to it, on foot, by sail, by rope or by rocket. Their knowledge is first-hand and dearly bought, and every expedition comes back less sure about home. The shadow is the claim: the explorer arrives, and someone already lives there.',
    lineage: [
      [-800, 'c. 800 BC', 'Lapita voyagers settle Tonga and Samoa across open Pacific water.'],
      [1325, '1325', 'Ibn Battuta leaves Tangier; he will travel for nearly thirty years.'],
      [1522, '1522', 'The survivors of Magellan’s fleet, under Elcano, complete the first circumnavigation.'],
      [1911, '1911', 'Roald Amundsen’s party reaches the South Pole.'],
      [1953, '1953', 'Tenzing Norgay and Edmund Hillary stand on the summit of Everest.'],
    ],
    practice: ['Packs light and plans heavily.', 'Keeps a log.', 'Learns the local names for things.', 'Turns back when the weather says so.'],
    lexicon: [['Dead reckoning', 'Finding your place from speed, heading and time.'], ['Terra incognita', 'Land not yet on the map.'], ['Base camp', 'The last fixed point.'], ['Bearing', 'The direction to go, in degrees.']],
    signs: ['You take the unmarked path.', 'The second visit bores you.', 'You keep a list of places, and it keeps growing.'],
    works: [['The Rihla (Travels)', 'Ibn Battuta, 1355'], ['South', 'Ernest Shackleton, 1919'], ['The Worst Journey in the World', 'Apsley Cherry-Garrard, 1922']],
  },
  monk: {
    figure: 'The hermit in the desert, and the Buddha beneath the Bodhi tree.',
    essay: 'The monk meets reality by subtraction: fewer possessions, fewer words, fewer wants, until what remains is attention itself. Buddhist, Christian, Hindu and Daoist monasteries all run the same experiment: what happens to a mind that stops grasping? The answer, reported for two and a half thousand years, is a kind of freedom.',
    lineage: [
      [-450, '5th century BC', 'Siddhartha Gautama sits beneath a fig tree at Bodh Gaya and awakens.'],
      [270, 'c. 270', 'Anthony withdraws into the Egyptian desert; others follow him there.'],
      [530, 'c. 530', 'Benedict writes his Rule for monks at Monte Cassino.'],
      [1227, '1227', 'Dōgen returns from China and brings Sōtō Zen to Japan.'],
    ],
    practice: ['Rises before the light.', 'Sits.', 'Works with the hands.', 'Keeps silence at fixed hours.'],
    lexicon: [['Zazen', 'Just sitting.'], ['Ora et labora', 'Pray and work: the Benedictine rule.'], ['Detachment', 'Holding without clutching.'], ['Kōan', 'A question that thinking cannot solve.']],
    signs: ['You like empty rooms.', 'You leave your phone in another room on purpose.', 'Quiet feels like rest, not absence.'],
    works: [['The Rule of Saint Benedict', 'c. 530'], ['Zen Mind, Beginner’s Mind', 'Shunryu Suzuki, 1970'], ['The Seven Storey Mountain', 'Thomas Merton, 1948']],
  },
  sovereign: {
    figure: 'Solomon, who asked for wisdom instead of wealth, and was given both.',
    essay: 'The sovereign meets reality as something to be ordered. Not every order is tyranny: laws, calendars, roads and currencies let strangers trust one another. The sovereign’s burden is decision: someone has to choose, and live with what choosing costs. The shadow is the crown that forgets it was only lent.',
    lineage: [
      [-1754, 'c. 1754 BC', 'Hammurabi of Babylon has his laws carved in stone for all to read.'],
      [1215, '1215', 'King John seals Magna Carta at Runnymede.'],
      [1648, '1648', 'The Peace of Westphalia makes sovereignty the rule between states.'],
      [1948, '1948', 'The Universal Declaration of Human Rights is adopted.'],
    ],
    practice: ['Listens before deciding.', 'Delegates, and checks.', 'Keeps records.', 'Plans for a successor.'],
    lexicon: [['Legitimacy', 'Power that others accept as rightful.'], ['Sovereignty', 'Final authority within a territory.'], ['Mandate', 'Permission to rule, from heaven or from the voters.'], ['Precedent', 'A decision that binds later ones.']],
    signs: ['You end up organising the trip.', 'You notice who is in charge in any room.', 'You think in rules that would work for everyone.'],
    works: [['The Prince', 'Niccolò Machiavelli, 1532'], ['Meditations', 'Marcus Aurelius, c. 175'], ['Leviathan', 'Thomas Hobbes, 1651']],
  },
  hedonist: {
    figure: 'Dionysus, god of wine, theatre and the night that will not end.',
    essay: 'The hedonist takes pleasure seriously, which is rarer than it sounds. Epicurus, the most famous of them, recommended bread, water, friends and freedom from fear; the feast was never the point. To experience reality fully is to taste it slowly, with every sense. The shadow is the treadmill: more, sooner, and less each time.',
    lineage: [
      [-306, 'c. 306 BC', 'Epicurus opens his school in a garden outside Athens.'],
      [-55, 'c. 55 BC', 'Lucretius writes On the Nature of Things, Epicureanism in verse.'],
      [1789, '1789', 'Bentham proposes to measure right action in pleasure and pain.'],
      [1825, '1825', 'Brillat-Savarin publishes The Physiology of Taste.'],
    ],
    practice: ['Eats slowly.', 'Keeps afternoons free.', 'Accepts the invitation.', 'Notices when pleasure stops being pleasure.'],
    lexicon: [['Ataraxia', 'Epicurus’ calm: freedom from disturbance.'], ['Savour', 'To make a pleasure last by attending to it.'], ['Hedonic treadmill', 'The return to baseline after every gain.'], ['Carpe diem', 'Seize the day: Horace, Odes 1.11.']],
    signs: ['You remember trips by their meals.', 'You own good sheets.', 'A long lunch seems to you like time well spent.'],
    works: [['Letter to Menoeceus', 'Epicurus, c. 300 BC'], ['The Physiology of Taste', 'Jean Anthelme Brillat-Savarin, 1825'], ['A Moveable Feast', 'Ernest Hemingway, 1964']],
  },
  trickster: {
    figure: 'Loki, Coyote, Anansi and Eshu: the one in every mythology who will not keep the rules.',
    essay: 'The trickster is how a culture laughs at its own rules. In every mythology someone lies, steals and breaks a taboo, and in doing so opens a door nobody knew was there. Fire, language and the arts are often said to have been stolen by a trickster. The trickster’s gift is the reminder that every order was made, and could be made otherwise.',
    lineage: [
      [-550, 'c. 6th century BC', 'The Homeric Hymn to Hermes: the god, one day old, steals Apollo’s cattle.'],
      [1510, 'c. 1510', 'The pranks of Till Eulenspiegel are printed in Strasbourg.'],
      [1601, 'c. 1601', 'Shakespeare gives the wisest lines in Twelfth Night to Feste, the fool.'],
      [1956, '1956', 'Paul Radin’s The Trickster, with commentary by Jung, is published.'],
    ],
    practice: ['Breaks the rule nobody remembers making.', 'Plays the fool in order to say the true thing.', 'Crosses borders.', 'Never stays long.'],
    lexicon: [['Liminal', 'On the threshold, between one state and the next.'], ['Carnival', 'The permitted upturning of order.'], ['Satire', 'Attack by ridicule.'], ['Hack', 'An ingenious misuse.']],
    signs: ['You look for loopholes for fun.', 'Solemn meetings make you want to laugh.', 'You ask the questions people hoped no one would.'],
    works: [['Trickster Makes This World', 'Lewis Hyde, 1998'], ['The Trickster', 'Paul Radin, 1956'], ['Pantagruel', 'François Rabelais, 1532']],
  },
  cinephile: {
    figure: 'The prisoners in Plato’s cave, who watch shadows on a wall, here by choice.',
    essay: 'The cinephile meets reality through the frame. To watch a film properly is to see what was chosen: where the camera stood, how long the shot lasts, what was cut away. Cinema is time made visible, and the cinephile is its most attentive witness. Its gift is a trained eye; its risk is preferring the screen to the street.',
    lineage: [
      [1895, '1895', 'The Lumière brothers show ten short films to a paying audience in Paris.'],
      [1925, '1925', 'Eisenstein’s Battleship Potemkin turns editing into argument.'],
      [1951, '1951', 'André Bazin and others found Cahiers du cinéma.'],
      [1959, '1959', 'Truffaut’s The 400 Blows opens the French New Wave.'],
    ],
    practice: ['Watches a film twice: once for the story, once for the cuts.', 'Sits in the front third.', 'Keeps a diary of everything seen.', 'Stays for the credits.'],
    lexicon: [['Mise-en-scène', 'Everything placed before the camera.'], ['Montage', 'Meaning made by joining shots.'], ['Long take', 'A shot that refuses to cut.'], ['Auteur', 'The director as the author of the film.']],
    signs: ['You know who shot it, not only who starred in it.', 'You notice the aspect ratio.', 'You have a film for every mood, and views on subtitles.'],
    works: [['What Is Cinema?', 'André Bazin, 1958–62'], ['Hitchcock/Truffaut', 'François Truffaut, 1966'], ['Sculpting in Time', 'Andrei Tarkovsky, 1986']],
  },
  musician: {
    figure: 'Orpheus, whose lyre moved stones and nearly brought the dead back.',
    essay: 'The musician meets reality as vibration organised in time. A chord is mathematics you can feel; a melody is the memory of a movement. Nearly every human culture has made music, and none has needed a translator for it. The musician’s discipline is repetition until freedom: scales for years, so that one night the hands can forget them.',
    lineage: [
      [-38000, 'c. 38,000 BC', 'A flute is carved from a vulture’s wing bone at Hohle Fels, in Germany.'],
      [1025, 'c. 1025', 'Guido of Arezzo teaches singers with lines and spaces: the staff.'],
      [1722, '1722', 'Bach completes the first book of The Well-Tempered Clavier.'],
      [1877, '1877', 'Edison records a voice on tinfoil and plays it back.'],
    ],
    practice: ['Plays scales daily.', 'Listens more than plays.', 'Learns by ear.', 'Practises the hard bar slowly.'],
    lexicon: [['Interval', 'The distance between two notes.'], ['Tempo', 'The speed of the beat.'], ['Timbre', 'The colour of a sound.'], ['Pentatonic', 'A five-note scale found all over the world.']],
    signs: ['You tap rhythms on tables.', 'A song can change your mood within eight bars.', 'You hear the bass line first.'],
    works: [['This Is Your Brain on Music', 'Daniel Levitin, 2006'], ['The Rest Is Noise', 'Alex Ross, 2007'], ['How Music Works', 'David Byrne, 2012']],
  },
  entrepreneur: {
    figure: 'Mercury, god of merchants, messages and roads, with wings on his heels.',
    essay: 'The entrepreneur meets reality as an unmet need. Where others see a problem, they see a business; where others see risk, they see the price of being first. Schumpeter called the process creative destruction: new firms displacing old ones, and the economy renewing itself through failure. The entrepreneur’s courage is to be wrong in public, often with other people’s money.',
    lineage: [
      [1602, '1602', 'The Dutch East India Company sells shares to the public in Amsterdam.'],
      [1759, '1759', 'Josiah Wedgwood starts his pottery in Burslem.'],
      [1911, '1911', 'Schumpeter puts the entrepreneur at the centre of economic change.'],
      [1939, '1939', 'Hewlett and Packard found their company in a garage in Palo Alto.'],
    ],
    practice: ['Talks to customers before building.', 'Tests the cheapest version first.', 'Watches cash every week.', 'Hears “no” as information.'],
    lexicon: [['Product–market fit', 'When people want it faster than you can make it.'], ['Runway', 'Months until the money runs out.'], ['Pivot', 'Changing direction without stopping.'], ['Equity', 'A share of what it becomes.']],
    signs: ['Every annoyance looks like a business to you.', 'You own a domain name you never used.', 'Risk excites you more than it frightens you.'],
    works: [['The Lean Startup', 'Eric Ries, 2011'], ['Capitalism, Socialism and Democracy', 'Joseph Schumpeter, 1942'], ['Shoe Dog', 'Phil Knight, 2016']],
  },
  biohacker: {
    figure: 'The alchemist at the furnace, looking for the elixir of life.',
    essay: 'The biohacker treats the body as an experiment with a sample size of one. Sleep is measured, food is logged, light and cold become tools. The roots are old, from Cornaro’s sober life to Santorio weighing himself for thirty years, but cheap sensors made it common. At its best it is self-knowledge with data; at its worst, a life spent optimising a number.',
    lineage: [
      [1558, '1558', 'Luigi Cornaro, in his eighties, publishes his Discourses on the Sober Life.'],
      [1614, '1614', 'Santorio publishes the results of decades of weighing himself, food and waste.'],
      [1953, '1953', 'Aserinsky and Kleitman describe REM sleep.'],
      [2007, '2007', 'Gary Wolf and Kevin Kelly name the Quantified Self.'],
    ],
    practice: ['Tracks sleep.', 'Changes one variable at a time.', 'Gets light in the morning.', 'Measures a baseline before trying anything.'],
    lexicon: [['n-of-1', 'A trial with one subject: you.'], ['Hormesis', 'Benefit from a small dose of stress.'], ['Baseline', 'What normal looks like, measured.'], ['Circadian', 'The body’s rhythm of about a day.']],
    signs: ['You know your resting heart rate.', 'Your morning has a protocol.', 'You have read a supplement label critically.'],
    works: [['Discourses on the Sober Life', 'Luigi Cornaro, 1558'], ['Why We Sleep', 'Matthew Walker, 2017'], ['Outlive', 'Peter Attia, 2023']],
  },
  looksmaxxer: {
    figure: 'Narcissus at the pool, who could not look away.',
    essay: 'The looksmaxxer meets reality as it is seen. Appearance is a surface, but it is the surface others meet first, and tending it is old: Egyptian kohl, Greek canons of proportion, the Regency dandy. The word is new, coined in online forums; the impulse is ancient. Its gift is self-respect made visible. Its shadow is a mirror that never says enough.',
    lineage: [
      [-4000, 'c. 4000 BC', 'Malachite and galena eye paint is ground on palettes in predynastic Egypt.'],
      [-450, 'c. 450 BC', 'Polykleitos writes his Canon of ideal human proportion.'],
      [1800, 'c. 1800', 'Beau Brummell makes the plain, perfectly cut coat the London fashion.'],
      [2014, '2010s', 'The word looksmaxxing spreads from online forums.'],
    ],
    practice: ['Sleeps enough, for the skin.', 'Stands up straight.', 'Learns what suits them.', 'Keeps the routine short enough to keep.'],
    lexicon: [['Symmetry', 'The left matched to the right.'], ['Canon', 'A rule of ideal proportion, after Polykleitos.'], ['Grooming', 'The daily upkeep of appearance.'], ['Glow-up', 'A visible change for the better, over time.']],
    signs: ['You know your best angle.', 'Your skincare has more than three steps.', 'You notice posture in photographs.'],
    works: [['The Picture of Dorian Gray', 'Oscar Wilde, 1890'], ['The Beauty Myth', 'Naomi Wolf, 1990'], ['Survival of the Prettiest', 'Nancy Etcoff, 1999']],
  },
  theologian: {
    figure: 'Jacob, who wrestled an angel until dawn and would not let go without a blessing.',
    essay: 'The theologian meets reality as gift and question at once: if there is a ground of all being, what is it like, and what does it ask of us? Theology is faith thinking about itself, with logic, history and argument, inside traditions that have kept one conversation going for millennia. Its gift is a language for ultimate things; its shadow is a certainty that forgets it was ever a question.',
    lineage: [
      [400, 'c. 400', 'Augustine writes the Confessions, addressed to God.'],
      [1095, '1095', 'Al-Ghazali writes The Incoherence of the Philosophers.'],
      [1190, 'c. 1190', 'Maimonides completes The Guide for the Perplexed.'],
      [1265, '1265', 'Thomas Aquinas begins the Summa Theologiae.'],
    ],
    practice: ['Reads the old texts in their own languages.', 'Prays and argues, sometimes in the same hour.', 'Keeps the feasts.', 'Takes the strongest objection seriously.'],
    lexicon: [['Revelation', 'What is disclosed, rather than discovered.'], ['Exegesis', 'Drawing the meaning out of a text.'], ['Apophatic', 'Speaking of God only by what God is not.'], ['Theodicy', 'Why a good God permits evil: Leibniz’s word, 1710.']],
    signs: ['You want to know why, not only how.', 'You have read a sacred text more than once.', 'The largest questions feel like home, not like vertigo.'],
    works: [['Confessions', 'Augustine of Hippo, c. 400'], ['The Guide for the Perplexed', 'Moses Maimonides, c. 1190'], ['I and Thou', 'Martin Buber, 1923']],
  },
  gardener: {
    figure: 'Demeter, whose grief is winter and whose joy is spring.',
    essay: 'The gardener meets reality at the speed of living things. Nothing can be forced: seeds keep their own time, and the weather has the last word. To garden is to collaborate with soil, insects and seasons, and to accept that most of the work is waiting. The reward is a piece of the world left more alive than it was found.',
    lineage: [
      [-9500, 'c. 9500 BC', 'Einkorn and emmer wheat are first cultivated in the Fertile Crescent.'],
      [-600, 'c. 600 BC', 'The Hanging Gardens of Babylon, if they existed, are planted.'],
      [1866, '1866', 'Gregor Mendel publishes the laws he found in his monastery’s pea beds.'],
      [1975, '1975', 'Masanobu Fukuoka publishes The One-Straw Revolution.'],
    ],
    practice: ['Watches before acting.', 'Feeds the soil, not the plant.', 'Saves seed.', 'Weeds a little every day.'],
    lexicon: [['Compost', 'Waste turned into fertility.'], ['Perennial', 'A plant that comes back every year.'], ['Succession', 'One crop following another in the same ground.'], ['Phyllotaxis', 'The spiral order of leaves and seeds.']],
    signs: ['You check the forecast for the plants’ sake.', 'You talk to them.', 'Patience comes more easily with soil on your hands.'],
    works: [['The One-Straw Revolution', 'Masanobu Fukuoka, 1975'], ['The Well-Tempered Garden', 'Christopher Lloyd, 1970'], ['Second Nature', 'Michael Pollan, 1991']],
  },
  storyteller: {
    figure: 'Scheherazade, who told a story every night for a thousand and one nights, to stay alive.',
    essay: 'The storyteller meets reality by giving it a shape: beginning, trouble, turn, end. We remember stories where we forget facts, and every culture’s knowledge was first carried in them. To tell is to choose what matters, what came first and what it meant. The gift is meaning that travels; the shadow is the tidy story that is not true.',
    lineage: [
      [-2100, 'c. 2100 BC', 'The first poems of Gilgamesh are written down in Sumer.'],
      [-750, 'c. 750 BC', 'The Iliad and the Odyssey take the form we know.'],
      [1353, 'c. 1353', 'Boccaccio’s Decameron: ten young people, a hundred stories, a plague outside.'],
      [1863, '1863', 'Gustav Freytag draws the five-part pyramid of dramatic structure.'],
    ],
    practice: ['Listens for the detail that makes it true.', 'Starts in the middle.', 'Cuts the beginning.', 'Tells it aloud before writing it down.'],
    lexicon: [['Plot', 'Events in an order that means something.'], ['Narrator', 'Who tells, and how much they know.'], ['Arc', 'How a character changes.'], ['In medias res', 'Starting in the middle of things: Horace’s advice.']],
    signs: ['You remember people by their stories.', 'You exaggerate slightly, for effect.', 'You cannot leave a book unfinished.'],
    works: [['One Thousand and One Nights', 'from the 9th century'], ['Aspects of the Novel', 'E. M. Forster, 1927'], ['The Hero with a Thousand Faces', 'Joseph Campbell, 1949']],
  },
  detective: {
    figure: 'Oedipus, who solved the Sphinx’s riddle, then his own crime.',
    essay: 'The detective meets reality as a puzzle that has an answer. Something happened; it left traces; reason can follow them back. The method, to observe, infer and eliminate, is cousin to the scientist’s, but aimed at a single event that will never happen again. The detective’s gift is justice that begins with attention; the shadow is the theory that bends the evidence.',
    lineage: [
      [1812, '1812', 'Eugène François Vidocq, once a convict, founds the Sûreté in Paris.'],
      [1841, '1841', 'Poe’s The Murders in the Rue Morgue invents the detective story.'],
      [1887, '1887', 'Sherlock Holmes first appears, in A Study in Scarlet.'],
      [1910, '1910', 'Edmond Locard opens a police laboratory in Lyon: every contact leaves a trace.'],
    ],
    practice: ['Writes everything down.', 'Goes back to the scene.', 'Asks the same question twice, differently.', 'Distrusts the first explanation.'],
    lexicon: [['Alibi', 'Proof of being elsewhere.'], ['Motive, means, opportunity', 'The three things a suspect must have.'], ['Red herring', 'A false clue.'], ['Exchange principle', 'Locard’s rule: every contact leaves a trace.']],
    signs: ['You notice what has changed in a room.', 'You guess the twist by the halfway point.', 'Inconsistencies in a story will not leave you alone.'],
    works: [['The Murders in the Rue Morgue', 'Edgar Allan Poe, 1841'], ['The Moonstone', 'Wilkie Collins, 1868'], ['A Study in Scarlet', 'Arthur Conan Doyle, 1887']],
  },
  archivist: {
    figure: 'Mnemosyne, goddess of memory and mother of the nine Muses.',
    essay: 'The archivist meets reality as what must not be lost. Most of the past has vanished; what remains survived because someone kept it, described it and let others find it. The work is quiet and long: deciding what to keep, cataloguing it honestly, guarding it from fire, damp and forgetting. Without archives there is no history, only rumour.',
    lineage: [
      [-650, 'c. 650 BC', 'Ashurbanipal gathers a library of clay tablets at Nineveh.'],
      [-285, 'c. 285 BC', 'The Library of Alexandria is founded.'],
      [1876, '1876', 'Melvil Dewey publishes his decimal classification.'],
      [1996, '1996', 'The Internet Archive begins saving the web.'],
    ],
    practice: ['Records where everything came from.', 'Keeps originals and works from copies.', 'Labels in pencil.', 'Helps people find what they did not know to look for.'],
    lexicon: [['Provenance', 'Where a thing has been, and who held it.'], ['Fonds', 'All the records made by one creator.'], ['Accession', 'A new arrival, formally received.'], ['Finding aid', 'The map to a collection.']],
    signs: ['You keep tickets, letters and receipts.', 'Your boxes are labelled.', 'Deleting old photographs feels like a small wrong.'],
    works: [['The Library of Babel', 'Jorge Luis Borges, 1941'], ['Archive Fever', 'Jacques Derrida, 1995'], ['Burning the Books', 'Richard Ovenden, 2020']],
  },
}

// every dated moment, in order, with the archetype it belongs to
export const EVENTS = Object.entries(DOSSIERS)
  .flatMap(([id, d]) => d.lineage.map(([year, label, text]) => ({ id, year, label, text })))
  .sort((a, b) => a.year - b.year)
