// Encyclopedia entries, orders III and IV: Disciplines and The City.
export default {
  warrior: {
    etym: 'From Old North French werreieor, from werre, “war”, a word of Germanic origin related to Old High German werra, “confusion, strife”. Latin bellum gave English belligerent, but not its everyday word for war.',
    def: 'One who meets reality as resistance and conflict, and answers it with trained courage, discipline and force placed in the service of something.',
    figure: 'Achilles before Troy, and Arjuna on the field of Kurukshetra, who hesitated.',
    overview: [
      'The warrior is defined less by fighting than by a relation to fear and death. Every warrior culture, from Homeric Greece to the samurai, built an ethic around facing danger deliberately: training, codes of honour, rites of initiation and mourning. The skill is violence; the virtue is self-command.',
      'The archetype reaches well beyond war. Athletes, surgeons, firefighters and people facing serious illness use the warrior’s vocabulary of discipline and endurance, and Stoic and Buddhist traditions describe the inner struggle as the real battle. The figure persists because human life contains things that must be faced rather than solved.',
    ],
    history: [
      'The earliest epics are warrior poetry: Gilgamesh and Enkidu, Achilles and Hector, and Arjuna at Kurukshetra, where in the Bhagavad Gita the god Krishna teaches a reluctant warrior about duty. Many early states were founded and ruled by warrior aristocracies.',
      'Many civilisations codified a warrior ethic: the Spartan agoge, Roman virtus, Islamic and Christian rules of just war, European chivalry, the Japanese code later called bushidō. Treatises such as Sun Tzu’s Art of War and Clausewitz’s On War treated conflict as something to be understood, not only endured.',
      'Industrial war broke much of the old romance. The machine gun, the trench and the bomber made courage less decisive than logistics, and writers such as Remarque and Wilfred Owen turned the warrior’s story toward trauma, a theme medicine recognised in 1980 as post-traumatic stress disorder.',
    ],
    distinctions: [
      ['Warrior and soldier', 'The soldier is a role in an institution, under orders; the warrior is an ideal of personal courage and honour. Modern armies try, with mixed success, to make soldiers with the warrior’s virtues and without the warrior’s independence.'],
      ['Courage and recklessness', 'Aristotle placed courage between cowardice and rashness. The warrior traditions agree: fearlessness is not a virtue, and someone who feels no fear has nothing to master.'],
    ],
    critique: 'The warrior ideal has glorified violence, ignored the women who fought, and been used to recruit the young into wars made by the old. Its shadow, named on the plate, is the need for an enemy: a way of being that needs conflict in order to have meaning will tend to find it, or make it.',
    now: 'Wars are now fought with drones, code and logistics as well as soldiers, and the warrior’s virtues are widely borrowed by sport, business and self-help. Veterans’ own writing has made the cost of the archetype more visible than its glory.',
    lineage: [
      [-1274, 'c. 1274 BC', 'Egypt and the Hittites fight at Kadesh; their later peace treaty survives in both empires’ archives.'],
      [-480, '480 BC', 'Three hundred Spartans and their allies hold the pass at Thermopylae.'],
      [-450, 'c. 5th century BC', 'The Art of War, attributed to Sun Tzu, is compiled.'],
      [-200, 'c. 2nd century BC', 'The Bhagavad Gita: Krishna counsels Arjuna on the eve of battle.'],
      [1645, 'c. 1645', 'Miyamoto Musashi writes The Book of Five Rings in a cave.'],
      [1832, '1832', 'Clausewitz’s On War is published, after his death.'],
      [1929, '1929', 'Remarque’s All Quiet on the Western Front tells the war from the trench.'],
      [1980, '1980', 'Post-traumatic stress disorder enters psychiatry’s diagnostic manual.'],
    ],
    figures: [
      ['Leonidas', 'd. 480 BC', 'Spartan king who held Thermopylae with a small rear guard.'],
      ['Joan of Arc', 'c. 1412–1431', 'Peasant girl who led French armies at seventeen.'],
      ['Miyamoto Musashi', 'c. 1584–1645', 'Undefeated duellist who ended his life as a painter and writer.'],
      ['Yaa Asantewaa', 'c. 1840–1921', 'Asante queen mother who led the War of the Golden Stool against the British in 1900.'],
    ],
    lexicon: [
      ['Discipline', 'Doing it when you do not want to.'],
      ['Courage', 'Acting in the presence of fear, not in its absence.'],
      ['Honour', 'A code that binds even when no one is watching.'],
      ['Strategy', 'The plan of the whole; tactics are the moves.'],
      ['Agōn', 'Greek for contest: the struggle that reveals what someone is.'],
    ],
    practice: ['Trains when there is nothing to train for.', 'Keeps the body ready and the word kept.', 'Studies the opponent.', 'Rests on purpose.'],
    signs: ['You choose the harder way to prove that you can.', 'You like a clear opponent.', 'People call you when something has to be faced.'],
    reading: [
      ['The Iliad', 'Homer, c. 750 BC'],
      ['The Book of Five Rings', 'Miyamoto Musashi, c. 1645'],
      ['On War', 'Carl von Clausewitz, 1832'],
      ['All Quiet on the Western Front', 'Erich Maria Remarque, 1929'],
      ['Achilles in Vietnam', 'Jonathan Shay, 1994'],
    ],
  },

  monk: {
    etym: 'From Greek monachos, “solitary”, from monos, “alone”, through Latin monachus. The word first named the Christian hermits of the Egyptian desert, and was later extended to members of contemplative orders in other traditions.',
    def: 'One who meets reality by withdrawing from its ordinary demands (possessions, marriage, ambition, noise) in order to attend to what remains when they are gone.',
    figure: 'The hermit in the desert, and the Buddha beneath the Bodhi tree.',
    overview: [
      'Monasticism is a structured experiment in subtraction, and its elements are strikingly similar across traditions: vows of poverty and chastity, a rule that governs the day, communal or solitary prayer and meditation, manual work and a teacher. The aim is not suffering for its own sake but a transformation of attention, so that the mind stops grasping and begins to see.',
      'The monk is often imagined alone, but most monks have lived in communities, and monasteries have been among history’s great institutions: keepers of texts, founders of hospitals, farms, breweries and schools. Withdrawal from the world has repeatedly produced things the world later came to depend on.',
    ],
    history: [
      'Organised renunciation appears first in India. The Buddha’s sangha and the Jain orders, in the fifth century BC, wrote rules for wandering and settled monastics, and Buddhist monasticism spread across Asia to become a pillar of societies from Sri Lanka to Japan.',
      'Christian monasticism began in the deserts of Egypt and Syria in the third and fourth centuries, with Anthony and then Pachomius, who founded communal monasteries. Benedict’s Rule, written around 530, gave Western monasteries a moderate pattern of prayer and work that, through Cluny and the Cistercians, shaped the economy and learning of medieval Europe.',
      'Reformations, revolutions and secularisation dissolved many monasteries, but the tradition survived and found an unexpected modern reach: Thomas Merton’s writing, the Zen teachers who came to the West in the 1950s and 60s, and the secular mindfulness movement, which adapted monastic meditation for hospitals and offices.',
    ],
    distinctions: [
      ['Monk and mystic', 'The monk lives by a rule within an institution; the mystic is defined by an experience, which may come to a monk, a married layperson or an unbeliever.'],
      ['Renunciation and asceticism', 'Renunciation gives things up; asceticism trains through hardship. The Buddha rejected extreme asceticism, proposing a Middle Way.'],
    ],
    critique: 'Monasticism has been criticised as an escape from responsibility, as dependence on others’ labour and alms, and, in parts of its history, as a source of wealth, abuse and political power. Within the traditions the warning is subtler: spiritual pride, the sense of standing above the world one has left.',
    now: 'Monastic communities continue on every continent, smaller than they were, while their practices have spread into ordinary life as retreats, digital detoxes, silent days and meditation apps. The monk’s question, what remains when you stop, has a large new audience.',
    lineage: [
      [-450, '5th century BC', 'Siddhartha Gautama sits beneath a fig tree at Bodh Gaya and awakens.'],
      [270, 'c. 270', 'Anthony withdraws into the Egyptian desert; others follow him there.'],
      [320, 'c. 320', 'Pachomius founds a communal monastery at Tabennisi on the Nile.'],
      [530, 'c. 530', 'Benedict writes his Rule for monks at Monte Cassino.'],
      [910, '910', 'The abbey of Cluny is founded; its network will reshape the Western church.'],
      [1227, '1227', 'Dōgen returns from China and brings Sōtō Zen to Japan.'],
      [1948, '1948', 'Thomas Merton publishes The Seven Storey Mountain.'],
      [1979, '1979', 'Jon Kabat-Zinn begins teaching mindfulness-based stress reduction in Massachusetts.'],
    ],
    figures: [
      ['Anthony the Great', 'c. 251–356', 'Went into the desert; others followed.'],
      ['Benedict of Nursia', 'c. 480–547', 'Wrote a rule balanced between prayer and work.'],
      ['Dōgen', '1200–1253', 'Taught that sitting itself is awakening.'],
      ['Thomas Merton', '1915–1968', 'Trappist monk whose writing carried contemplation to a wide public.'],
    ],
    lexicon: [
      ['Zazen', 'Just sitting.'],
      ['Ora et labora', 'Pray and work: the Benedictine pattern.'],
      ['Detachment', 'Holding without clutching.'],
      ['Kōan', 'A question that thinking cannot solve.'],
      ['Sangha', 'The community of practitioners, one of the Three Jewels of Buddhism.'],
    ],
    practice: ['Rises before the light.', 'Sits.', 'Works with the hands.', 'Keeps silence at fixed hours.'],
    signs: ['You like empty rooms.', 'You leave your phone in another room on purpose.', 'Quiet feels like rest, not absence.'],
    reading: [
      ['The Sayings of the Desert Fathers', '4th–5th century'],
      ['The Rule of Saint Benedict', 'c. 530'],
      ['The Seven Storey Mountain', 'Thomas Merton, 1948'],
      ['Zen Mind, Beginner’s Mind', 'Shunryu Suzuki, 1970'],
      ['Full Catastrophe Living', 'Jon Kabat-Zinn, 1990'],
    ],
  },

  biohacker: {
    etym: 'A compound of bio-, from Greek bios, “life”, and hacker, which in the slang of MIT’s Tech Model Railroad Club in the late 1950s meant someone who solves a problem with an ingenious, unofficial fix. The compound spread in the 2000s.',
    def: 'One who meets reality as a body that can be measured, experimented on and improved, usually their own and often outside medical institutions.',
    figure: 'The alchemist at the furnace, looking for the elixir of life.',
    overview: [
      'Biohacking covers a wide range, from tracking sleep and diet to do-it-yourself biology labs and, at the fringe, self-implanted devices and unregulated gene therapies. What unites it is the stance of the experimenter towards their own body: the conviction that it can be understood through data and changed through deliberate intervention.',
      'Its key method is the n-of-1 trial, an experiment with a single subject. Clinicians use such trials legitimately to choose treatments for individual patients, but they are vulnerable to placebo effects, regression to the mean and the difficulty of blinding oneself. Good biohackers know this, keep baselines and change one variable at a time; many do not.',
    ],
    history: [
      'Self-experiment has a long medical history. Santorio Santorio weighed himself, his food and his excretions for decades and published the results in 1614, discovering “insensible perspiration”. Luigi Cornaro’s Discourses on the Sober Life (1558) recommended strict moderation and claimed it had kept him well into old age.',
      'Many physicians tested treatments on themselves first. Werner Forssmann threaded a catheter into his own heart in 1929; Barry Marshall drank a culture of Helicobacter pylori in 1984 to prove that it causes ulcers, and shared a Nobel Prize for it in 2005. These are the heroic side of the archetype.',
      'Cheap sensors, smartphones and online communities made the modern movement. The Quantified Self was named in 2007, and DIY biology groups and longevity enthusiasts followed. The movement now overlaps with a large wellness industry selling supplements, devices and protocols.',
    ],
    distinctions: [
      ['Biohacker and scientist', 'The scientist generalises from many subjects under controls; the biohacker seeks what works for one. The best biohackers borrow scientific method; the worst borrow only its vocabulary.'],
      ['Optimisation and health', 'Health is the absence of illness and the capacity to live well; optimisation seeks a better number. The two can diverge, as when tracking itself becomes a source of anxiety.'],
    ],
    critique: 'Critics point to the weak evidence behind many popular interventions, the commercial interests of those who promote them, and the risks of unsupervised experiment. Others see a privatisation of health: a project for those with time and money, while public health depends on collective measures. The shadow on the plate, living for the number, is the most common complaint of former enthusiasts.',
    now: 'Wearables record heart rate, sleep and glucose for millions of people who would never call themselves biohackers. The question has moved from whether to measure to what the measurements mean, and who owns them.',
    lineage: [
      [1558, '1558', 'Luigi Cornaro, in his eighties, publishes his Discourses on the Sober Life.'],
      [1614, '1614', 'Santorio publishes the results of decades spent weighing himself, his food and his waste.'],
      [1929, '1929', 'Werner Forssmann threads a catheter into his own heart.'],
      [1953, '1953', 'Aserinsky and Kleitman describe REM sleep.'],
      [1964, '1964', 'Randy Gardner stays awake for eleven days, watched by sleep researchers.'],
      [1984, '1984', 'Barry Marshall drinks a culture of Helicobacter pylori to show that it causes ulcers.'],
      [2007, '2007', 'Gary Wolf and Kevin Kelly name the Quantified Self.'],
      [2008, '2008', 'DIYbio is founded to support amateur biology laboratories.'],
    ],
    figures: [
      ['Luigi Cornaro', 'c. 1464–1566', 'Venetian advocate of moderation, said to have lived to about a hundred.'],
      ['Santorio Santorio', '1561–1636', 'Weighed his own life for thirty years.'],
      ['Barry Marshall', 'b. 1951', 'Proved a bacterium causes ulcers by infecting himself.'],
      ['Seth Roberts', '1953–2014', 'Psychologist who made self-experimentation a research method.'],
    ],
    lexicon: [
      ['n-of-1', 'A trial with one subject: you.'],
      ['Hormesis', 'Benefit from a small dose of stress.'],
      ['Baseline', 'What normal looks like, measured.'],
      ['Circadian', 'The body’s rhythm of about a day.'],
      ['Placebo', 'An effect produced by the expectation of treatment.'],
    ],
    practice: ['Tracks sleep.', 'Changes one variable at a time.', 'Gets light in the morning.', 'Measures a baseline before trying anything.'],
    signs: ['You know your resting heart rate.', 'Your morning has a protocol.', 'You have read a supplement label critically.'],
    reading: [
      ['Discourses on the Sober Life', 'Luigi Cornaro, 1558'],
      ['Who Goes First?', 'Lawrence K. Altman, 1987'],
      ['The Quantified Self', 'Deborah Lupton, 2016'],
      ['Why We Sleep', 'Matthew Walker, 2017'],
      ['Outlive', 'Peter Attia, 2023'],
    ],
  },

  looksmaxxer: {
    etym: 'Internet slang, from looks and maxx, from maximise. The word spread from online forums in the early 2010s, some associated with the “manosphere”, along with a vocabulary of “mewing”, “softmaxxing” and “hardmaxxing”.',
    def: 'One who meets reality as it is seen, and works deliberately on their own appearance as a form of self-improvement, status or self-respect.',
    figure: 'Narcissus at the pool, who could not look away.',
    overview: [
      'Looksmaxxing names a very old practice in a new idiom. Grooming, dress, posture and cosmetics are among the most universal human behaviours, and every society has had ideals of beauty and techniques for approaching them. What is new is the explicitness: appearance treated as a project with metrics, protocols and before-and-after photographs.',
      'The practice runs from the uncontroversial (sleep, skincare, exercise, a good haircut) to the extreme: cosmetic surgery, so-called bone-smashing and steroids. Research on attractiveness gives it some basis, since appearance does affect how people are treated, in hiring, in court and in friendship. That same finding is the source of its anxieties.',
    ],
    history: [
      'Cosmetics are ancient. Egyptian men and women lined their eyes with kohl and malachite, partly to protect them from sun and infection. Greek sculptors sought ideal proportions, and Polykleitos’ Canon, around 450 BC, set out a system of ratios for the perfect body.',
      'European courts made appearance a political art, and around 1800 the dandy Beau Brummell made restraint itself the fashion. Baudelaire praised the dandy as a hero of self-creation. In the twentieth century cinema, advertising and a cosmetics industry made idealised faces ubiquitous.',
      'The word belongs to online forums of the 2010s, some of them tied to the fatalistic belief that looks determine a person’s whole fate. By the 2020s it had spread to mainstream social media, where it is often more playful, and where young men discuss openly what was once confined to women’s magazines.',
    ],
    distinctions: [
      ['Grooming and looksmaxxing', 'Grooming maintains; looksmaxxing optimises, measuring the face against an ideal. The difference lies more in the attitude than in the practices.'],
      ['Vanity and self-respect', 'Vanity seeks admiration; self-respect makes care visible. Wilde’s dandies blurred the two on purpose, and so does the archetype.'],
    ],
    critique: 'Critics see a sharpened form of body anxiety, now directed at young men, with links to body dysmorphia, eating disorders and risky procedures, and to ideologies that rank people by their faces. Naomi Wolf’s The Beauty Myth (1990) made a similar argument about women. The archetype’s best answer is the plate’s secret: no one else is looking as closely as you are.',
    now: 'Filters, front cameras and facial-analysis apps make appearance more measurable than ever, and cosmetic procedures have become routine. The looksmaxxer is less an outlier than an exaggeration of what most people with a phone now do.',
    lineage: [
      [-4000, 'c. 4000 BC', 'Malachite and galena eye paint is ground on palettes in predynastic Egypt.'],
      [-1345, 'c. 1345 BC', 'The bust of Nefertiti is carved, an ideal of beauty still copied.'],
      [-450, 'c. 450 BC', 'Polykleitos writes his Canon of ideal human proportion.'],
      [1800, 'c. 1800', 'Beau Brummell makes the plain, perfectly cut coat the London fashion.'],
      [1863, '1863', 'Baudelaire’s The Painter of Modern Life praises the dandy.'],
      [1909, '1909', 'Eugène Schueller founds the company that becomes L’Oréal.'],
      [2010, '2010', 'Instagram launches, and the face becomes a feed.'],
      [2014, '2010s', 'The word looksmaxxing spreads from online forums.'],
    ],
    figures: [
      ['Polykleitos', '5th century BC', 'Sculptor who wrote down the proportions of beauty.'],
      ['Beau Brummell', '1778–1840', 'Made understatement the height of fashion.'],
      ['Oscar Wilde', '1854–1900', 'Dandy, and the sharpest critic of the surface he loved.'],
      ['Helena Rubinstein', '1872–1965', 'Built a cosmetics empire on the idea that beauty can be made.'],
    ],
    lexicon: [
      ['Symmetry', 'The left matched to the right.'],
      ['Canon', 'A rule of ideal proportion, after Polykleitos.'],
      ['Grooming', 'The daily upkeep of appearance.'],
      ['Glow-up', 'A visible change for the better, over time.'],
      ['Halo effect', 'The habit of crediting attractive people with other good qualities.'],
    ],
    practice: ['Sleeps enough, for the skin.', 'Stands up straight.', 'Learns what suits them.', 'Keeps the routine short enough to keep.'],
    signs: ['You know your best angle.', 'Your skincare has more than three steps.', 'You notice posture in photographs.'],
    reading: [
      ['The Painter of Modern Life', 'Charles Baudelaire, 1863'],
      ['The Picture of Dorian Gray', 'Oscar Wilde, 1890'],
      ['The Beauty Myth', 'Naomi Wolf, 1990'],
      ['The Body Project', 'Joan Jacobs Brumberg, 1997'],
      ['Survival of the Prettiest', 'Nancy Etcoff, 1999'],
    ],
  },

  sovereign: {
    etym: 'From Old French soverain, from Vulgar Latin superanus, “one above”, from Latin super, “over”. Jean Bodin, in 1576, defined sovereignty as the absolute and perpetual power of a commonwealth.',
    def: 'One who meets reality as something to be ordered, and takes responsibility for decisions that bind others: rulers, but also founders, judges and anyone who governs.',
    figure: 'Solomon, who asked for wisdom instead of wealth, and was given both.',
    overview: [
      'The sovereign is about authority: the right, not merely the power, to decide. Some order is a precondition of every other way in this atlas; scientists need institutions, merchants need contracts, monks need peace. The sovereign’s work is to provide it, and their legitimacy rests on whether those they govern accept it as rightful.',
      'Political thought has spent much of its history on the sovereign’s two problems: how to get good rule, and how to restrain bad rule. Plato answered with the philosopher-king, Confucius with virtue and ritual, Hobbes with an absolute ruler as the only escape from war, and the constitutional tradition by dividing power so that no one holds all of it.',
    ],
    history: [
      'The earliest written laws, from Ur-Nammu to Hammurabi, present the king as the giver of justice under the gods. In China the Zhou developed the Mandate of Heaven, under which a ruler who governed badly lost the right to rule, an idea with revolutionary implications.',
      'Medieval and early modern Europe worked out the doctrines of the modern state: Magna Carta’s limits on the king (1215), Bodin’s theory of sovereignty (1576), the Peace of Westphalia’s system of sovereign states (1648) and Hobbes’ Leviathan (1651). The American and French revolutions placed sovereignty in the people.',
      'The twentieth century produced totalitarian sovereigns and new limits on sovereignty: international law, human rights and supranational bodies. Today the archetype is lived mostly in offices, courts and boardrooms, as well as in palaces.',
    ],
    distinctions: [
      ['Power and authority', 'Power is the ability to compel; authority is power accepted as rightful. Max Weber distinguished traditional, charismatic and legal authority.'],
      ['Sovereign and tyrant', 'For Greek thinkers the tyrant was the ruler who governed for himself rather than for the city. The difference lies not in how much power one holds but in whom it serves.'],
    ],
    critique: 'Anarchists from Proudhon to Kropotkin argued that sovereignty is itself domination; liberals warned that power corrupts its holders; Michel Foucault suggested that modern power works less through sovereigns than through institutions, norms and surveillance. The archetype’s own shadow is the crown that forgets it was lent.',
    now: 'Sovereignty is contested between nations and international bodies, governments and technology platforms, and in arguments over data, borders and the atmosphere. Each of those disputes asks the sovereign’s old question: who decides?',
    lineage: [
      [-2100, 'c. 2100 BC', 'Ur-Nammu of Ur issues the oldest surviving law code.'],
      [-1754, 'c. 1754 BC', 'Hammurabi of Babylon has his laws carved in stone for all to read.'],
      [-1046, 'c. 1046 BC', 'The Zhou claim the Mandate of Heaven after overthrowing the Shang.'],
      [-260, 'c. 260 BC', 'After the Kalinga war, Ashoka carves edicts of tolerance across his empire.'],
      [1215, '1215', 'King John seals Magna Carta at Runnymede.'],
      [1648, '1648', 'The Peace of Westphalia makes sovereignty the rule between states.'],
      [1787, '1787', 'The United States Constitution divides power among three branches.'],
      [1948, '1948', 'The Universal Declaration of Human Rights is adopted.'],
    ],
    figures: [
      ['Hammurabi', 'r. c. 1792–1750 BC', 'Published his laws so that the wronged could read them.'],
      ['Ashoka', 'c. 304–232 BC', 'A conqueror who renounced conquest.'],
      ['Elizabeth I', '1533–1603', 'Ruled England for forty-four years.'],
      ['Nelson Mandela', '1918–2013', 'Prisoner who became president, and stepped down after one term.'],
    ],
    lexicon: [
      ['Legitimacy', 'Power that others accept as rightful.'],
      ['Sovereignty', 'Final authority within a territory.'],
      ['Mandate', 'Permission to rule, from heaven or from the voters.'],
      ['Precedent', 'A decision that binds later ones.'],
      ['Separation of powers', 'Montesquieu’s principle (1748): divide power so that it checks itself.'],
    ],
    practice: ['Listens before deciding.', 'Delegates, and checks.', 'Keeps records.', 'Plans for a successor.'],
    signs: ['You end up organising the trip.', 'You notice who is in charge in any room.', 'You think in rules that would work for everyone.'],
    reading: [
      ['Politics', 'Aristotle, c. 350 BC'],
      ['Meditations', 'Marcus Aurelius, c. 175'],
      ['The Prince', 'Niccolò Machiavelli, 1532'],
      ['Leviathan', 'Thomas Hobbes, 1651'],
      ['The Origins of Political Order', 'Francis Fukuyama, 2011'],
    ],
  },

  rebel: {
    etym: 'From Latin rebellare, “to make war again”, from re-, “again”, and bellum, “war”: originally a defeated people taking up arms once more. The word has kept its sense of refusing a settlement that others treat as final.',
    def: 'One who meets reality as an order that need not be accepted, and refuses it, openly and at personal cost, in the name of something that order denies.',
    figure: 'Antigone, who buried her brother against the king’s decree and accepted the punishment.',
    overview: [
      'The rebel is defined by refusal. Albert Camus, in The Rebel (1951), begins with the slave who says no: in refusing an order the slave also affirms a limit, a dignity that must not be crossed, and in that affirmation discovers solidarity with others. Rebellion is therefore not mere negation. It says no to one thing in the name of another.',
      'The rebel differs from its neighbours in the City. The sovereign makes order; the trickster mocks it without wishing to replace it; the entrepreneur works around it for gain; the rebel confronts it and accepts the consequences. Its forms range from the solitary conscientious objector to mass movements, and from non-violent resistance to armed revolt.',
    ],
    history: [
      'Slave revolts, peasant risings and religious dissent run through recorded history: Spartacus against Rome (73–71 BC), the English Peasants’ Revolt of 1381, Luther before the emperor at Worms in 1521. Most were defeated, but they left songs, martyrs and ideas.',
      'The Age of Revolutions made rebellion a political principle. The American and French revolutions claimed a right to overthrow unjust government, and the Haitian Revolution (1791–1804), led by formerly enslaved people under Toussaint Louverture and others, made that claim universal.',
      'Thoreau’s essay on civil disobedience (1849) and Gandhi’s satyagraha developed a theory of principled, non-violent law-breaking, taken up by the American civil rights movement and by dissidents in the Soviet bloc. Václav Havel’s The Power of the Powerless (1978) argued that simply refusing to “live within the lie” could undermine a regime.',
    ],
    distinctions: [
      ['Rebel and revolutionary', 'The rebel refuses; the revolutionary seeks to seize power and build a new order. Camus warned that revolutions often betray the rebellion that started them.'],
      ['Rebel and trickster', 'The trickster breaks rules playfully and moves on; the rebel breaks them deliberately, stays, and takes the punishment. One unsettles order; the other opposes it.'],
    ],
    critique: 'Rebellion can harden into an identity that needs an oppressor in order to exist, or a style sold back to the young by the industries it claims to oppose. Revolutions have repeatedly produced tyrannies worse than the ones they overthrew. The rebel’s test, in Camus’ terms, is whether the refusal keeps faith with the limit it began by defending.',
    now: 'Rebellion is now organised on networks as well as streets, through strikes, boycotts, leaks and occupations. Research by Erica Chenoweth and Maria Stephan found that non-violent campaigns in the twentieth century succeeded roughly twice as often as violent ones.',
    lineage: [
      [-73, '73 BC', 'Spartacus breaks out of a gladiators’ school at Capua; tens of thousands join him.'],
      [1381, '1381', 'The English Peasants’ Revolt marches on London.'],
      [1521, '1521', 'Luther refuses to recant before the emperor at Worms.'],
      [1791, '1791', 'The Haitian Revolution begins; in 1804 Haiti becomes the first state founded by formerly enslaved people.'],
      [1849, '1849', 'Thoreau publishes Resistance to Civil Government, later called Civil Disobedience.'],
      [1930, '1930', 'Gandhi leads the Salt March to the sea at Dandi.'],
      [1955, '1955', 'Rosa Parks refuses to give up her seat on a Montgomery bus.'],
      [1978, '1978', 'Václav Havel writes The Power of the Powerless.'],
    ],
    figures: [
      ['Spartacus', 'd. 71 BC', 'Gladiator who led the largest slave revolt against Rome.'],
      ['Toussaint Louverture', 'c. 1743–1803', 'Formerly enslaved general of the Haitian Revolution.'],
      ['Harriet Tubman', 'c. 1822–1913', 'Escaped slavery, then returned again and again to lead others out.'],
      ['Václav Havel', '1936–2011', 'Dissident playwright, imprisoned, then president.'],
    ],
    lexicon: [
      ['Civil disobedience', 'Open, principled law-breaking, with acceptance of the penalty.'],
      ['Dissent', 'Disagreement made public.'],
      ['Solidarity', 'The bond rebellion discovers: my refusal is also yours.'],
      ['Satyagraha', 'Gandhi’s “truth-force”: non-violent resistance.'],
      ['Samizdat', 'Self-published, hand-copied writing that evaded Soviet censorship.'],
    ],
    practice: ['Says no, out loud.', 'Counts the cost before acting.', 'Finds the others who also refuse.', 'Keeps the reason clearer than the anger.'],
    signs: ['You cannot follow a rule you cannot justify.', 'You side with the outnumbered.', '“That’s just how it is” makes you want to change it.'],
    reading: [
      ['Civil Disobedience', 'Henry David Thoreau, 1849'],
      ['The Black Jacobins', 'C. L. R. James, 1938'],
      ['The Rebel', 'Albert Camus, 1951'],
      ['The Power of the Powerless', 'Václav Havel, 1978'],
      ['Why Civil Resistance Works', 'Erica Chenoweth and Maria J. Stephan, 2011'],
    ],
  },

  entrepreneur: {
    etym: 'From French entreprendre, “to undertake”, from entre, “between”, and prendre, “to take”. The economist Richard Cantillon, writing around 1730, first gave the entrepreneur a central role: one who buys at a known price in order to sell at an uncertain one.',
    def: 'One who meets reality as unmet need and unexploited possibility, and takes the risk of organising people and resources to meet it.',
    figure: 'Mercury, god of merchants, messages and roads, with wings on his heels.',
    overview: [
      'The entrepreneur’s distinctive relation to reality is uncertainty. Frank Knight (1921) distinguished risk, which can be calculated, from uncertainty, which cannot, and argued that profit is the reward for bearing the second. The entrepreneur acts before the evidence is in, because by the time it is, the opportunity has gone.',
      'Joseph Schumpeter made the entrepreneur the engine of capitalism: the innovator who brings new products, methods or markets and so destroys the old. Israel Kirzner drew a quieter picture: the entrepreneur as someone alert to gaps and mistakes in the market that others have missed. Both are visible in practice, in the founder who invents and the trader who notices.',
    ],
    history: [
      'Merchants and moneylenders appear with the first cities. Assyrian traders at Kanesh, in Anatolia, left thousands of tablets around 1900 BC recording partnerships, loans and caravan profits. Medieval Italian and Islamic merchants developed partnerships, bills of exchange and double-entry bookkeeping.',
      'The joint-stock company, such as the Dutch East India Company (1602), let strangers share risk. The Industrial Revolution produced the industrialist-entrepreneur, from Josiah Wedgwood to Andrew Carnegie, and with them the factory and the brand.',
      'In the twentieth century venture capital, from the 1940s, and the start-up culture of Silicon Valley turned entrepreneurship into an industry with its own methods and mythology, and a few enormously successful companies whose survival hides the many that failed.',
    ],
    distinctions: [
      ['Entrepreneur and manager', 'The manager runs an existing organisation well; the entrepreneur creates something that did not exist, under uncertainty. Many founders struggle once their company needs a manager instead.'],
      ['Entrepreneur and inventor', 'The inventor makes the new thing; the entrepreneur makes it into something people use and pay for. Edison was both; most people are one.'],
    ],
    critique: 'Critics argue that the heroic myth of the founder hides the public research, infrastructure and luck on which success depends, as Mariana Mazzucato argued in The Entrepreneurial State (2013), and that survivorship bias makes us study winners and forget the failures. The shadow on the plate is growth as an end in itself.',
    now: 'Most of the world’s entrepreneurs run small businesses far from venture capital. Social enterprises, cooperatives and open-source projects are testing whether the entrepreneur’s energy can serve ends other than profit.',
    lineage: [
      [-1900, 'c. 1900 BC', 'Assyrian merchants at Kanesh record partnerships, loans and caravan profits on clay.'],
      [1494, '1494', 'Luca Pacioli publishes the first printed account of double-entry bookkeeping.'],
      [1602, '1602', 'The Dutch East India Company sells shares to the public in Amsterdam.'],
      [1759, '1759', 'Josiah Wedgwood starts his pottery in Burslem.'],
      [1911, '1911', 'Schumpeter puts the entrepreneur at the centre of economic change.'],
      [1939, '1939', 'Hewlett and Packard found their company in a garage in Palo Alto.'],
      [1946, '1946', 'American Research and Development, an early venture capital firm, is founded.'],
      [1976, '1976', 'Muhammad Yunus begins lending to poor villagers in Bangladesh; Grameen Bank follows.'],
    ],
    figures: [
      ['Josiah Wedgwood', '1730–1795', 'Turned pottery into a brand and a factory system.'],
      ['Madam C. J. Walker', '1867–1919', 'Daughter of formerly enslaved parents; built a hair-care business and a fortune.'],
      ['Kōnosuke Matsushita', '1894–1989', 'Founded the company now called Panasonic from a small workshop in Osaka.'],
      ['Muhammad Yunus', 'b. 1940', 'Pioneered microcredit; Nobel Peace Prize, 2006.'],
    ],
    lexicon: [
      ['Product–market fit', 'When people want it faster than you can make it.'],
      ['Runway', 'Months until the money runs out.'],
      ['Pivot', 'Changing direction without stopping.'],
      ['Equity', 'A share of what it becomes.'],
      ['Creative destruction', 'Schumpeter’s phrase (1942) for innovation displacing what came before.'],
    ],
    practice: ['Talks to customers before building.', 'Tests the cheapest version first.', 'Watches cash every week.', 'Hears “no” as information.'],
    signs: ['Every annoyance looks like a business to you.', 'You own a domain name you never used.', 'Risk excites you more than it frightens you.'],
    reading: [
      ['Risk, Uncertainty and Profit', 'Frank Knight, 1921'],
      ['Capitalism, Socialism and Democracy', 'Joseph Schumpeter, 1942'],
      ['The Lean Startup', 'Eric Ries, 2011'],
      ['The Entrepreneurial State', 'Mariana Mazzucato, 2013'],
      ['Shoe Dog', 'Phil Knight, 2016'],
    ],
  },

  trickster: {
    etym: 'From trick, from Old North French trique, “deceit”. As a name for a type of mythic figure the word was used by the ethnologist Daniel Brinton in the 1860s and fixed by Paul Radin’s The Trickster (1956).',
    def: 'One who meets reality by disrupting it: breaking rules, crossing boundaries and showing, through deception and laughter, that every order was made and could be made otherwise.',
    figure: 'Loki, Coyote, Anansi and Eshu: the one in every mythology who will not keep the rules.',
    overview: [
      'Almost every mythology has a trickster: Hermes in Greece, Loki in Scandinavia, Coyote and Raven in North America, Anansi among the Akan, Eshu among the Yoruba, Sun Wukong the Monkey King in China. They are thieves, liars and shape-shifters, often greedy and foolish, yet frequently credited with gifts to humanity: fire, language, culture itself.',
      'Lewis Hyde argues that the trickster embodies the boundary: a figure of crossroads and thresholds, moving between gods and humans, whose transgressions make change possible. The laughter is not frivolous. A culture that can laugh at its rules can also revise them.',
    ],
    history: [
      'The Homeric Hymn to Hermes, from around the sixth century BC, shows the newborn god stealing Apollo’s cattle and lying his way out of it, then inventing the lyre to make peace. Indigenous American trickster cycles, recorded from the nineteenth century onward, preserve some of the richest examples.',
      'Many societies licensed the trickster for a season: the Roman Saturnalia, when masters served their slaves; the medieval Feast of Fools; the court jester, who could say to a king what no minister dared. Shakespeare’s fools inherit the role.',
      'In modern culture the archetype moved into comedy, satire, hoaxes and hacking. The Situationists and later culture-jammers made disruption a political art; comedians and street artists made it an artistic one.',
    ],
    distinctions: [
      ['Trickster and villain', 'The villain wants to win; the trickster wants to play. The trickster may do harm, but rarely from malice, and is often the butt of their own tricks.'],
      ['Trickster and rebel', 'The rebel opposes an order in the name of something better; the trickster shows that order is arbitrary, without promising anything in its place.'],
    ],
    critique: 'The trickster’s freedom can turn into cruelty or nihilism: the prank that humiliates, the cynicism that believes in nothing. Disinformation, trolling and political chaos-making use the trickster’s tools without the trickster’s function of renewal.',
    now: 'The internet is a trickster’s paradise of memes, hoaxes, parody accounts and anonymous mischief. Telling satire from deception has become a daily problem, and the jester’s licence now belongs, uneasily, to everyone.',
    lineage: [
      [-550, 'c. 6th century BC', 'The Homeric Hymn to Hermes: the god, one day old, steals Apollo’s cattle.'],
      [-217, '217 BC', 'Rome reforms the Saturnalia, the festival when masters serve their slaves.'],
      [1175, 'c. 1175', 'The first branches of the Roman de Renart: Reynard the fox outwits the court.'],
      [1510, 'c. 1510', 'The pranks of Till Eulenspiegel are printed in Strasbourg.'],
      [1592, '1592', 'Journey to the West is printed: Sun Wukong, the Monkey King, storms heaven.'],
      [1601, 'c. 1601', 'Shakespeare gives the wisest lines in Twelfth Night to Feste, the fool.'],
      [1956, '1956', 'Paul Radin’s The Trickster, with a commentary by Jung, is published.'],
      [1957, '1957', 'The Situationist International is founded, making disruption a political art.'],
    ],
    figures: [
      ['Diogenes of Sinope', 'c. 412–323 BC', 'Lived in a jar and mocked the pieties of Athens in public.'],
      ['Nasreddin', '13th century', 'The wise fool of countless Turkish and Persian tales.'],
      ['Till Eulenspiegel', 'legendary, 14th century', 'A prankster who took every instruction literally.'],
      ['Andy Kaufman', '1949–1984', 'A comedian who left audiences unsure what was a joke.'],
    ],
    lexicon: [
      ['Liminal', 'On the threshold, between one state and the next.'],
      ['Carnival', 'The permitted upturning of order.'],
      ['Satire', 'Attack by ridicule.'],
      ['Hack', 'An ingenious misuse.'],
      ['Shape-shifter', 'One who changes form in order to cross a boundary.'],
    ],
    practice: ['Breaks the rule nobody remembers making.', 'Plays the fool in order to say the true thing.', 'Crosses borders.', 'Never stays long.'],
    signs: ['You look for loopholes for fun.', 'Solemn meetings make you want to laugh.', 'You ask the questions people hoped no one would.'],
    reading: [
      ['Pantagruel', 'François Rabelais, 1532'],
      ['Journey to the West', 'attributed to Wu Cheng’en, 1592'],
      ['The Trickster', 'Paul Radin, 1956'],
      ['Rabelais and His World', 'Mikhail Bakhtin, 1965'],
      ['Trickster Makes This World', 'Lewis Hyde, 1998'],
    ],
  },
}
