// Encyclopedia entries, orders I and II: Knowing and Making.
// Lineage entries are [year, as written, what happened]; negative years are BC; c. marks an approximate date.
export default {
  scientist: {
    etym: 'From Latin scientia, “knowledge”, from scire, “to know”. The English word scientist was proposed by William Whewell in 1833 and first printed in 1834, by analogy with artist; until then the scientist was a “natural philosopher”.',
    def: 'One who meets reality by asking how it works, and accepts only answers that can be tested against it, by anyone, again.',
    figure: 'Prometheus, who stole fire from the gods: the light of knowing, and its price.',
    overview: [
      'The scientist’s defining move is not observation, which everyone does, but the controlled comparison: change one thing, hold the rest still, and see what follows. From this discipline come the experiment, the measurement and the statistic, and from them a body of knowledge that does not depend on the authority or the sincerity of whoever found it. A result counts only if a stranger, following the same method, can get it too.',
      'The method is built around the knower’s weakness. Peer review, replication, blinding and pre-registration exist because scientists, like everyone, see what they hope to see. Science is therefore less a set of beliefs than a set of institutions for catching mistakes, and its authority comes from how much error a claim has survived, not from certainty.',
    ],
    history: [
      'Systematic observation is ancient. Babylonian astronomers recorded planetary positions for centuries, and Greek thinkers from Thales to Aristotle looked for natural rather than divine causes. Scholars in Baghdad, Cairo and Oxford added experiment; Ibn al-Haytham’s Book of Optics, completed around 1021, insisted that claims about light and vision be tested with apparatus.',
      'The Scientific Revolution of the sixteenth and seventeenth centuries joined mathematics to experiment. Galileo, Kepler and Newton described motion in equations that predicted as well as explained, and new societies, the Royal Society of London among them (1660), made publication and witnessed demonstration the currency of credit.',
      'The nineteenth century professionalised the role, with laboratories, doctorates, journals and the new word. The twentieth made science large, expensive and consequential, from quantum mechanics and the structure of DNA to nuclear weapons, and gave philosophers a long argument about what exactly the method is.',
    ],
    distinctions: [
      ['Scientist and engineer', 'The scientist wants to know why the bridge stands; the engineer needs it to stand whether or not the theory is complete. Each depends on the other, but one is judged by truth and the other by function.'],
      ['Science and scientism', 'Scientism is the further claim that only what science can measure is real or worth knowing. Most working scientists do not hold it, and it is not itself a scientific result.'],
    ],
    critique: 'Historians such as Thomas Kuhn showed that normal science works inside paradigms it rarely questions; sociologists have shown how funding and prestige steer what gets studied. The replication crisis in psychology and medicine, visible since the early 2010s, showed how incentives can corrupt even a self-correcting system. The strongest answers to these criticisms have usually come from inside science, which is part of its strength.',
    now: 'Contemporary science is collaborative on a scale no individual can survey: thousands of authors on a single particle-physics paper, global climate models, open data. The lone genius is mostly a myth; the scientist today is a member of a very large, argumentative team.',
    lineage: [
      [-585, 'c. 585 BC', 'Thales of Miletus is said to predict a solar eclipse.'],
      [1021, 'c. 1021', 'Ibn al-Haytham completes the Book of Optics, testing theories of vision with experiment.'],
      [1543, '1543', 'Copernicus publishes On the Revolutions of the Heavenly Spheres.'],
      [1660, '1660', 'The Royal Society is founded in London. Its motto: Nullius in verba, take nobody’s word for it.'],
      [1687, '1687', 'Newton’s Principia sets out the laws of motion and universal gravitation.'],
      [1859, '1859', 'Darwin publishes On the Origin of Species.'],
      [1905, '1905', 'Einstein’s miracle year: special relativity, light quanta and Brownian motion.'],
      [1953, '1953', 'Watson and Crick, drawing on Rosalind Franklin’s X-ray data, propose the double helix of DNA.'],
    ],
    figures: [
      ['Ibn al-Haytham', 'c. 965–1040', 'Made experiment the test of optical theory.'],
      ['Galileo Galilei', '1564–1642', 'Turned a telescope on the sky and mathematics on motion.'],
      ['Marie Curie', '1867–1934', 'Discovered polonium and radium; the only person to win Nobel Prizes in two different sciences.'],
      ['Rosalind Franklin', '1920–1958', 'Her X-ray photographs made the structure of DNA visible.'],
    ],
    lexicon: [
      ['Hypothesis', 'A guess that could be shown wrong.'],
      ['Falsifiable', 'Karl Popper’s test (1934): a claim that some possible observation could refute.'],
      ['Control', 'The case in which nothing was changed, kept for comparison.'],
      ['Replication', 'Getting the same result again, independently.'],
      ['Paradigm', 'Kuhn’s word (1962) for the shared framework within which normal science works.'],
    ],
    practice: ['Keeps a dated notebook.', 'Repeats the experiment.', 'Publishes the method with the result.', 'Looks for the error in their own work first.'],
    signs: ['You ask “how do you know?” more often than “what do you think?”', 'You enjoy being proved wrong, eventually.', 'Something in your personal life has a spreadsheet.'],
    reading: [
      ['The Structure of Scientific Revolutions', 'Thomas Kuhn, 1962'],
      ['The Logic of Scientific Discovery', 'Karl Popper, 1934'],
      ['The Beginnings of Western Science', 'David C. Lindberg, 1992'],
      ['Rosalind Franklin: The Dark Lady of DNA', 'Brenda Maddox, 2002'],
      ['Surely You’re Joking, Mr. Feynman!', 'Richard Feynman, 1985'],
    ],
  },

  philosopher: {
    etym: 'From Greek philosophia, “love of wisdom”, from philos, “loving”, and sophia, “wisdom”. Tradition credits Pythagoras with calling himself a philosophos: a lover of wisdom rather than its owner.',
    def: 'One who meets reality by questioning the concepts everyone else uses to describe it: truth, justice, mind, cause, self.',
    figure: 'Socrates, the gadfly of Athens, who said that the unexamined life is not worth living.',
    overview: [
      'Philosophy begins where an ordinary word stops working. Everyone uses “know”, “fair” and “real” with confidence until asked to define them; the philosopher is the one who keeps asking. Its tools are argument, definition, counterexample and the thought experiment, and its product is rarely a final answer. More often it is a clearer question and a map of the positions one could hold.',
      'Historically, philosophy is the mother of the disciplines. Physics was “natural philosophy” until the nineteenth century, and psychology, economics, logic and linguistics each left philosophy once their questions could be answered by other means. What remains are the questions that have not yet found a method, and those that every method presupposes.',
    ],
    history: [
      'Systematic philosophy appears at roughly the same time in several places: in Greece from Thales onward, in China with Confucius and the Daoists, in India with the Upanishads and the Buddhist and Jain schools. Socrates, executed in Athens in 399 BC, set the Western pattern: the relentless question, put to anyone who claims to know.',
      'Plato and Aristotle built systems that shaped the Mediterranean and Islamic worlds for two thousand years, transmitted and transformed by Ibn Sina, Ibn Rushd, Maimonides and Aquinas. Descartes, in 1641, restarted philosophy from doubt; Kant, in 1781, asked what the mind itself contributes to everything it knows.',
      'In the twentieth century Western philosophy divided, roughly, into an analytic tradition focused on logic and language (Frege, Russell, Wittgenstein) and a continental tradition focused on existence, history and interpretation (Husserl, Heidegger, Sartre, Beauvoir). The division is less sharp now than it was.',
    ],
    distinctions: [
      ['Philosopher and sage', 'The sage offers wisdom to be received; the philosopher offers arguments to be checked. A philosopher who asks to be believed rather than followed has become a sage.'],
      ['Philosopher and theologian', 'Both reason about first things, but the theologian starts within a revelation and asks what it means; the philosopher accepts no starting point that cannot itself be questioned.'],
    ],
    critique: 'Philosophy is often accused of making no progress, since its central questions remain open after two and a half thousand years. Its defenders answer that its progress shows up elsewhere, in the sciences it founded and in the confusions it dissolved. The older risk is the one Socrates’ accusers named: a habit of questioning that corrodes trust without building anything in its place.',
    now: 'Philosophers now sit on ethics committees and work on artificial intelligence, consciousness and climate, and in the public argument about what counts as evidence. The oldest question, how to live, has returned through a revival of Stoicism and its many popularisers.',
    lineage: [
      [-500, 'c. 500 BC', 'Confucius teaches in the state of Lu; his sayings are later gathered as the Analects.'],
      [-399, '399 BC', 'Socrates is tried and sentenced to death in Athens.'],
      [-375, 'c. 375 BC', 'Plato writes the Republic, with its allegory of the cave.'],
      [-335, '335 BC', 'Aristotle founds the Lyceum in Athens.'],
      [1180, 'c. 1180', 'Ibn Rushd (Averroes) writes his commentaries on Aristotle in Córdoba.'],
      [1641, '1641', 'Descartes’ Meditations begin from radical doubt.'],
      [1781, '1781', 'Kant’s Critique of Pure Reason asks what the mind brings to all knowing.'],
      [1949, '1949', 'Simone de Beauvoir publishes The Second Sex.'],
    ],
    figures: [
      ['Socrates', 'c. 470–399 BC', 'Wrote nothing; questioned everyone.'],
      ['Zhuangzi', 'c. 369–286 BC', 'Dreamed he was a butterfly, and asked which of them was dreaming.'],
      ['Immanuel Kant', '1724–1804', 'Argued that space, time and cause are forms the mind brings to experience.'],
      ['Simone de Beauvoir', '1908–1986', '“One is not born, but rather becomes, a woman.”'],
    ],
    lexicon: [
      ['Premise', 'What an argument starts from.'],
      ['Ontology', 'The study of what exists.'],
      ['Epistemology', 'The study of how we know.'],
      ['Aporia', 'The puzzlement where an argument runs out.'],
      ['Thought experiment', 'An imagined case that tests a concept, like Plato’s ring of invisibility or Searle’s Chinese room.'],
    ],
    practice: ['Defines the terms before arguing.', 'Looks for the counterexample.', 'States the opposing view better than its holder can.', 'Argues with the dead, in writing.'],
    signs: ['You answer a question with a question.', 'You have argued, seriously, about what counts as a sandwich.', 'You often say: it depends what you mean by…'],
    reading: [
      ['Apology', 'Plato, c. 399 BC'],
      ['The Analects', 'Confucius, compiled 5th–3rd century BC'],
      ['Meditations on First Philosophy', 'René Descartes, 1641'],
      ['The Problems of Philosophy', 'Bertrand Russell, 1912'],
      ['Think', 'Simon Blackburn, 1999'],
    ],
  },

  theologian: {
    etym: 'From Greek theologia, from theos, “god”, and logos, “word, reason, account”. Plato uses the word for stories about the gods; Christian writers later claimed it for reasoned discourse about God.',
    def: 'One who meets reality as having a ground or source, and reasons within a tradition of revelation about what that source is and what it asks.',
    figure: 'Jacob, who wrestled an angel until dawn and would not let go without a blessing.',
    overview: [
      'Theology is distinct from simple belief and from the study of religion. The believer trusts; the scholar of religion describes; the theologian argues from inside a faith, using reason, history and interpretation to understand what that faith claims. Anselm’s phrase for the enterprise, fides quaerens intellectum, “faith seeking understanding”, still describes it.',
      'Every major tradition has developed it: Christian theology from the Church Fathers onward, Islamic kalam, Jewish rabbinic and philosophical thought, Hindu Vedanta, Buddhist scholastic philosophy. The same questions recur across them: the nature of the divine, the problem of evil, the relation of grace to freedom, and how sacred texts should be read.',
    ],
    history: [
      'Theology took its classical form when scriptural traditions met Greek philosophy. Philo of Alexandria read the Hebrew Bible through Plato in the first century; Augustine, around 400, joined Christian faith to Neoplatonism in works that shaped Western thought for a thousand years.',
      'The high Middle Ages were theology’s great systematic age in all three Abrahamic faiths. Al-Ghazali, Maimonides and Thomas Aquinas each weighed Aristotle’s philosophy against revelation, and the medieval universities called theology “the queen of the sciences”.',
      'The Reformation made theology a contest over authority, text and grace; the Enlightenment challenged its foundations; nineteenth-century scholars began to read scripture historically. In the twentieth century Karl Barth, Paul Tillich and Dietrich Bonhoeffer answered war and secularism, and liberation theologians read scripture alongside the poor.',
    ],
    distinctions: [
      ['Theologian and mystic', 'The mystic seeks direct experience of the divine; the theologian seeks to think clearly about it. The traditions keep the two in conversation, and often in mutual suspicion.'],
      ['Theology and philosophy of religion', 'Philosophy of religion examines religious claims from outside any tradition; theology works from within one, accepting its sources as authoritative while interpreting them.'],
    ],
    critique: 'Critics from Hume to the New Atheists argue that theology reasons rigorously from premises it has no right to, and that its conclusions have too often sanctified power and persecution. Theologians have produced some of the sharpest criticism themselves: the apophatic tradition warns that every statement about God says more about the speaker than about God.',
    now: 'Theology is practised today in seminaries and secular universities, in interfaith dialogue and in public arguments about bioethics, ecology and justice. Georges Lemaître, a priest who proposed the expanding universe, is a reminder that the supposed war between science and theology is younger, and less inevitable, than it looks.',
    lineage: [
      [40, 'c. 40', 'Philo of Alexandria interprets the Hebrew Bible through Greek philosophy.'],
      [325, '325', 'The Council of Nicaea defines the Christian creed.'],
      [400, 'c. 400', 'Augustine writes the Confessions, addressed to God.'],
      [1078, '1078', 'Anselm’s Proslogion proposes the ontological argument.'],
      [1095, '1095', 'Al-Ghazali writes The Incoherence of the Philosophers.'],
      [1190, 'c. 1190', 'Maimonides completes The Guide for the Perplexed.'],
      [1265, '1265', 'Thomas Aquinas begins the Summa Theologiae.'],
      [1937, '1937', 'Dietrich Bonhoeffer publishes The Cost of Discipleship; the Nazis execute him in 1945.'],
    ],
    figures: [
      ['Augustine of Hippo', '354–430', 'Made the inner life a subject of theology.'],
      ['Al-Ghazali', 'c. 1058–1111', 'Doubted philosophy, then rebuilt faith on experience.'],
      ['Thomas Aquinas', 'c. 1225–1274', 'Joined Aristotle to Christian doctrine in a single system.'],
      ['Dietrich Bonhoeffer', '1906–1945', 'Asked what faith demands under tyranny, and answered with his life.'],
    ],
    lexicon: [
      ['Revelation', 'What is disclosed, rather than discovered.'],
      ['Exegesis', 'Drawing the meaning out of a text.'],
      ['Apophatic', 'Speaking of God only by what God is not.'],
      ['Theodicy', 'The question of why a good God permits evil: Leibniz’s word, 1710.'],
      ['Grace', 'Favour freely given, not earned.'],
    ],
    practice: ['Reads the old texts in their own languages.', 'Prays and argues, sometimes in the same hour.', 'Keeps the feasts.', 'Takes the strongest objection seriously.'],
    signs: ['You want to know why, not only how.', 'You have read a sacred text more than once.', 'The largest questions feel like home, not vertigo.'],
    reading: [
      ['Confessions', 'Augustine of Hippo, c. 400'],
      ['The Guide for the Perplexed', 'Moses Maimonides, c. 1190'],
      ['I and Thou', 'Martin Buber, 1923'],
      ['The Cost of Discipleship', 'Dietrich Bonhoeffer, 1937'],
      ['A History of God', 'Karen Armstrong, 1993'],
    ],
  },

  detective: {
    etym: 'From detect, from Latin detegere, “to uncover”, from de-, “off”, and tegere, “to cover”. The noun, short for “detective officer”, appears in English in the 1840s, soon after London’s Metropolitan Police formed a detective branch in 1842.',
    def: 'One who meets reality as the trace of a particular past event, and reasons backward from evidence to what happened and who was responsible.',
    figure: 'Oedipus, who solved the Sphinx’s riddle, then his own crime.',
    overview: [
      'The detective’s object is singular. Where the scientist seeks laws that hold everywhere, the detective wants one event, on one night, that will never recur. The reasoning that serves this is what the philosopher C. S. Peirce called abduction: inference to the best explanation, moving from a surprising fact to the hypothesis that would make it unsurprising.',
      'The figure has two lives that feed each other. One is professional: police investigators, private agents, forensic scientists and investigative journalists. The other is literary and enormously popular: the detective story, which turns this reasoning into a game the reader can play, and promises that the world, however dark, is in the end intelligible.',
    ],
    history: [
      'Investigation is as old as law, and puzzle stories as old as literature: Oedipus questions witnesses, and Chinese tradition has told for centuries of judges such as Bao Zheng and Di Renjie who solved crimes. But the professional detective is a creation of the modern city, where strangers are anonymous and crimes must be traced rather than witnessed.',
      'Eugène François Vidocq, a former criminal, founded the Sûreté in Paris in 1812; Scotland Yard formed its detective branch in 1842; Allan Pinkerton’s agency opened in Chicago in 1850. Edgar Allan Poe invented the fictional form in 1841, and Arthur Conan Doyle made it a global habit with Sherlock Holmes from 1887.',
      'In the twentieth century forensic science (fingerprints, blood groups, ballistics and, from 1986, DNA profiling) moved detection toward the laboratory, while fiction divided between the golden-age puzzle of Christie and Sayers and the hard-boiled street of Hammett and Chandler.',
    ],
    distinctions: [
      ['Detective and scientist', 'Both infer from evidence, but the scientist’s claims must be repeatable while the detective’s concern an event that cannot be rerun. The detective must reach a conclusion; the scientist can wait.'],
      ['Detective and judge', 'The detective builds the case; a judge or jury decides whether it is proved. Keeping the two apart is one of the oldest safeguards of justice.'],
    ],
    critique: 'Certainty is the detective’s shadow. Confirmation bias, false confessions and overconfident forensics have produced many wrongful convictions, as DNA exonerations since the 1990s have shown. Critics of the genre add that it teaches readers to see crime as individual wickedness to be found out, rather than as something with social causes.',
    now: 'Open-source investigators now work from satellite images and public videos, and genetic genealogy led to the arrest of the Golden State Killer in 2018. The detective’s method has spread to anyone with a laptop, along with the old danger of naming the wrong person.',
    lineage: [
      [-429, 'c. 429 BC', 'Sophocles’ Oedipus the King: the investigator discovers that he is the culprit.'],
      [1812, '1812', 'Eugène François Vidocq, once a convict, founds the Sûreté in Paris.'],
      [1841, '1841', 'Poe’s The Murders in the Rue Morgue invents the detective story.'],
      [1842, '1842', 'London’s Metropolitan Police forms a detective branch.'],
      [1887, '1887', 'Sherlock Holmes first appears, in A Study in Scarlet.'],
      [1910, '1910', 'Edmond Locard opens a police laboratory in Lyon: every contact leaves a trace.'],
      [1930, '1930', 'Dashiell Hammett’s The Maltese Falcon gives the detective a harder street.'],
      [1986, '1986', 'DNA profiling is first used in a criminal investigation, in Leicestershire.'],
    ],
    figures: [
      ['Eugène François Vidocq', '1775–1857', 'Thief turned head of police; a model for Balzac’s Vautrin.'],
      ['Kate Warne', 'c. 1833–1868', 'The first woman detective at the Pinkerton agency, hired in 1856.'],
      ['Edmond Locard', '1877–1966', 'Founded forensic science on the principle that contact leaves traces.'],
      ['Agatha Christie', '1890–1976', 'Made the puzzle mystery the best-selling fiction in the world.'],
    ],
    lexicon: [
      ['Alibi', 'Proof of having been elsewhere.'],
      ['Motive, means, opportunity', 'The three things a suspect must have had.'],
      ['Red herring', 'A false clue.'],
      ['Exchange principle', 'Locard’s rule: every contact leaves a trace.'],
      ['Abduction', 'Peirce’s term for reasoning to the best explanation.'],
    ],
    practice: ['Writes everything down.', 'Goes back to the scene.', 'Asks the same question twice, differently.', 'Distrusts the first explanation.'],
    signs: ['You notice what has changed in a room.', 'You guess the twist by the halfway point.', 'An inconsistency in a story will not leave you alone.'],
    reading: [
      ['The Murders in the Rue Morgue', 'Edgar Allan Poe, 1841'],
      ['The Moonstone', 'Wilkie Collins, 1868'],
      ['A Study in Scarlet', 'Arthur Conan Doyle, 1887'],
      ['The Simple Art of Murder', 'Raymond Chandler, 1944'],
      ['Forensics', 'Val McDermid, 2014'],
    ],
  },

  engineer: {
    etym: 'From Old French engigneor, “contriver of engines”, from Latin ingenium, “native talent, clever device”, the root of ingenious. The first engineers built siege engines; John Smeaton called himself a “civil engineer” around 1768 to mark those who built for peace.',
    def: 'One who meets reality as a set of constraints, and arranges materials and forces within them so that something works, reliably, for people who need it.',
    figure: 'Daedalus, who built the labyrinth, and the wings his son flew too high on.',
    overview: [
      'Engineering is the disciplined use of knowledge to make things that function: bridges, engines, circuits, software, water supplies. Its characteristic thought is design under constraint. Every real project trades cost against strength, speed against safety and elegance against what can be built with the tools at hand, and the engineer’s judgement lives in those trade-offs.',
      'Engineering knowledge is not simply applied science. Bridges, steam engines and aircraft often worked before theory could explain why, and much of what engineers know lives in rules of thumb, standards, failure reports and tacit skill. The historian Walter Vincenti called it a distinct kind of knowledge, learned by doing and by studying what failed.',
    ],
    history: [
      'The great works of antiquity were engineering without the name: the pyramids of Egypt, the qanats of Persia, Roman aqueducts and roads, the Grand Canal of China. Vitruvius, writing around 25 BC, said that good building must have firmitas, utilitas and venustas: firmness, usefulness and delight.',
      'The Industrial Revolution made the engineer a public hero. Watt’s steam engine, the bridges and railways of Telford and Brunel, and institutions founded to train and certify engineers, the Institution of Civil Engineers in 1818 among the first, turned a craft into a profession.',
      'The twentieth century added electrical, chemical, aeronautical and software engineering, and disasters that reshaped the discipline, from the collapse of the Tacoma Narrows Bridge in 1940 to the loss of the shuttle Challenger in 1986. An engineer’s duty to the public who will cross the bridge became part of engineering education.',
    ],
    distinctions: [
      ['Engineer and scientist', 'The scientist asks whether something is true; the engineer asks whether it will hold. The engineer can act on a theory known to be incomplete, if the margins are wide enough.'],
      ['Engineer and craftsman', 'The craftsman makes by trained hand and eye, one piece at a time; the engineer designs by calculation, often for things built by others and at scale.'],
    ],
    critique: 'Engineering’s shadow is the ability to build without asking whether one should. Lewis Mumford and Langdon Winner argued that technologies carry politics, shaping who holds power long after their engineers have gone. The answer has been to bring ethics, users and the public into design, with mixed success.',
    now: 'Most engineering is now invisible: code, standards, supply chains, power grids. Its frontier problems, from decarbonising energy to making artificial intelligence reliable, are as much about systems and people as about materials.',
    lineage: [
      [-2650, 'c. 2650 BC', 'Imhotep designs the step pyramid of Djoser at Saqqara.'],
      [-312, '312 BC', 'Rome builds its first aqueduct, the Aqua Appia.'],
      [-25, 'c. 25 BC', 'Vitruvius writes On Architecture: firmness, usefulness and delight.'],
      [1436, '1436', 'Brunelleschi’s dome over Florence cathedral is completed without wooden centring.'],
      [1769, '1769', 'James Watt patents the separate condenser for the steam engine.'],
      [1883, '1883', 'The Brooklyn Bridge opens, the longest suspension span of its day.'],
      [1940, '1940', 'The Tacoma Narrows Bridge twists apart in the wind, four months after it opened.'],
      [1969, '1969', 'Apollo 11 lands on the Moon and returns.'],
    ],
    figures: [
      ['Imhotep', '27th century BC', 'Architect of the first great stone monument.'],
      ['Al-Jazari', '1136–1206', 'Described automata and water-raising machines in his Book of Ingenious Devices.'],
      ['Isambard Kingdom Brunel', '1806–1859', 'Railways, tunnels, bridges and the largest ships of his age.'],
      ['Margaret Hamilton', 'b. 1936', 'Led the software engineering for Apollo’s on-board flight computers.'],
    ],
    lexicon: [
      ['Tolerance', 'How far a part may differ from its drawing.'],
      ['Factor of safety', 'Strength held in reserve beyond the expected load.'],
      ['Failure mode', 'The particular way a thing breaks.'],
      ['Iteration', 'Build, test, change; again.'],
      ['Redundancy', 'A second system ready when the first one fails.'],
    ],
    practice: ['Calculates the load before drawing the beam.', 'Builds a prototype in order to break it.', 'Adds a factor of safety.', 'Writes down why each decision was made.'],
    signs: ['You take things apart before reading the instructions.', 'You answer “it depends on the requirements”.', 'Broken things in your home get fixed, and sometimes improved.'],
    reading: [
      ['The Ten Books on Architecture', 'Vitruvius, c. 25 BC'],
      ['To Engineer Is Human', 'Henry Petroski, 1985'],
      ['The Design of Everyday Things', 'Don Norman, 1988'],
      ['What Engineers Know and How They Know It', 'Walter Vincenti, 1990'],
      ['The Soul of a New Machine', 'Tracy Kidder, 1981'],
    ],
  },

  artist: {
    etym: 'From Medieval Latin artista, from ars, “skill, craft”. Until the Renaissance an artist was anyone skilled in an art, including the liberal arts; the modern sense, a maker of works valued for their own sake, settled only in the eighteenth century.',
    def: 'One who meets reality by making forms (images, objects, performances) that add something to the world and change how the rest of it is seen.',
    figure: 'Pygmalion, whose statue was made so well that it came alive.',
    overview: [
      'Art does two things at once: it makes an object, and it makes a way of seeing. A Rembrandt portrait is a painted surface, and it is also a training in attention to old faces. The artist’s distinctive knowledge lives in the hand and the eye as much as the head, and it is acquired as crafts are, by long practice.',
      'What counts as art has changed more than almost any other category in this atlas. For most of history art served religion, power and use; the Renaissance raised the artist from artisan toward genius; modernism made the questioning of art itself a subject for art. Duchamp’s Fountain (1917) is the emblem: a work whose content is the question of what a work is.',
    ],
    history: [
      'The oldest known figurative paintings, on cave walls in Sulawesi and at Chauvet in France, are tens of thousands of years old, so image-making is as old as anything distinctively human. In Egypt, Greece and China, artists were mostly anonymous craftsmen working within strong conventions.',
      'Renaissance Italy, and Giorgio Vasari’s Lives of the Artists (1550), created the artist as an individual genius with a biography. The academies of the seventeenth and eighteenth centuries codified the rules; the Romantics and then the avant-gardes broke them.',
      'Since the nineteenth century artists have often defined themselves against the market and the public while depending on both: the Salon des Refusés of 1863, the Impressionists’ independent exhibitions, the manifestos of Futurism and Surrealism, and a market that now prices some living artists in the tens of millions.',
    ],
    distinctions: [
      ['Artist and artisan', 'The artisan makes useful things well, to a pattern; the artist makes things whose use, if any, is to be looked at, heard or thought about. The line was drawn late, and many traditions never drew it.'],
      ['Art and entertainment', 'Entertainment gives an audience what it expects; art, at least in the modern sense, tends to change what it expects. Most works do some of both.'],
    ],
    critique: 'The cult of the artist has been criticised for excusing cruelty in the name of genius, for erasing the collective and anonymous labour behind most art, and, as John Berger argued in Ways of Seeing, for serving the property and vanity of the rich. The artist’s own risk is the reverse: becoming so occupied with how things look that one stops seeing them.',
    now: 'Artists now work in every medium, including code, data and their own bodies, and are asking what images mean when machines can generate them without limit. The older question, why make anything at all, is as live as ever.',
    lineage: [
      [-43500, 'c. 43,500 BC', 'A wild pig is painted on a cave wall on Sulawesi, among the oldest figurative images known.'],
      [-34000, 'c. 34,000 BC', 'Horses, lions and rhinoceroses are painted in the Chauvet cave.'],
      [1503, '1503', 'Leonardo begins the portrait now called the Mona Lisa.'],
      [1550, '1550', 'Vasari’s Lives of the Artists makes the artist a hero with a biography.'],
      [1863, '1863', 'The Salon des Refusés shows the paintings the official Salon rejected.'],
      [1872, '1872', 'Monet paints Impression, Sunrise, and gives a movement its name.'],
      [1917, '1917', 'Duchamp submits a urinal, signed R. Mutt, as Fountain.'],
      [1962, '1962', 'Warhol shows thirty-two paintings of Campbell’s soup cans in Los Angeles.'],
    ],
    figures: [
      ['Leonardo da Vinci', '1452–1519', 'Drew in order to understand.'],
      ['Katsushika Hokusai', '1760–1849', 'Made Thirty-six Views of Mount Fuji when he was past seventy.'],
      ['Frida Kahlo', '1907–1954', 'Made her own body and pain a public subject.'],
      ['Marcel Duchamp', '1887–1968', 'Turned the question of what counts as art into art.'],
    ],
    lexicon: [
      ['Composition', 'Where everything is, and why.'],
      ['Medium', 'What the work is made of.'],
      ['Gesture', 'A mark that keeps the movement of the hand.'],
      ['Negative space', 'The shape of what was left empty.'],
      ['Readymade', 'Duchamp’s term for an ordinary object chosen and presented as art.'],
    ],
    practice: ['Works every day, inspired or not.', 'Keeps a sketchbook.', 'Copies the masters, and then stops.', 'Finishes things.'],
    signs: ['You notice the colour before the name.', 'You cannot walk past a beautiful thing.', 'Your notebooks hold more drawings than words.'],
    reading: [
      ['Lives of the Most Excellent Painters, Sculptors and Architects', 'Giorgio Vasari, 1550'],
      ['Letters to a Young Poet', 'Rainer Maria Rilke, 1929'],
      ['The Story of Art', 'E. H. Gombrich, 1950'],
      ['Ways of Seeing', 'John Berger, 1972'],
      ['The Gift', 'Lewis Hyde, 1983'],
    ],
  },

  musician: {
    etym: 'From Latin musica, from Greek mousikē technē, “the art of the Muses”, which for the Greeks included poetry and dance as well as sound.',
    def: 'One who meets reality as sound organised in time, and makes, performs or listens to music as a way of knowing and feeling the world.',
    figure: 'Orpheus, whose lyre moved stones and nearly brought the dead back.',
    overview: [
      'Music is the most abstract of the arts and among the most bodily. It depicts almost nothing, yet it moves people more directly than any picture: it changes heart rate, synchronises groups and fixes memories. Every known human culture makes it, which suggests that music is not an ornament of human life but part of its equipment.',
      'The musician combines three roles that literate cultures often separate: composer, performer and listener. In much of the world’s music they remain one, in improvisation, oral tradition and communal singing. Notation made it possible to separate them, and to build works too large and complex for any single memory.',
    ],
    history: [
      'Flutes of bird bone and mammoth ivory from caves in southern Germany are around forty thousand years old. The oldest notated melody known, the Hurrian Hymn from Ugarit, dates from about 1400 BC, and Pythagoras is credited with finding that consonant intervals correspond to simple ratios of string length.',
      'Medieval singers developed staff notation; Guido of Arezzo, around 1025, gave them the lines and syllables that became do-re-mi. Polyphony, tonal harmony, the public concert and the symphony followed in Europe, while other traditions built equally sophisticated systems: the Indian raga, the Arabic maqam, the Javanese gamelan.',
      'Recording, from Edison’s phonograph in 1877, changed music more than anything since notation. It made performances repeatable, created a global market and made possible genres such as jazz, rock and hip-hop that live chiefly on record. Streaming has since put almost all recorded music within reach of almost everyone, and made a living from it harder.',
    ],
    distinctions: [
      ['Musician and composer', 'The composer fixes music to be performed by others; the performer brings it into sound. In jazz, folk and most of the world’s music they are the same person.'],
      ['Sound and music', 'Music is sound organised by pattern: pitch, rhythm, repetition. John Cage tested the boundary with 4′33″ (1952), in which the audience’s own noise becomes the piece.'],
    ],
    critique: 'Philosophers have distrusted music since Plato, who thought certain modes made citizens soft or wild, and it has been used for propaganda, ritual and even interrogation. The musician’s private shadow is perfectionism, a life practised rather than lived, in an industry that rewards very few.',
    now: 'More music is made and heard now than at any time in history, by more people, with tools that once filled a studio. The open questions are about attention, payment, and what machine-generated music will mean for the people who make it.',
    lineage: [
      [-38000, 'c. 38,000 BC', 'A flute is carved from a vulture’s wing bone at Hohle Fels, in Germany.'],
      [-1400, 'c. 1400 BC', 'The Hurrian Hymn is written on a clay tablet at Ugarit: the oldest notated melody known.'],
      [-530, 'c. 530 BC', 'Pythagoras, by tradition, links musical intervals to whole-number ratios.'],
      [1025, 'c. 1025', 'Guido of Arezzo teaches singers with lines and spaces: the staff.'],
      [1722, '1722', 'Bach completes the first book of The Well-Tempered Clavier.'],
      [1824, '1824', 'Beethoven’s Ninth Symphony is first performed in Vienna; its composer is profoundly deaf.'],
      [1877, '1877', 'Edison records a voice on tinfoil and plays it back.'],
      [1952, '1952', 'John Cage’s 4′33″: four minutes and thirty-three seconds without a played note.'],
    ],
    figures: [
      ['Hildegard of Bingen', '1098–1179', 'Abbess, visionary and composer.'],
      ['Johann Sebastian Bach', '1685–1750', 'Brought counterpoint to a summit.'],
      ['Ravi Shankar', '1920–2012', 'Carried Hindustani classical music to a world audience.'],
      ['Nina Simone', '1933–2003', 'Trained as a classical pianist; made music a voice of the civil rights movement.'],
    ],
    lexicon: [
      ['Interval', 'The distance between two notes.'],
      ['Tempo', 'The speed of the beat.'],
      ['Timbre', 'The colour of a sound.'],
      ['Pentatonic', 'A five-note scale found all over the world.'],
      ['Counterpoint', 'Two or more independent melodies sounding together.'],
    ],
    practice: ['Plays scales daily.', 'Listens more than plays.', 'Learns by ear.', 'Practises the hard bar slowly.'],
    signs: ['You tap rhythms on tables.', 'A song can change your mood within eight bars.', 'You hear the bass line first.'],
    reading: [
      ['Silence', 'John Cage, 1961'],
      ['This Is Your Brain on Music', 'Daniel Levitin, 2006'],
      ['The Rest Is Noise', 'Alex Ross, 2007'],
      ['Musicophilia', 'Oliver Sacks, 2007'],
      ['How Music Works', 'David Byrne, 2012'],
    ],
  },

  storyteller: {
    etym: 'Story comes through Anglo-French estorie from Latin historia, “inquiry, account”, from Greek. For centuries story and history were a single word.',
    def: 'One who meets reality by giving events a shape (beginning, trouble, turn and end) so that they can be remembered, shared and made to mean something.',
    figure: 'Scheherazade, who told a story every night for a thousand and one nights, to stay alive.',
    overview: [
      'Narrative may be the oldest technology of knowledge. Before writing, genealogy, law, navigation and cosmology were carried in stories that could be memorised and retold. Psychologists find that people remember information far better when it is set in a story, and that we spontaneously narrate our own lives in order to understand them.',
      'The storyteller’s essential act is selection. Of all the things that happened, a story keeps a few, puts them in order and implies that the order matters: this happened because of that. That is its power and its danger. A story explains, and in explaining it can make the accidental look inevitable.',
    ],
    history: [
      'Oral epics such as Gilgamesh, the Iliad and the Mahabharata were composed and passed on by performers who recombined traditional formulas. Milman Parry and Albert Lord, recording singers in Yugoslavia in the 1930s, showed how a poet could perform thousands of lines without writing by improvising within such a system.',
      'Writing fixed stories and changed them. Frame tales, from the Thousand and One Nights to Boccaccio’s Decameron and Chaucer’s Canterbury Tales, gathered stories inside stories; the novel, from Murasaki’s Tale of Genji and Cervantes’ Don Quixote onward, followed inner lives through ordinary time.',
      'Theorists have looked for the shapes beneath stories: Aristotle’s beginning, middle and end; Gustav Freytag’s pyramid (1863); Vladimir Propp’s thirty-one functions of the Russian folktale (1928); Joseph Campbell’s monomyth (1949). Each captures something and leaves much out.',
    ],
    distinctions: [
      ['Story and plot', 'E. M. Forster’s distinction (1927): “The king died and then the queen died” is a story; “the king died, and then the queen died of grief” is a plot. Plot adds cause.'],
      ['Storyteller and historian', 'Both narrate the past, but the historian is bound by evidence and must say what is not known; the storyteller is bound by meaning, and may invent what the story needs.'],
    ],
    critique: 'Our appetite for causes and arcs leads us to see coherence where there was chance, and to trust a good story over good evidence; Nassim Taleb called it the narrative fallacy. Propaganda, conspiracy theories and advertising all exploit it. The philosopher Galen Strawson has argued that many people do not experience their lives as a story at all, and need not.',
    now: 'Stories now arrive as series, games, podcasts and feeds, and are increasingly shaped by data on what keeps an audience watching. The oldest skill, holding attention with a voice, has never been more valuable or more industrialised.',
    lineage: [
      [-2100, 'c. 2100 BC', 'The first poems of Gilgamesh are written down in Sumer.'],
      [-750, 'c. 750 BC', 'The Iliad and the Odyssey take roughly the form we know.'],
      [400, 'c. 400', 'The Mahabharata, the longest epic poem, reaches roughly its present form.'],
      [1010, 'c. 1010', 'Murasaki Shikibu writes The Tale of Genji at the Heian court.'],
      [1353, 'c. 1353', 'Boccaccio’s Decameron: ten young people, a hundred stories, a plague outside.'],
      [1605, '1605', 'Cervantes publishes the first part of Don Quixote.'],
      [1863, '1863', 'Gustav Freytag draws the five-part pyramid of dramatic structure.'],
      [1928, '1928', 'Vladimir Propp maps the thirty-one functions of the Russian folktale.'],
    ],
    figures: [
      ['Homer', 'c. 8th century BC', 'The name tradition gives to the poet of the Iliad and the Odyssey.'],
      ['Murasaki Shikibu', 'c. 973–c. 1014', 'Wrote The Tale of Genji, often called the first novel.'],
      ['Hans Christian Andersen', '1805–1875', 'Wrote new fairy tales that read like old ones.'],
      ['Chinua Achebe', '1930–2013', 'Told the colonial encounter from the other side, in Things Fall Apart.'],
    ],
    lexicon: [
      ['Plot', 'Events in an order that means something.'],
      ['Narrator', 'Who tells, and how much they know.'],
      ['Arc', 'How a character changes.'],
      ['In medias res', 'Starting in the middle of things: Horace’s advice.'],
      ['Frame tale', 'A story that contains other stories, like the Thousand and One Nights.'],
    ],
    practice: ['Listens for the detail that makes it true.', 'Starts in the middle.', 'Cuts the beginning.', 'Tells it aloud before writing it down.'],
    signs: ['You remember people by their stories.', 'You exaggerate slightly, for effect.', 'You cannot leave a book unfinished.'],
    reading: [
      ['One Thousand and One Nights', 'from the 9th century'],
      ['Aspects of the Novel', 'E. M. Forster, 1927'],
      ['Morphology of the Folktale', 'Vladimir Propp, 1928'],
      ['The Storyteller', 'Walter Benjamin, 1936'],
      ['The Hero with a Thousand Faces', 'Joseph Campbell, 1949'],
    ],
  },
}
