// Encyclopedia entries, orders V and VI: Beholding and Tending.
export default {
  explorer: {
    etym: 'From Latin explorare, “to search out”. Ancient grammarians derived it from ex-, “out”, and plorare, “to cry aloud”, perhaps the hunter’s shout when game was found; the etymology is uncertain, but the sense of going out to find has been constant.',
    def: 'One who meets reality by going to it, crossing into places and conditions not yet known to them, and coming back with first-hand knowledge.',
    figure: 'Odysseus, ten years finding the way home, and Gilgamesh at the edge of the world.',
    overview: [
      'Exploration combines curiosity, endurance and logistics. The romantic image is of a lone figure at the edge of the map, but nearly every expedition depended on local guides, porters and knowledge: Tenzing Norgay on Everest, Inuit clothing and dogs on the polar journeys, the Tahitian navigator Tupaia aboard Cook’s Endeavour. Discovery has usually meant that people already living somewhere met someone new.',
      'The explorer’s knowledge is testimony: I was there. Before photography and satellites, the traveller’s report was the only evidence of distant places, which is why travel writing so often mixed observation with invention, and why an explorer’s credibility mattered so much.',
    ],
    history: [
      'The greatest feats of pre-modern exploration were Polynesian. Voyagers without instruments settled the Pacific over some three thousand years, reaching Hawai‘i, Rapa Nui and finally Aotearoa New Zealand around AD 1250. Arab, Indian and Chinese sailors linked the Indian Ocean; Ibn Battuta travelled some 120,000 kilometres in the fourteenth century, and Zheng He’s fleets reached East Africa in the 1410s.',
      'European voyages from the fifteenth century joined the world’s oceans into one system, at a terrible cost to the peoples encountered: conquest, slavery and epidemic followed. The scientific expeditions of the eighteenth and nineteenth centuries, Cook’s and Humboldt’s among them, joined exploration to natural history.',
      'The polar and mountain expeditions of the early twentieth century were the last great journeys to blank places on the map of the land. Exploration then turned to the deep sea, much of whose floor is still mapped only coarsely, and to space.',
    ],
    distinctions: [
      ['Explorer and tourist', 'The tourist goes where others have arranged the way; the explorer goes where the way has to be found. Most travel lies somewhere between.'],
      ['Discovery and encounter', 'From the side of the places “discovered”, exploration was an encounter, and often an invasion. Historians now usually prefer the second word.'],
    ],
    critique: 'The explorer was often the advance guard of empire, and exploration narratives long erased the guides and inhabitants who made the journeys possible. Adventure can also become a product: queues on Everest, extreme tourism, the explorer as brand. The archetype’s private risk is restlessness, the inability to stay anywhere long enough to know it.',
    now: 'Explorers now map the deep ocean, caves, the genome and the surfaces of other planets, mostly through instruments. The older figure, the one who goes in person, survives in astronauts, cave divers and the few who still cross unmapped ground.',
    lineage: [
      [-800, 'c. 800 BC', 'Lapita voyagers settle Tonga and Samoa across open Pacific water.'],
      [1250, 'c. 1250', 'Polynesian voyagers reach Aotearoa New Zealand, the last large land to be settled.'],
      [1325, '1325', 'Ibn Battuta leaves Tangier; he will travel for nearly thirty years.'],
      [1418, 'c. 1418', 'Zheng He’s fleet reaches the coast of East Africa.'],
      [1522, '1522', 'The survivors of Magellan’s fleet, under Elcano, complete the first circumnavigation.'],
      [1799, '1799', 'Alexander von Humboldt sets out for the Americas, making exploration a science.'],
      [1911, '1911', 'Roald Amundsen’s party reaches the South Pole.'],
      [1953, '1953', 'Tenzing Norgay and Edmund Hillary stand on the summit of Everest.'],
    ],
    figures: [
      ['Ibn Battuta', '1304–c. 1369', 'Travelled for three decades from Morocco to China.'],
      ['Zheng He', '1371–1433', 'Admiral of seven Ming voyages across the Indian Ocean.'],
      ['Alexander von Humboldt', '1769–1859', 'Saw nature as one interconnected system.'],
      ['Tenzing Norgay', '1914–1986', 'Sherpa mountaineer who reached the summit of Everest in 1953.'],
    ],
    lexicon: [
      ['Dead reckoning', 'Finding your place from speed, heading and time.'],
      ['Terra incognita', 'Land not yet on the map.'],
      ['Base camp', 'The last fixed point.'],
      ['Bearing', 'The direction to go, in degrees.'],
      ['Wayfinding', 'Navigation by stars, swells and birds, as Polynesian navigators practised it.'],
    ],
    practice: ['Packs light and plans heavily.', 'Keeps a log.', 'Learns the local names for things.', 'Turns back when the weather says so.'],
    signs: ['You take the unmarked path.', 'The second visit bores you.', 'You keep a list of places, and it keeps growing.'],
    reading: [
      ['The Rihla (Travels)', 'Ibn Battuta, 1355'],
      ['South', 'Ernest Shackleton, 1919'],
      ['The Worst Journey in the World', 'Apsley Cherry-Garrard, 1922'],
      ['We, the Navigators', 'David Lewis, 1972'],
      ['The Invention of Nature', 'Andrea Wulf, 2015'],
    ],
  },

  hedonist: {
    etym: 'From Greek hēdonē, “pleasure”. The Cyrenaics of the fourth century BC were the first philosophical hedonists; the English word hedonism is a nineteenth-century coinage.',
    def: 'One who meets reality through pleasure, holding that what feels good, rightly understood, is the measure of a good life.',
    figure: 'Dionysus, god of wine, theatre and the night that will not end.',
    overview: [
      'Philosophical hedonism is more austere than its reputation. The Cyrenaics, followers of Aristippus, prized the pleasure of the moment; but Epicurus, the most influential hedonist, defined pleasure chiefly as the absence of pain in the body and of disturbance in the mind (ataraxia), and recommended simple food, friendship and freedom from fear of death and the gods.',
      'Hedonism survives in two forms. Psychological hedonism says that people always act to gain pleasure or avoid pain; ethical hedonism says that they should. Bentham and Mill built an ethics on the second: the right act is the one that produces the greatest happiness. The everyday hedonist simply takes enjoyment seriously, as a skill to be cultivated rather than an accident.',
    ],
    history: [
      'Aristippus of Cyrene, a pupil of Socrates, taught that present pleasure is the good. Epicurus opened his school, the Garden, in Athens around 306 BC; his followers spread across the Mediterranean, and Lucretius set the philosophy in Latin verse in On the Nature of Things.',
      'For over a thousand years Christian moralists treated Epicureanism as a byword for godless indulgence. The rediscovery of Lucretius’ poem in 1417 helped revive it in the Renaissance; Montaigne, Gassendi and the libertines defended pleasure and nature against asceticism.',
      'Bentham (1789) proposed a calculus of pleasure and pain; Mill (1863) distinguished higher pleasures from lower. Gastronomy became literature with Brillat-Savarin (1825), and twentieth-century movements from Slow Food to positive psychology took up the question of how to enjoy well.',
    ],
    distinctions: [
      ['Hedonist and glutton', 'The glutton wants more; the hedonist wants better. Epicurus thought excess bad strategy, because it produces pain.'],
      ['Pleasure and happiness', 'Pleasure is a feeling; happiness in Aristotle’s sense, eudaimonia, is a life going well. Hedonists identify them; most other traditions do not.'],
    ],
    critique: 'The psychologists Brickman and Campbell described the hedonic treadmill in 1971: pleasures fade as we adapt, so pursuing them directly defeats itself. Robert Nozick’s experience machine (1974) asked whether anyone would plug into a device that guaranteed perfect pleasure; most people say no, which suggests we want more than feelings. The archetype’s best answer is to savour rather than accumulate.',
    now: 'Consumer culture promises pleasure everywhere and often delivers distraction, and many technologies are designed around the treadmill. The hedonist’s ancient discipline, choosing pleasures carefully and giving them full attention, has become a kind of resistance.',
    lineage: [
      [-400, 'c. 400 BC', 'Aristippus of Cyrene teaches that the pleasure of the moment is the good.'],
      [-306, 'c. 306 BC', 'Epicurus opens his school in a garden outside Athens.'],
      [-55, 'c. 55 BC', 'Lucretius writes On the Nature of Things, Epicureanism in verse.'],
      [1417, '1417', 'Poggio Bracciolini rediscovers Lucretius’ poem in a German monastery.'],
      [1789, '1789', 'Bentham proposes to measure right action in pleasure and pain.'],
      [1825, '1825', 'Brillat-Savarin publishes The Physiology of Taste.'],
      [1863, '1863', 'Mill’s Utilitarianism separates higher pleasures from lower ones.'],
      [1986, '1986', 'The Slow Food movement begins in Italy, in protest at a fast-food restaurant in Rome.'],
    ],
    figures: [
      ['Epicurus', '341–270 BC', 'Taught that a pleasant life is a simple, unafraid one among friends.'],
      ['Lucretius', 'c. 99–55 BC', 'Set Epicurus’ philosophy in Latin verse.'],
      ['Michel de Montaigne', '1533–1592', 'Wrote essays in praise of the body and its pleasures.'],
      ['M. F. K. Fisher', '1908–1992', 'Wrote about eating as a way of living.'],
    ],
    lexicon: [
      ['Ataraxia', 'Epicurus’ calm: freedom from disturbance.'],
      ['Savour', 'To make a pleasure last by attending to it.'],
      ['Hedonic treadmill', 'The return to baseline after every gain.'],
      ['Carpe diem', 'Seize the day: Horace, Odes 1.11.'],
      ['Eudaimonia', 'Aristotle’s word for flourishing: a life going well, not only feeling good.'],
    ],
    practice: ['Eats slowly.', 'Keeps afternoons free.', 'Accepts the invitation.', 'Notices when pleasure stops being pleasure.'],
    signs: ['You remember trips by their meals.', 'You own good sheets.', 'A long lunch seems to you time well spent.'],
    reading: [
      ['Letter to Menoeceus', 'Epicurus, c. 300 BC'],
      ['On the Nature of Things', 'Lucretius, c. 55 BC'],
      ['The Physiology of Taste', 'Jean Anthelme Brillat-Savarin, 1825'],
      ['A Moveable Feast', 'Ernest Hemingway, 1964'],
      ['The Swerve', 'Stephen Greenblatt, 2011'],
    ],
  },

  cinephile: {
    etym: 'From French cinéphile, from cinéma, short for cinématographe, “motion-writing”, the name of the Lumière brothers’ machine, and Greek philos, “loving”. The word was current in French film culture by the 1920s.',
    def: 'One who meets reality through the moving image, watching with an attention that treats cinema as an art, a history and a way of seeing the world.',
    figure: 'The prisoners in Plato’s cave, who watch shadows on a wall; here, by choice.',
    overview: [
      'Cinephilia is love of cinema as cinema: not only of stories told on film but of the medium’s own means, which are framing, editing, duration, light and movement. The cinephile watches the cut as well as the character and remembers who held the camera. For many it is also a social practice: the film club, the festival, the argument after the screening.',
      'Film theory has given cinephiles two great poles. André Bazin praised the long take and deep focus, which preserve the ambiguity of the real; Sergei Eisenstein praised montage, the collision of shots that creates a meaning neither shot contains. Most films, and most viewers, live between the two.',
    ],
    history: [
      'Cinema began as a fairground novelty; the Lumières’ first public paid screening was in Paris on 28 December 1895. Within thirty years film had avant-gardes, theories and critics, from Soviet montage to German Expressionism, and soon archives: the Cinémathèque française, co-founded by Henri Langlois in 1936, became the school of a generation.',
      'Post-war French cinephilia, gathered around Cahiers du cinéma (1951), championed the auteur theory, treating Hitchcock and Hawks as artists rather than entertainers. Its critics became the directors of the New Wave: Truffaut, Godard, Rohmer, Chabrol and Rivette.',
      'Television, video, DVD and streaming each changed cinephilia, making films ownable and searchable while threatening the shared experience of the dark room. Susan Sontag mourned “the decay of cinema” in 1996; others see a new, global and online cinephilia with more access to more films than ever.',
    ],
    distinctions: [
      ['Cinephile and fan', 'The fan loves particular films, stars or franchises; the cinephile loves the medium and its history, and will watch a difficult film for what it does with time or light.'],
      ['Film and cinema', 'A film is a work; cinema is also a place and a ritual, the shared dark room. Many cinephiles insist the second is part of the first.'],
    ],
    critique: 'Cinephilia has been accused of elitism and of a canon dominated by Western men; recent criticism has widened it to women directors and to Asian, African and Latin American cinema. The archetype’s own shadow is spectatorship replacing life: the street seen only as a location.',
    now: 'Streaming has made the archive enormous and the screen small. Cinephiles today often watch alone, write in public, and campaign for repertory cinemas and restoration as forms of preservation.',
    lineage: [
      [1895, '1895', 'The Lumière brothers show ten short films to a paying audience in Paris.'],
      [1925, '1925', 'Eisenstein’s Battleship Potemkin turns editing into argument.'],
      [1936, '1936', 'Henri Langlois co-founds the Cinémathèque française.'],
      [1946, '1946', 'The first Cannes Film Festival is held.'],
      [1951, '1951', 'André Bazin and others found Cahiers du cinéma.'],
      [1959, '1959', 'Truffaut’s The 400 Blows opens the French New Wave.'],
      [1966, '1966', 'Truffaut publishes his book-length interview with Hitchcock.'],
      [1996, '1996', 'Susan Sontag’s essay “The Decay of Cinema” mourns the end of cinephilia.'],
    ],
    figures: [
      ['André Bazin', '1918–1958', 'Critic who argued that film’s power lies in its bond with reality.'],
      ['Henri Langlois', '1914–1977', 'Archivist who saved thousands of films and taught a generation by showing them.'],
      ['Satyajit Ray', '1921–1992', 'Co-founded a film society in Calcutta, then became one of cinema’s great directors.'],
      ['Agnès Varda', '1928–2019', 'A founding figure of the New Wave, who called her method “cinécriture”.'],
    ],
    lexicon: [
      ['Mise-en-scène', 'Everything placed before the camera.'],
      ['Montage', 'Meaning made by joining shots.'],
      ['Long take', 'A shot that refuses to cut.'],
      ['Auteur', 'The director as the author of the film.'],
      ['Diegesis', 'The world of the story: diegetic sound is heard by the characters; a score is not.'],
    ],
    practice: ['Watches a film twice: once for the story, once for the cuts.', 'Sits in the front third.', 'Keeps a diary of everything seen.', 'Stays for the credits.'],
    signs: ['You know who shot it, not only who starred in it.', 'You notice the aspect ratio.', 'You have a film for every mood, and views on subtitles.'],
    reading: [
      ['Film Form', 'Sergei Eisenstein, 1949'],
      ['What Is Cinema?', 'André Bazin, 1958–62'],
      ['Hitchcock/Truffaut', 'François Truffaut, 1966'],
      ['Sculpting in Time', 'Andrei Tarkovsky, 1986'],
      ['The Decay of Cinema', 'Susan Sontag, 1996'],
    ],
  },

  archivist: {
    etym: 'From archive, from Greek archeion, “public office, the magistrates’ residence”, from archē, “government, beginning”. The archive was first the place where the records of authority were kept.',
    def: 'One who meets reality as what must not be lost, and preserves, arranges and describes the records of the past so that others can find and question them.',
    figure: 'Mnemosyne, goddess of memory and mother of the nine Muses.',
    overview: [
      'Archives differ from libraries. A library collects published works chosen for their content; an archive keeps the records an organisation or a person produced in the course of living, kept together as evidence. The archivist’s principles follow from this: provenance (keep records according to who made them) and original order (keep them as they were kept), so that context survives with content.',
      'Archivists decide what survives. Since most records cannot be kept, appraisal, the choice of what to preserve, is the profession’s most consequential act. The historian’s past is largely the archivist’s selection, and its gaps (the poor, the colonised, women, the illiterate) are often gaps in what anyone thought worth keeping.',
    ],
    history: [
      'Archives are as old as writing, which was invented largely for record-keeping. The palace archive of Ebla in Syria held thousands of clay tablets around 2350 BC; Ashurbanipal’s library at Nineveh, in the seventh century BC, mixed archive and library; the Library of Alexandria aimed to hold everything written in Greek.',
      'Modern archival science began in the nineteenth century. Revolutionary France created the Archives nationales in 1790 and opened public records to citizens; the principle of respect des fonds was laid down in France in 1841; a Dutch manual of 1898 made provenance the basis of the profession.',
      'The twentieth century made archives both more powerful and more endangered: surveillance archives such as the Stasi files, opened to the people they watched in 1992; libraries destroyed in war, from Louvain in 1914 to Sarajevo in 1992; and digital records whose formats age within a decade.',
    ],
    distinctions: [
      ['Archive and library', 'A library collects books for what they say; an archive keeps records as evidence of the activity that produced them. A letter in a library is a text; in an archive it is a trace.'],
      ['Archivist and hoarder', 'The hoarder keeps everything and can find nothing; the archivist chooses, describes and arranges, so that what is kept can be used.'],
    ],
    critique: 'Derrida’s Archive Fever (1995) and postcolonial historians such as Michel-Rolph Trouillot stressed that archives are instruments of power: they record what states and institutions wanted known and silence the rest. Archivists now work to document communities that were left out, and historians read existing archives “against the grain”.',
    now: 'Most records are now born digital, and much of the web disappears within years. The Internet Archive, national web archives and community archives are attempts to keep up; the archivist’s old question, what should be kept, has become a question about everyone’s data.',
    lineage: [
      [-2350, 'c. 2350 BC', 'The palace archive of Ebla, in Syria, holds thousands of clay tablets.'],
      [-650, 'c. 650 BC', 'Ashurbanipal gathers a library of clay tablets at Nineveh.'],
      [-285, 'c. 285 BC', 'The Library of Alexandria is founded.'],
      [1790, '1790', 'Revolutionary France creates the Archives nationales and opens records to citizens.'],
      [1876, '1876', 'Melvil Dewey publishes his decimal classification.'],
      [1898, '1898', 'Three Dutch archivists publish the manual that makes provenance the profession’s rule.'],
      [1992, '1992', 'The Stasi files are opened to the people they watched.'],
      [1996, '1996', 'The Internet Archive begins saving the web.'],
    ],
    figures: [
      ['Callimachus', 'c. 310–240 BC', 'Compiled the Pinakes, a catalogue of the Library of Alexandria.'],
      ['Paul Otlet', '1868–1944', 'Dreamed of a universal index of all knowledge, on cards.'],
      ['Henriette Avram', '1919–2006', 'Created the MARC format that put library catalogues into computers.'],
      ['Brewster Kahle', 'b. 1960', 'Founded the Internet Archive.'],
    ],
    lexicon: [
      ['Provenance', 'Where a thing has been, and who held it.'],
      ['Fonds', 'All the records made by one creator.'],
      ['Accession', 'A new arrival, formally received.'],
      ['Finding aid', 'The map to a collection.'],
      ['Appraisal', 'Deciding what to keep, and so what history will be able to know.'],
    ],
    practice: ['Records where everything came from.', 'Keeps originals and works from copies.', 'Labels in pencil.', 'Helps people find what they did not know to look for.'],
    signs: ['You keep tickets, letters and receipts.', 'Your boxes are labelled.', 'Deleting old photographs feels like a small wrong.'],
    reading: [
      ['The Library of Babel', 'Jorge Luis Borges, 1941'],
      ['Archive Fever', 'Jacques Derrida, 1995'],
      ['Silencing the Past', 'Michel-Rolph Trouillot, 1995'],
      ['Burning the Books', 'Richard Ovenden, 2020'],
      ['The Library: A Fragile History', 'Andrew Pettegree and Arthur der Weduwen, 2021'],
    ],
  },

  healer: {
    etym: 'From Old English hǣlan, “to make whole”, from the same root as whole, hale, health and holy. To heal was first to restore something to completeness.',
    def: 'One who meets reality as suffering in a body or a mind, and works to relieve it through knowledge, skill and care.',
    figure: 'Asclepius, the physician-god whose serpent-staff still marks medicine.',
    overview: [
      'The healer stands where knowledge meets another person’s pain. Medicine is the healer’s science, but healing has always included more: the touch, the explanation, the presence that makes illness bearable when it cannot be cured. The old maxim on the plate, cure sometimes, treat often, comfort always, states the proportions honestly.',
      'Healing is one of the oldest specialised roles: shamans, herbalists, midwives, bone-setters and the priests of healing gods appear in every society. What defines the archetype is an asymmetry. One person is vulnerable and must trust; the other has power and must deserve it. Medical ethics, from the Hippocratic oath onward, exists to govern that asymmetry.',
    ],
    history: [
      'The Egyptian Edwin Smith papyrus, copied around 1600 BC from older texts, describes wounds and their treatment with remarkable empiricism. Greek Hippocratic writers of the fifth and fourth centuries BC looked for natural causes of disease; Ayurveda in India and the Huangdi Neijing in China built whole systems of the body. Galen’s medicine shaped Europe and the Islamic world for over a thousand years.',
      'Islamic physicians such as al-Razi and Ibn Sina, whose Canon of Medicine (1025) was taught in Europe into the seventeenth century, developed hospitals and clinical observation. The nineteenth century added vaccination, anaesthesia (1846), antisepsis and germ theory, and Florence Nightingale made nursing a trained profession and statistics a tool of care.',
      'Antibiotics, from Fleming’s observation of penicillin in 1928, helped life expectancy rise faster in the twentieth century than ever before. New questions came with the new power: informed consent, after the medical crimes judged at Nuremberg (1947); the patient as a partner rather than an object; and how to care when cure is no longer possible, which Cicely Saunders’ hospice movement answered from 1967.',
    ],
    distinctions: [
      ['Healer and physician', 'The physician is a profession; the healer is a vocation. Nurses, carers, therapists and parents heal, and a physician can fail to.'],
      ['Cure and care', 'Cure removes the disease; care attends to the person who has it. Modern medicine excels at the first and has had to relearn the second.'],
    ],
    critique: 'Medicine has been criticised for paternalism, for treating bodies as machines, for its history of experiments on the poor and the colonised, and for the commercialisation of health. Ivan Illich’s Medical Nemesis (1975) argued that institutional medicine itself produces illness. The healer’s private shadow is the need to be needed.',
    now: 'Healers now work in teams, alongside machines and data that diagnose some conditions better than people can. The part that seems irreplaceable is the oldest: listening, explaining, and staying with someone who is afraid.',
    lineage: [
      [-1600, 'c. 1600 BC', 'The Edwin Smith papyrus records forty-eight surgical cases, with examination and treatment.'],
      [-400, 'c. 400 BC', 'Hippocratic writers in Greece look for natural causes of disease.'],
      [1025, '1025', 'Ibn Sina completes the Canon of Medicine, taught for six centuries.'],
      [1796, '1796', 'Edward Jenner tests vaccination against smallpox.'],
      [1846, '1846', 'Ether anaesthesia is demonstrated in public at Massachusetts General Hospital.'],
      [1860, '1860', 'Florence Nightingale opens her training school for nurses at St Thomas’ Hospital, London.'],
      [1928, '1928', 'Alexander Fleming notices a mould, penicillin, killing bacteria in a dish.'],
      [1967, '1967', 'Cicely Saunders opens St Christopher’s Hospice: care after cure is over.'],
    ],
    figures: [
      ['Hippocrates', 'c. 460–370 BC', 'By tradition, the one who separated medicine from magic.'],
      ['Ibn Sina', '980–1037', 'Philosopher and physician whose Canon taught Europe medicine.'],
      ['Florence Nightingale', '1820–1910', 'Founded modern nursing, and used statistics to save lives.'],
      ['Cicely Saunders', '1918–2005', 'Nurse, social worker and doctor; founded the modern hospice movement.'],
    ],
    lexicon: [
      ['Diagnosis', 'Knowing through: reading the signs of what is wrong.'],
      ['Prognosis', 'Knowing ahead: what will probably happen.'],
      ['Triage', 'Sorting the wounded by who can be helped most.'],
      ['Primum non nocere', 'First, do no harm: a later maxim, Hippocratic in spirit.'],
      ['Palliative care', 'Treatment of pain and distress when cure is not the aim.'],
    ],
    practice: ['Listens before examining.', 'Washes their hands.', 'Explains what will happen.', 'Knows when to stop treating and keep caring.'],
    signs: ['People tell you where it hurts.', 'You stay when others leave the room.', 'You read the leaflet in the medicine box.'],
    reading: [
      ['The Hippocratic Writings', '5th–4th century BC'],
      ['Notes on Nursing', 'Florence Nightingale, 1859'],
      ['Medical Nemesis', 'Ivan Illich, 1975'],
      ['The Emperor of All Maladies', 'Siddhartha Mukherjee, 2010'],
      ['Being Mortal', 'Atul Gawande, 2014'],
    ],
  },

  teacher: {
    etym: 'From Old English tǣcan, “to show, point out”, related to token: to teach was first to show by a sign. Its Latin counterpart, educare, “to bring up”, is often confused with educere, “to lead out”, and the confusion has a philosophy of its own.',
    def: 'One who meets reality as something to be passed on, and helps another person come to understand, do or become what they could not before.',
    figure: 'Chiron the centaur, who taught Achilles and Asclepius, and Athena disguised as Mentor, whose name became the word.',
    overview: [
      'Teaching is how knowledge survives the death of the knower. It is distinct from knowing: a great scientist may teach badly, and a great teacher may know relatively little but know how understanding happens. The teacher’s object is not the subject but the learner’s mind, and the art lies in finding where that mind is and what it needs next.',
      'Two images have competed through history. In one, knowledge is transmitted, from master to apprentice, in the catechism, in the lecture. In the other it is drawn out: in Plato’s Meno, Socrates questions an enslaved boy until the boy finds a geometrical proof himself, and Montessori and Dewey designed rooms where children find things out. Good teachers use both.',
    ],
    history: [
      'Formal schooling appears with writing: Sumerian scribal schools, “tablet houses”, trained scribes from the third millennium BC. In China, Confucius, around 500 BC, made teaching a moral vocation open to students of any birth; the Indian guru-shishya tradition, the Greek academies and the rabbinic houses of study each made the bond between teacher and student sacred.',
      'Medieval universities, from Bologna and Paris, institutionalised the lecture and the disputation. Printing, the Reformation and Comenius’ Great Didactic (1657) pushed toward teaching everyone to read, and nineteenth-century states made schooling compulsory.',
      'The twentieth century produced child-centred and critical pedagogies: Maria Montessori’s first Casa dei Bambini (1907), John Dewey’s experimental schools, and Paulo Freire’s Pedagogy of the Oppressed (1968), which argued that education either domesticates or liberates. Research since then has given teaching an evidence base, from retrieval practice to feedback that comes while it can still be used.',
    ],
    distinctions: [
      ['Teaching and telling', 'Telling transfers information; teaching produces understanding, which the learner has to build. The test is not what was said but what the student can now do.'],
      ['Teacher and guru', 'The teacher aims to become unnecessary; the guru, in the debased sense, keeps the disciple dependent. In the older Indian sense the guru is precisely the one who frees.'],
    ],
    critique: 'Schools have been criticised, from Rousseau to Ivan Illich’s Deschooling Society (1971), for teaching obedience, sorting children by class and killing curiosity. The teacher carries the archetype’s shadow when they teach what to think rather than how. Its glory is the reverse: Anne Sullivan spelling words into the hand of a deaf-blind child until, at the water pump, Helen Keller understood that everything has a name.',
    now: 'Teaching is being reshaped by online courses, adaptive software and artificial tutors. The evidence so far suggests that the human parts, attention, encouragement and knowing a particular child, matter more, not less, when information is everywhere.',
    lineage: [
      [-2500, 'c. 2500 BC', 'Sumerian “tablet houses” train scribes; their practice exercises survive.'],
      [-500, 'c. 500 BC', 'Confucius teaches any student who brings even the smallest gift.'],
      [-387, 'c. 387 BC', 'Plato founds the Academy in Athens.'],
      [1088, '1088', 'The traditional founding date of the University of Bologna.'],
      [1657, '1657', 'Comenius’ Great Didactic proposes teaching all things to all people.'],
      [1887, '1887', 'Anne Sullivan reaches Helen Keller at the water pump.'],
      [1907, '1907', 'Maria Montessori opens her first Casa dei Bambini in Rome.'],
      [1968, '1968', 'Paulo Freire writes Pedagogy of the Oppressed.'],
    ],
    figures: [
      ['Confucius', '551–479 BC', 'Made learning a lifelong moral practice.'],
      ['John Amos Comenius', '1592–1670', 'Wrote Orbis Pictus (1658), the first picture book for teaching children.'],
      ['Anne Sullivan', '1866–1936', 'Taught Helen Keller to read, write and speak.'],
      ['Paulo Freire', '1921–1997', 'Taught adult literacy as a path to freedom.'],
    ],
    lexicon: [
      ['Pedagogy', 'The art and science of teaching; from the Greek for the slave who walked a child to school.'],
      ['Socratic method', 'Teaching by questions that lead the learner to discover.'],
      ['Scaffolding', 'Support given and then gradually withdrawn as the learner grows.'],
      ['Zone of proximal development', 'Vygotsky’s term: what a learner can do with help, but not yet alone.'],
      ['Formative assessment', 'Checking understanding in order to adjust the teaching, not to grade.'],
    ],
    practice: ['Finds out what the student already thinks.', 'Asks more than tells.', 'Gives feedback while it can still be used.', 'Learns every student’s name.'],
    signs: ['You explain things with your hands.', 'Someone else’s understanding pleases you more than your own.', 'You still think of a teacher who changed you.'],
    reading: [
      ['Meno', 'Plato, c. 385 BC'],
      ['The Story of My Life', 'Helen Keller, 1903'],
      ['Democracy and Education', 'John Dewey, 1916'],
      ['Pedagogy of the Oppressed', 'Paulo Freire, 1968'],
      ['Why Don’t Students Like School?', 'Daniel T. Willingham, 2009'],
    ],
  },

  lover: {
    etym: 'From Old English lufu, from a Germanic root shared with Latin libet, “it pleases”, and Sanskrit lubhyati, “desires”. Greek divided the field among several words: erōs, desire; philia, friendship; storgē, family affection; agapē, self-giving love.',
    def: 'One who meets reality through attachment to another particular being, and finds in that bond the measure of what is real and what matters.',
    figure: 'Eros, and Psyche, who lost her lover by trying to see him clearly.',
    overview: [
      'The lover’s way is defined by particularity. The scientist seeks laws, the theologian the ground of all things, the sovereign rules for everyone; the lover cares about this one person, irreplaceably. Iris Murdoch’s definition, on the plate, makes love a form of knowledge: attention so complete that another self comes into view.',
      'Love is also among the most culturally shaped of experiences. Ideals of romantic love, arranged marriage, courtly devotion, same-sex friendship and divine love have varied enormously, and each has its literature. What persists is a structure: longing, union, loss, and the transformation of the self that loves.',
    ],
    history: [
      'Love poetry is among the oldest literature: Egyptian love songs on papyri of the New Kingdom, the Song of Songs, Sappho’s lyrics of the sixth century BC, the Tamil Sangam poems. Plato’s Symposium, around 385 BC, gave the West its first philosophy of love: erōs as a ladder from one beautiful body to beauty itself.',
      'The troubadours of twelfth-century southern France sang of courtly love, an idealised and often impossible devotion; Persian Sufi poets, above all Rumi, made human love a figure for love of God. The letters of Héloïse and Abelard, Dante’s Beatrice and Petrarch’s Laura made one beloved a lifelong subject.',
      'The idea that marriage should rest on romantic love spread widely only from the eighteenth century, as the historian Stephanie Coontz has traced. In the twentieth century psychology studied attachment, from Harry Harlow’s experiments with infant monkeys (1958) to John Bowlby’s theory, and the right to love whom one chooses became a political cause.',
    ],
    distinctions: [
      ['Lover and hedonist', 'The hedonist seeks pleasure, which could come from anyone or anything; the lover is bound to one other, and will accept pain for their sake.'],
      ['Erōs and agapē', 'Erōs desires the beloved; agapē gives without condition. The theologian Anders Nygren set the two against each other in 1930; most lovers know both.'],
    ],
    critique: 'Love has been called an illusion (Schopenhauer thought it the species’ trick for reproducing itself), a form of possession, and an ideology that kept women in domestic dependence. bell hooks argued that love properly understood, as care, respect and responsibility, cannot coexist with domination. The shadow on the plate, possession mistaken for love, is the oldest warning in the literature.',
    now: 'Dating apps have turned the search for a partner into a market of profiles, and loneliness is now discussed as a public-health problem. At the same time more people than ever are free to choose whom they love, and to say so.',
    lineage: [
      [-1300, 'c. 1300 BC', 'Love songs are copied on papyrus in New Kingdom Egypt.'],
      [-600, 'c. 600 BC', 'Sappho writes on Lesbos of erōs, “the loosener of limbs”.'],
      [-385, 'c. 385 BC', 'Plato’s Symposium makes love a ladder toward beauty itself.'],
      [1100, 'c. 1100', 'William IX of Aquitaine, the first troubadour known by name, sings of love.'],
      [1132, 'c. 1132', 'Héloïse and Abelard begin their letters, long after their love has ruined them both.'],
      [1258, '1258', 'Rumi begins the Masnavi, after the loss of his friend Shams.'],
      [1597, '1597', 'Romeo and Juliet is first printed.'],
      [1958, '1958', 'Harry Harlow’s “The Nature of Love” shows that affection is a need, not a luxury.'],
    ],
    figures: [
      ['Sappho', 'c. 630–570 BC', 'Poet of desire; an ancient epigram called her the tenth Muse.'],
      ['Héloïse d’Argenteuil', 'c. 1100–1164', 'Scholar and abbess, author of the most famous love letters in Europe.'],
      ['Rumi', '1207–1273', 'Made love of a friend and love of God a single subject.'],
      ['bell hooks', '1952–2021', 'Argued that love is a practice of care, respect and responsibility.'],
    ],
    lexicon: [
      ['Erōs', 'Desire; for Plato, the longing that leads toward beauty.'],
      ['Philia', 'Friendship: Aristotle’s love between people who wish each other well.'],
      ['Agapē', 'Love that gives without condition.'],
      ['Limerence', 'Dorothy Tennov’s word (1979) for the obsessive early stage of romantic love.'],
      ['Attachment', 'Bowlby’s term for the bond that gives a child, and later an adult, a secure base.'],
    ],
    practice: ['Pays attention.', 'Remembers the small things.', 'Says it.', 'Lets the other be other.'],
    signs: ['You remember what people love.', 'One person can change the colour of your day.', 'You have written something you never sent.'],
    reading: [
      ['Symposium', 'Plato, c. 385 BC'],
      ['The Letters of Abelard and Heloise', '12th century'],
      ['On Love', 'Stendhal, 1822'],
      ['A Lover’s Discourse', 'Roland Barthes, 1977'],
      ['All About Love', 'bell hooks, 2000'],
    ],
  },

  gardener: {
    etym: 'From Old North French gardin, from a Frankish word related to English yard, an enclosure. The Old Persian pairidaēza, a walled garden, passed through Greek as paradeisos: paradise.',
    def: 'One who meets reality as living growth, and works with soil, plants and seasons to bring a piece of the world to flourish.',
    figure: 'Demeter, whose grief is winter and whose joy is spring.',
    overview: [
      'Gardening is collaboration with processes one cannot command. Seeds germinate, the weather turns, pests arrive; the gardener can prepare, protect and prune, but cannot make anything grow. The resulting virtue is a particular patience, action timed to the season rather than the will. Voltaire’s “we must cultivate our garden”, the last line of Candide, makes it a philosophy of modest, practical work.',
      'The garden is also humanity’s most persistent image of the good place: Eden, the Persian paradise garden, the Chinese scholar’s garden, the Japanese dry garden, the English landscape park. Each expresses an idea of the right relation between human order and nature, from strict geometry to designed wildness.',
    ],
    history: [
      'Cultivation began around 9500 BC in the Fertile Crescent, and independently in China, Mesoamerica, the Andes, New Guinea and Africa. Pleasure gardens appear with the first cities: Egyptian tomb paintings show pools among fruit trees, and the Persian chahar bagh, a garden quartered by water channels, spread with Islam from Spain to India.',
      'Monastery gardens kept herbal knowledge alive in medieval Europe; the botanical gardens of Padua (1545) and Leiden (1590) joined gardening to science; plant hunters moved species around the world, often in the service of empire. Gregor Mendel’s pea experiments in his monastery garden founded genetics in 1866.',
      'Twentieth-century gardeners moved between ornament and ecology: Gertrude Jekyll’s planting as painting, the organic movement, Masanobu Fukuoka’s “do-nothing” farming, permaculture (1978), and the rewilding and community-garden movements, in which gardening is also a form of repair.',
    ],
    distinctions: [
      ['Gardener and farmer', 'The farmer grows at scale for a living; the gardener grows on a small scale, often for beauty as well as food. Many crops and techniques were first tried in gardens.'],
      ['Gardener and engineer', 'Both shape the world, but the engineer’s materials are inert and obey calculation, while the gardener’s are alive and have purposes of their own. A garden is never finished.'],
    ],
    critique: 'Gardens have been instruments of power and exclusion: villages cleared to make landscape parks, colonial botanical networks that served plantations, lawns that consume water and habitat. The garden as metaphor has its own danger, the urge to weed society. The shadow on the plate is control dressed as care.',
    now: 'With biodiversity in decline, gardens have become refuges for pollinators, relief from urban heat, and places of recovery for people. The gardener’s patient knowledge of soil and season has become relevant to some of the century’s largest problems.',
    lineage: [
      [-9500, 'c. 9500 BC', 'Einkorn and emmer wheat are first cultivated in the Fertile Crescent.'],
      [-1350, 'c. 1350 BC', 'A painting in the tomb of Nebamun at Thebes shows a garden pool lined with fruit trees.'],
      [-550, 'c. 550 BC', 'Cyrus the Great lays out the gardens of Pasargadae, an early quartered Persian garden.'],
      [1500, 'c. 1500', 'The dry garden of Ryōan-ji in Kyoto is laid out: fifteen stones in raked gravel.'],
      [1545, '1545', 'The botanical garden of Padua, the oldest still on its original site, is founded.'],
      [1866, '1866', 'Gregor Mendel publishes the laws he found in his monastery’s pea beds.'],
      [1975, '1975', 'Masanobu Fukuoka publishes The One-Straw Revolution.'],
      [1978, '1978', 'Bill Mollison and David Holmgren publish Permaculture One.'],
    ],
    figures: [
      ['Gregor Mendel', '1822–1884', 'Friar who found the laws of inheritance among his peas.'],
      ['Gertrude Jekyll', '1843–1932', 'Planted borders like paintings.'],
      ['Masanobu Fukuoka', '1913–2008', 'Farmed by doing as little as possible.'],
      ['Wangari Maathai', '1940–2011', 'Founded the Green Belt Movement, which has planted tens of millions of trees in Kenya.'],
    ],
    lexicon: [
      ['Compost', 'Waste turned into fertility.'],
      ['Perennial', 'A plant that comes back every year.'],
      ['Succession', 'One crop following another in the same ground.'],
      ['Phyllotaxis', 'The spiral order of leaves and seeds.'],
      ['Mycorrhiza', 'The partnership between roots and fungi that feeds most plants.'],
    ],
    practice: ['Watches before acting.', 'Feeds the soil, not the plant.', 'Saves seed.', 'Weeds a little every day.'],
    signs: ['You check the forecast for the plants’ sake.', 'You talk to them.', 'Patience comes more easily with soil on your hands.'],
    reading: [
      ['Candide', 'Voltaire, 1759'],
      ['The Well-Tempered Garden', 'Christopher Lloyd, 1970'],
      ['The One-Straw Revolution', 'Masanobu Fukuoka, 1975'],
      ['Second Nature', 'Michael Pollan, 1991'],
      ['The Well Gardened Mind', 'Sue Stuart-Smith, 2020'],
    ],
  },
}
