// The test in Your Constellation: sixteen small scenes, six answers each.
// Every archetype is the main answer to exactly four questions, so no way of being is favoured by the
// questions themselves. An answer gives two points to its archetype, and one to a second where it fits.

export const QUESTIONS = [
  {
    tag: 'The locked door',
    q: 'A locked door stands between you and a room you have heard is extraordinary.',
    a: [
      ['Study the lock. Every lock is a puzzle that went to engineering school.', 'engineer', 'scientist'],
      ['Kick it. Doors respect confidence.', 'warrior'],
      ['Ask who locked it, and what they were afraid of.', 'philosopher', 'detective'],
      ['Check the windows, the chimney, the roof, the drains.', 'explorer'],
      ['Gather everyone else in the corridor and demand it be opened.', 'rebel', 'sovereign'],
      ['Knock politely and ask if there is a party.', 'hedonist'],
    ],
  },
  {
    tag: 'The free year',
    q: 'A stranger hands you a year off, fully paid. The only condition: you must start tomorrow.',
    a: [
      ['Start a company. A year is a generous runway.', 'entrepreneur'],
      ['Finally make the thing only you could make.', 'artist'],
      ['Go somewhere silent and find out who is left when nobody is watching.', 'monk'],
      ['Watch every film on the list you have been keeping since you were fifteen.', 'cinephile'],
      ['Teach somewhere that has no teacher.', 'teacher', 'healer'],
      ['Fix your sleep, your gut and your VO₂ max, in that order.', 'biohacker'],
    ],
  },
  {
    tag: 'The dinner party',
    q: 'You are at a dinner party where you know nobody. Within the hour you have…',
    a: [
      ['…found the one person worth talking to, and stopped noticing anyone else.', 'lover'],
      ['…worked out who is secretly feuding with whom, from the seating plan alone.', 'detective'],
      ['…told the story about the ferry, and the whole table is crying with laughter.', 'storyteller'],
      ['…quietly rearranged the evening so that it actually works.', 'sovereign'],
      ['…told the host a dignified lie, purely to see how far it would go.', 'trickster'],
      ['…ended up in the kitchen, talking about the bread.', 'hedonist', 'gardener'],
    ],
  },
  {
    tag: 'The confident stranger',
    q: 'Someone on a train explains, with total confidence, exactly how the world works.',
    a: [
      ['Ask for the evidence. Politely. Then less politely.', 'scientist'],
      ['Ask what they mean by “the world”.', 'philosopher'],
      ['Ask what they believe, and why it matters so much to them.', 'theologian'],
      ['Agree enthusiastically, then argue the opposite with the same face.', 'trickster'],
      ['Ask how they would explain it to a ten-year-old.', 'teacher'],
      ['Let it pass. It does not touch anything that matters.', 'monk'],
    ],
  },
  {
    tag: 'The broken radio',
    q: 'The old radio that belonged to your grandmother finally stops working.',
    a: [
      ['Take it apart on the kitchen table. There may be screws left over.', 'engineer'],
      ['Work out exactly why it failed before touching anything.', 'detective', 'scientist'],
      ['Label it, date it and keep it in a box. It is a record now.', 'archivist'],
      ['Turn it into a lamp.', 'artist'],
      ['Play it one last time, crackle and all, and actually listen.', 'musician'],
      ['Put a plant in it. Everything is a pot if you believe.', 'gardener'],
    ],
  },
  {
    tag: 'Chaos',
    q: 'You walk into a room where everything has gone wrong at once.',
    a: [
      ['Impose an order: lists, roles, a timetable, a person in charge (you).', 'sovereign'],
      ['Find the pattern underneath it.', 'scientist'],
      ['Find the person who is hurt, and start there.', 'healer'],
      ['Write it all down. Someone will want to know what happened.', 'archivist'],
      ['Find the one variable that matters, and fix that.', 'biohacker', 'engineer'],
      ['Leave it alone for an hour. Most things settle if you let them.', 'gardener'],
    ],
  },
  {
    tag: 'The perfect evening',
    q: 'Your idea of a perfect evening is…',
    a: [
      ['A long dinner, a second bottle, and nowhere to be afterwards.', 'hedonist'],
      ['A film in a dark room, with your phone in another room.', 'cinephile'],
      ['Playing music with friends until the neighbours bang on the wall.', 'musician'],
      ['One person, and a conversation that refuses to end.', 'lover'],
      ['Working late on something that is almost, almost working.', 'engineer'],
      ['Silence, a candle, and nothing to report.', 'monk'],
    ],
  },
  {
    tag: 'Mornings',
    q: 'Your ideal morning looks like…',
    a: [
      ['A cold shower, three supplements and a sleep score in the green.', 'biohacker'],
      ['Skincare, posture, and an outfit that means business.', 'looksmaxxer'],
      ['Prayer, or something like it, before anything else.', 'theologian'],
      ['Walking round the garden in your dressing gown, inspecting.', 'gardener'],
      ['Scales, slowly, then faster.', 'musician'],
      ['Inbox zero, and a pitch deck by nine.', 'entrepreneur'],
    ],
  },
  {
    tag: 'The argument',
    q: 'You are winning an argument, clearly and fairly. Then the other person starts to cry.',
    a: [
      ['Stop. Make tea. You can be right tomorrow.', 'healer'],
      ['Hold your ground, kindly. Feelings are not counter-arguments.', 'warrior'],
      ['Ask what is really wrong. It is never about the thing.', 'lover', 'detective'],
      ['Check your sources again. If you are this sure, you might be wrong.', 'scientist'],
      ['Tell a story about a time you were wrong. It is only slightly invented.', 'storyteller'],
      ['Laugh. They laugh. Nobody remembers what it was about.', 'trickster'],
    ],
  },
  {
    tag: 'The museum',
    q: 'You have exactly one hour in an enormous museum.',
    a: [
      ['Find the single greatest painting and stand in front of it for fifty minutes.', 'artist'],
      ['Read every label. Every single one.', 'archivist'],
      ['Get deliberately lost in the wings nobody visits.', 'explorer'],
      ['Find the oldest object in the building and imagine who made it.', 'storyteller'],
      ['Work out how they keep the temperature and humidity so steady.', 'engineer', 'scientist'],
      ['Find the room where an old film runs on a loop, and stay there.', 'cinephile'],
    ],
  },
  {
    tag: 'The stupid rule',
    q: 'There is a rule at work that everyone privately agrees is ridiculous.',
    a: [
      ['Break it, openly, and invite them to fire you.', 'rebel'],
      ['Follow it until you are in a position to change it properly.', 'sovereign'],
      ['Find the loophole, then build a little business inside it.', 'entrepreneur', 'trickster'],
      ['Find out who made it, and when. It was probably a good idea in 1987.', 'detective', 'archivist'],
      ['Ask whether a rule nobody believes in is still a rule.', 'philosopher'],
      ['Write a song about it and perform it at the office party.', 'musician'],
    ],
  },
  {
    tag: 'The shop window',
    q: 'You catch your reflection in a shop window.',
    a: [
      ['Adjust your posture, then your collar, then your angle.', 'looksmaxxer'],
      ['Notice how tired you look, and resolve, again, to sleep more.', 'biohacker'],
      ['Frame it. Reflection, street, low sun: that is a shot.', 'cinephile'],
      ['Wonder, briefly, which one of you is real.', 'philosopher'],
      ['Miss it entirely. You were watching a stranger who looked lost.', 'healer'],
      ['Meet your own eye. You have been through worse than this.', 'warrior'],
    ],
  },
  {
    tag: 'The last word',
    q: 'At the very end, what would you most like said of you?',
    a: [
      ['That they never gave up.', 'warrior'],
      ['That they went where no one had been.', 'explorer'],
      ['That they were at peace.', 'monk'],
      ['That they made something beautiful.', 'artist'],
      ['That they loved well.', 'lover'],
      ['That they refused to go along.', 'rebel'],
    ],
  },
  {
    tag: 'The power cut',
    q: 'The power goes out across the whole city, for a week.',
    a: [
      ['Organise the street: a water rota, a food store, a list of who needs checking on.', 'sovereign', 'healer'],
      ['Knock on every door on the stairwell, one by one.', 'healer'],
      ['Teach the children by candlelight, because school is still school.', 'teacher'],
      ['Finally read the box of letters in the attic.', 'archivist'],
      ['Plant the vegetables you always said you would.', 'gardener'],
      ['Sell candles at a fair price. Mostly fair.', 'entrepreneur'],
    ],
  },
  {
    tag: 'The letter',
    q: 'A letter arrives in handwriting you do not recognise. No return address.',
    a: [
      ['Examine the postmark, the paper and the ink before you open it.', 'detective'],
      ['Open it at once and read it aloud to whoever is nearby.', 'storyteller'],
      ['Hold it a moment first. Some messages deserve a little reverence.', 'theologian'],
      ['Refuse to open it until the sender has the courage to sign it.', 'rebel'],
      ['Admire the handwriting, and wonder how your own would look in that ink.', 'looksmaxxer', 'artist'],
      ['Assume it is a prank, and start planning a better one in reply.', 'trickster'],
    ],
  },
  {
    tag: 'The last day',
    q: 'Someone tells you the world ends tomorrow, and for once they seem to be right.',
    a: [
      ['Throw a feast. Invite everyone. Open the good wine.', 'hedonist'],
      ['Climb somewhere high and far to watch the last sunset.', 'explorer'],
      ['Pray, or sit very still, or both.', 'theologian', 'monk'],
      ['Find out whether it is actually true.', 'scientist'],
      ['Teach someone something useful, just in case.', 'teacher'],
      ['Look your absolute best. If this is the last photograph, make it a good one.', 'looksmaxxer'],
    ],
  },
]

// A line from the archetype just chosen, shown above the next question.
export const REACT = {
  scientist: ['The scientist writes that down, with a date.', 'Somewhere, a control group nods.'],
  philosopher: ['The philosopher asks what you mean by “chose”.', 'A question mark settles on your shoulder.'],
  theologian: ['The theologian lights a candle for that one.', 'Noted, in a very old book.'],
  detective: ['The detective adds it to the board, with red string.', 'Interesting. Very interesting.'],
  engineer: ['The engineer checks the load. It holds.', 'Somewhere, a bolt is tightened.'],
  artist: ['The artist squints at you, approvingly.', 'That would look good in charcoal.'],
  musician: ['A chord resolves somewhere.', 'The musician taps it out on the table.'],
  storyteller: ['The storyteller leans in: and then?', 'That is going straight into the anecdote.'],
  warrior: ['The warrior cracks their knuckles.', 'A drum, somewhere, approves.'],
  monk: ['The monk says nothing, which is high praise.', 'A bell rings, once, very quietly.'],
  biohacker: ['The biohacker logs it against your baseline.', 'Heart rate: unchanged. Excellent.'],
  looksmaxxer: ['The looksmaxxer adjusts your collar.', 'Good angle.'],
  sovereign: ['The sovereign adds it to the record.', 'A seal is pressed into wax.'],
  rebel: ['The rebel grins: not like that, then.', 'Someone, somewhere, refuses with you.'],
  entrepreneur: ['The entrepreneur sees an opportunity in that.', 'That could scale.'],
  trickster: ['The trickster swaps two of your answers. Just kidding.', 'Somewhere, a rule breaks quietly.'],
  explorer: ['The explorer marks it on the map.', 'A compass needle swings toward you.'],
  hedonist: ['The hedonist orders another round.', 'Delicious choice.'],
  cinephile: ['Cut. Print. Moving on.', 'The cinephile frames that one with their fingers.'],
  archivist: ['Filed, with a catalogue number.', 'The archivist keeps that, in pencil.'],
  healer: ['The healer takes your pulse. Steady.', 'Someone feels a little better, for no clear reason.'],
  teacher: ['The teacher gives that a quiet tick.', 'Good. Now show your working.'],
  lover: ['The lover smiles at you across the room.', 'Someone, somewhere, is thinking of you.'],
  gardener: ['The gardener nods, and waters something.', 'A seed decides to germinate.'],
}

// The reading for each archetype, written to the person who scored highest in it.
export const RESULTS = {
  scientist: {
    epithet: 'The Patient Doubter',
    blurb: 'You do not believe things because they are said loudly, or often, or by people in nice jackets. You want to see the data, and then you want to see how the data was collected. This makes you excellent company in a crisis and mildly exhausting at a wellness retreat.',
    power: 'Changing your mind when the evidence changes, which is rarer than it should be.',
    blind: 'Treating everything that cannot be measured as if it does not quite count.',
    party: 'Quietly fact-checking the anecdote, then deciding, kindly, not to mention it.',
    try: 'Run one experiment on your own life this month, with a control.',
  },
  philosopher: {
    epithet: 'The Professional Wonderer',
    blurb: 'Where other people see answers, you see assumptions holding them up. You are the person who asks “but why?” one more time than is socially comfortable, and occasionally that question turns out to be the important one.',
    power: 'Seeing the hidden premise in any argument, including your own.',
    blind: 'Turning every decision into a seminar while the soup goes cold.',
    party: 'In the corner, at two in the morning, arguing about whether numbers exist.',
    try: 'Define one word you use every day, properly. Then try to live by the definition.',
  },
  theologian: {
    epithet: 'The Seeker of Ground',
    blurb: 'You suspect that reality has a depth, a source, or a meaning that the surface does not show, and you think that suspicion deserves rigorous thought rather than vague feeling. You take the biggest questions seriously, and you can disagree about them without contempt.',
    power: 'Holding faith and doubt in the same hand without dropping either.',
    blind: 'Forgetting that the person across the table may have reached the opposite conclusion just as honestly.',
    party: 'Having the conversation everyone else was avoiding, gently.',
    try: 'Read one sacred text from a tradition that is not your own, slowly.',
  },
  detective: {
    epithet: 'The Noticer',
    blurb: 'You see the tan line where the watch used to be. You notice when a story changes slightly on its second telling. You enjoy puzzles that have an answer, and you are uneasy until you have it.',
    power: 'Attention to the small detail that does not fit.',
    blind: 'Falling in love with your first theory and recruiting the evidence to defend it.',
    party: 'Working out the host’s marriage from the coasters.',
    try: 'Next time you are certain, write down what evidence would change your mind.',
  },
  engineer: {
    epithet: 'The Fixer',
    blurb: 'When something is broken, you feel it as a physical itch. You think in constraints, tolerances and trade-offs, and you get a deep, quiet satisfaction from things that simply work. Nobody thanks you for the bridge that did not fall down, and you do not need them to.',
    power: 'Turning a vague wish into a working plan.',
    blind: 'Solving the problem as stated, when the real problem was different.',
    party: 'Fixing the host’s wobbly table with a folded beer mat, without being asked.',
    try: 'Before you build the next thing, ask who will use it, and watch them try.',
  },
  artist: {
    epithet: 'The Maker of Ways of Seeing',
    blurb: 'You notice colour before name and shape before function. You do not want only to describe the world; you want to add something to it that was not there before, and that makes everything around it look a little different.',
    power: 'Making other people see what you see.',
    blind: 'Waiting to feel inspired before starting, sometimes for years.',
    party: 'Drawing the guests on the back of the menu, unflatteringly but accurately.',
    try: 'Make one small thing every day for a week, and finish every one.',
  },
  musician: {
    epithet: 'The Keeper of Time',
    blurb: 'You hear the world as rhythm and interval: the dripping tap in three-four, the bus that brakes in a minor key. Music is how you feel things with other people without having to explain them.',
    power: 'Reading the tempo of a room and changing it.',
    blind: 'Practising so much that you forget to play.',
    party: 'Commandeering the playlist, for everyone’s good.',
    try: 'Learn one song by ear, from start to finish, with no notation.',
  },
  storyteller: {
    epithet: 'The Maker of Meaning',
    blurb: 'You remember people by their stories and events by their shape. You know instinctively where a story should start (not at the beginning) and where it should end (just before people expect). You make life feel more like it means something.',
    power: 'Holding a room with nothing but a voice.',
    blind: 'Improving the truth for the sake of the arc.',
    party: 'Telling the ferry story. Again. To great acclaim.',
    try: 'Tell a true story with no improvements at all, and see whether it still works.',
  },
  warrior: {
    epithet: 'The One Who Stays',
    blurb: 'You meet difficulty head on. Where others look for the way round, you look for the way through, and you train for the moment before it comes. People call you when something has to be faced.',
    power: 'Discipline that does not depend on mood.',
    blind: 'Needing an opponent, and finding one when there isn’t one.',
    party: 'Challenging someone to arm-wrestle, then winning graciously.',
    try: 'Win one argument this month by losing it on purpose.',
  },
  monk: {
    epithet: 'The Quiet Centre',
    blurb: 'You suspect that most of what people chase is noise. You are good at stopping, at doing without, at sitting with something until it becomes clear. Other people find you calming, sometimes without knowing why.',
    power: 'Attention that does not grasp.',
    blind: 'Detaching from things that deserved your fight.',
    party: 'Leaving early, untroubled, after one long and memorable conversation.',
    try: 'Sit in silence for ten minutes a day for a week, and notice what notices.',
  },
  biohacker: {
    epithet: 'The Self-Experimenter',
    blurb: 'Your body is a system, and systems can be measured and improved. You know your resting heart rate, your caffeine cut-off and your best bedtime to the quarter hour. You are, at least, very well rested.',
    power: 'Changing one variable at a time, and noticing what it did.',
    blind: 'Optimising the numbers while the life they measure goes unlived.',
    party: 'Explaining glucose spikes over dessert, to a mixed reception.',
    try: 'Spend one day measuring nothing at all.',
  },
  looksmaxxer: {
    epithet: 'The Curator of the Surface',
    blurb: 'You understand that appearance is the first thing anyone meets, and you treat it as a craft rather than a vanity. You know your best angle, your colours and your posture, and you show up looking like you meant to.',
    power: 'Making care visible.',
    blind: 'Hearing the mirror’s criticisms louder than anyone else’s praise.',
    party: 'Best dressed, without seeming to try (you tried).',
    try: 'Take one photograph of yourself and refuse to retake it.',
  },
  sovereign: {
    epithet: 'The One Who Decides',
    blurb: 'You see a group of people and immediately see how they could be organised. You are comfortable with responsibility, and with the loneliness of making the call. Things around you tend to run on time.',
    power: 'Making order that lets other people get on with their lives.',
    blind: 'Forgetting that authority is lent, not owned.',
    party: 'Quietly running the seating plan, the playlist and the taxis home.',
    try: 'Hand one decision you would normally make to someone else, and live with the result.',
  },
  rebel: {
    epithet: 'The One Who Says No',
    blurb: 'You cannot follow a rule you cannot justify. You side with the outnumbered, and “that’s just how it is” sounds to you like a challenge. You know that most freedoms began with somebody refusing.',
    power: 'Courage to say no in public, and to pay for it.',
    blind: 'Needing an oppressor to know who you are.',
    party: 'Arguing with the bouncer, on principle, for someone else.',
    try: 'Name what you are refusing for, not only what you are refusing against.',
  },
  entrepreneur: {
    epithet: 'The Opportunist (Affectionate)',
    blurb: 'Every annoyance looks to you like a business waiting to happen. You are comfortable with uncertainty in a way that frightens other people, and you would rather be wrong quickly than right too late.',
    power: 'Turning a hunch into something other people use.',
    blind: 'Treating every friend as a contact and every hour as runway.',
    party: 'Leaving with three business cards and a co-founder.',
    try: 'Do one thing this week that cannot possibly be monetised.',
  },
  trickster: {
    epithet: 'The Licensed Fool',
    blurb: 'You know that most rules were made up by someone, and you enjoy reminding people of it. You see the absurdity in solemn things, and your mischief often lets in air that a room badly needed.',
    power: 'Laughter that shows that things could be otherwise.',
    blind: 'Not knowing when the joke has stopped being kind.',
    party: 'Convincing the host you have met before. You have not.',
    try: 'Once this month, take something completely seriously. See what happens.',
  },
  explorer: {
    epithet: 'The Edge-Walker',
    blurb: 'The unmarked path calls to you, and the second visit bores you slightly. You learn by going: by foot, by ticket, by accident. Your knowledge is first-hand, and your list of places only gets longer.',
    power: 'Comfort with the unknown.',
    blind: 'Leaving before you have really arrived.',
    party: 'Found in a room nobody else knew the house had.',
    try: 'Explore one place you have been a hundred times as if you had never seen it.',
  },
  hedonist: {
    epithet: 'The Connoisseur',
    blurb: 'You take pleasure seriously, which is rarer than it sounds. You know good bread, good company and the right moment for the second bottle, and you understand, as Epicurus did, that the trick is quality, not quantity.',
    power: 'Savouring what everyone else rushes past.',
    blind: 'Mistaking more for better.',
    party: 'The reason it was a good party.',
    try: 'Eat one meal this week with no screen, no rush and full attention.',
  },
  cinephile: {
    epithet: 'The Frame-Reader',
    blurb: 'You see the world in shots and cuts. You know who held the camera, you stay for the credits, and you can tell a good film from an expensive one in the first ten minutes. Life, to you, is best understood at 24 frames per second.',
    power: 'Seeing what was chosen, and what was left out.',
    blind: 'Watching your own life from the back row.',
    party: 'Recommending a four-hour Hungarian film with total sincerity.',
    try: 'Go out without a screen and notice how many shots you see in a single street.',
  },
  archivist: {
    epithet: 'The Keeper',
    blurb: 'You keep the ticket, the letter, the receipt. You label your boxes. You know that the past survives only because somebody bothered to keep it, and you are, quietly, that somebody.',
    power: 'Making sure things can be found again.',
    blind: 'Keeping everything, and so finding nothing.',
    party: 'Remembering exactly what everyone said at the last one.',
    try: 'Choose one box to keep, and let one go.',
  },
  healer: {
    epithet: 'The One Who Notices Pain',
    blurb: 'You see the person who is struggling before anyone else does, and you move toward them. You know that comfort is a skill, and that sometimes the most useful thing is simply to stay in the room.',
    power: 'Making suffering easier to bear.',
    blind: 'Needing to be needed, and forgetting to look after yourself.',
    party: 'In the kitchen with the person who is having a terrible evening.',
    try: 'Let someone look after you this month, without arguing.',
  },
  teacher: {
    epithet: 'The Lighter of Fires',
    blurb: 'You get more pleasure from someone else understanding than from understanding things yourself. You explain with your hands, you find the example that makes it click, and you remember the teacher who changed you.',
    power: 'Finding where someone’s mind is, and what it needs next.',
    blind: 'Explaining when nobody asked.',
    party: 'Teaching someone a card trick, then the maths behind it.',
    try: 'Learn something you are bad at, from someone younger than you.',
  },
  lover: {
    epithet: 'The Devoted',
    blurb: 'You meet the world through particular people. One person can change the colour of your day, and you remember what everyone loves. To you, attention is the deepest form of respect, and being known is the point of it all.',
    power: 'Seeing another person completely.',
    blind: 'Losing yourself in someone else’s weather.',
    party: 'Talking to one person all night, and calling it the best party in years.',
    try: 'Tell someone exactly what you admire about them, today.',
  },
  gardener: {
    epithet: 'The Patient Tender',
    blurb: 'You know that most good things cannot be forced. You work with seasons, soil and slow time, and you are happiest with your hands in something living. You leave places more alive than you found them.',
    power: 'Patience that is active, not passive.',
    blind: 'Weeding what should have been allowed to grow.',
    party: 'Taking cuttings home from the host’s plants, with permission (mostly).',
    try: 'Plant something you will not see mature.',
  },
}

// What it means when one order dominates the shape.
export const ORDER_READING = {
  knowing: 'Mostly Knowing. You meet reality as a question with an answer, and you will not rest until you have found it, checked it, and found the flaw in it.',
  making: 'Mostly Making. You meet reality as raw material. Something in you is not satisfied until it has added a new thing to the world.',
  self: 'Mostly Disciplines. You meet reality by working on the one who meets it: training, refining, subtracting.',
  city: 'Mostly the City. You meet reality as a matter of rules and power: who decides, who refuses, who profits, who laughs.',
  beholding: 'Mostly Beholding. You meet reality as something to receive: to go to, to taste, to watch, to keep.',
  tending: 'Mostly Tending. You meet reality through other living things: their bodies, minds, hearts and growth.',
}
